
TRUNCATE TABLE BENEFICIARY_REL_PERCENT;

INSERT INTO BENEFICIARY_REL_PERCENT
   (PSN,
    SSN,
    KIND_ID,
    PERCENT,
    RELATIONSHIP)
SELECT
    PYREL_PSN,
    PYREL_PAYSSN,
    CASE 
            WHEN PYREL_TYPE = 'P' THEN 'P'
            ELSE 'S'
    END AS TYPE_ID,     
    PYREL_PERCENT,
    PYREL_RELATION
FROM PROFITSHARE.PAYREL;
