
TRUNCATE TABLE DISTRIBUTION;

INSERT INTO DISTRIBUTION
   (SSN,
    SEQUENCE_NUMBER,
    EMPLOYEE_NAME,
    FREQUENCY_ID,
    STATUS_ID,
    PAYEE_SSN, 
    PAYEE_NAME,
    STREET, 
    CITY,
    STATE,
    POSTAL_CODE,
    THIRD_PARTY_PAYEEE,
    THIRD_PARTY_NAME,
    THIRD_PARTY_STREET,
    THIRD_PARTY_STREET2,
    THIRD_PARTY_CITY,
    THIRD_PARTY_STATE,
    THIRD_PARTY_POSTAL_CODE,
    THIRD_PARTY_ACCOUNT,
    FORTHEBENEFITOF_PAYEE,
    FORTHEBENEFITOF_ACCOUNT_TYPE,
    TAX1099_FOR_EMPLOYEE,
    TAX1099_FOR_BENEFICIARY,
    FEDERAL_TAX_PERCENTAGE,
    STATE_TAX_PERCENTAGE,
    GROSS_AMOUNT,
    FEDERAL_TAX_AMOUNT,
    STATE_TAX_AMOUNT,
    CHECK_AMOUNT,
    TAX_CODE_ID,
    DECEASED,
    GENDER_ID,
    QDRO,
    MEMO,
    ROTH_IRA)
SELECT
    PROFDIST_SSN,
    PROFDIST_PAYSEQ,
    PROFDIST_EMPNAME,
    PROFDIST_PAYFREQ,
    PROFDIST_PAYFLAG,
    PROFDIST_PAYSSN,
    PROFDIST_PAYNAME,
    PROFDIST_PAYADDR1,
    PROFDIST_PAYCITY,
    PROFDIST_PAYSTATE,
    TO_NCHAR(PROFDIST_PAYZIP1) || PROFDIST_PAYZIP2,
    PROFDIST_3RDPAYTO,
    PROFDIST_3RDNAME,
    PROFDIST_3RDADDR1,
    PROFDIST_3RDADDR2,
    PROFDIST_3RDCITY,
    PROFDIST_3RDSTATE,
    TO_NCHAR(PROFDIST_3RDZIP1) || PROFDIST_3RDZIP2,
    PROFDIST_3RDACCT,
    PROFDIST_FBOPAYTO,
    PROFDIST_FBOTYPE,
    CASE
         WHEN PROFDIST_1099_INFO_EMP = 'Y' THEN 1
         ELSE 0
    END as acode,
    CASE
         WHEN PROFDIST_OTHER_BENEFICIARY = 'Y' THEN 1
         ELSE 0
    END as bcode,
    PROFDIST_FEDPCT,
    PROFDIST_STATEPCT,
    PROFDIST_GROSSAMT,
    PROFDIST_FEDTAX,
    PROFDIST_STATETAX,
    PROFDIST_CHECKAMT,
    PROFDIST_TAXCODE,
    CASE
         WHEN PROFDIST_DECEASED = 'Y' THEN 1
         ELSE 0
    END as ccode,
    CASE
         WHEN PROFDIST_SEX = 'M' THEN 'M'
         WHEN PROFDIST_SEX ='F' THEN 'F'
           ELSE NULL           
    END as psex,
    CASE
         WHEN PROFDIST_QDRO = 'Y' THEN 1
         ELSE 0
    END as dcode,
    PROFDIST_MEMO,
    CASE
         WHEN PROFDIST_ROTH_IRA = 'Y' THEN 1
         ELSE 0
    END as ecode
FROM PROFITSHARE.PROFDIST;
