

INSERT INTO PROFIT_DETAIL
   (PROFIT_YEAR,
    PROFIT_YEAR_ITERATION,
    PROFIT_CODE_ID,
    CONTRIBUTION,
    EARNINGS,
    FORFEITURE,
    ZERO_CONTRIBUTION_REASON_ID,
    FEDERAL_TAXES,
    STATE_TAXES,
    TAX_CODE_ID,
    SSN,
    DISTRIBUTION_SEQUENCE,
    MONTH_TO_DATE,
    REMARK,
    YEAR_TO_DATE)
SELECT
    TRUNC(PROFIT_SS_YEAR),
    MOD(PROFIT_SS_YEAR * 10, 10),
    PROFIT_SS_CODE,
    PROFIT_SS_CONT,
    PROFIT_SS_EARN,
    PROFIT_SS_FORT,
    PROFIT_SS_ZEROCONT,
    NVL(PROFIT_SS_FED_TAXES,0),
    NVL(PROFIT_SS_STATE_TAXES,0),
    CASE
         WHEN TRIM(PROFIT_SS_TAX_CODE) = '0' THEN NULL
         ELSE TRIM(PROFIT_SS_TAX_CODE)           
    END as ptcode,
    PR_SS_D_S_SEC_NUMBER,
    PROFIT_SS_DET_PR_SS_D_S_SEQNUM,
    PROFIT_SS_MDTE,
    CASE
         WHEN TRIM(PROFIT_SS_CMNT) = '' THEN NULL
         ELSE PROFIT_SS_CMNT           
    END as pcmnt,
    CASE 
        WHEN TO_NUMBER(PROFIT_SS_YDTE) >= 59 THEN '19' || PROFIT_SS_YDTE
        ELSE '20' || PROFIT_SS_YDTE
    END AS FOUR_DIGIT_YEAR
FROM PROFITSHARE.PROFIT_SS_DETAIL;
