using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Demoulas.ProfitSharing.Common.Enums;
/// <summary>
/// https://demoulas.atlassian.net/wiki/spaces/MAIN/pages/31887785/DEMOGRAPHICS
/// </summary>
public enum PayClassification
{
    Manager = 1,
    AssistantManager = 2,
    FrontEndManager = 10,
    AssistantHeadCashier = 11,
    CashiersAM = 13,
    CashiersPM = 14,
    Cashiers14_15 = 15,
    SackersAM = 16,
    SackersPM = 17,
    Sackers14_15 = 18,
    StoreMaintenance = 19,
    OfficeManager = 20,
    CourtesyBoothAM = 22,
    CourtesyBoothPM = 23,
    POSFullTime = 24,
    ClerkFullTimeAP = 25,
    ClerksFullTimeAR = 26,
    ClerksFullTimeGroc = 27,
    ClerksFullTimePerishables = 28,
    ClerksFullTimeWarehouse = 29,
    Merchandiser = 30,
    GroceryManager = 31,
    EndsPartTime = 32,
    FirstMeatCutter = 33,
    NotUsed35 = 35,
    CafePartTime = 37,
    Receiver = 38,
    NotUsed39 = 39,
    MeatCutters = 40,
    ApprMeatCutters = 41,
    MeatCutterPartTime = 42,
    TraineeMeatCutter = 43,
    PartTimeSubshop = 44,
    AsstSubShopManager = 45,
    ServiceCaseFullTime = 46,
    WrappersFullTime = 47,
    WrappersPartTimeAM = 48,
    WrappersPartTimePM = 49,
    HeadClerk = 50,
    SubShopManager = 51,
    ClerksFullTimeAM = 52,
    ClerksPartTimeAM = 53,
    ClerksPartTimePM = 54,
    POSPartTime = 55,
    MarketsKitchenAsstMgr = 56,
    MarketsKitchenFT = 57,
    MarketsKitchenPT = 58,
    KitchenManager = 59,
    NotUsed60 = 60,
    PTBakeryMerchandiser = 61,
    FTCakeAndCreams = 62,
    CakeAndCreamPT = 63,
    OverWorkerPT = 64,
    BenchWorkerPT = 65,
    ForkLiftOprRecAM = 66,
    ForkLiftOprRecPM = 67,
    ForkLiftOprShipAM = 68,
    ForkLiftOprShipPM = 69,
    ForkLiftOprMiscAM = 70,
    ForkLiftOprMiscPM = 71,
    LoaderAM = 72,
    LoaderPM = 73,
    WhseMaintenanceAM = 74,
    WhseMaintenancePM = 75,
    SelectorPartTimeAM = 77,
    SelectorPartTimePM = 78,
    SelectorFullTimeAM = 79,
    TempFullTime = 80,
    SelectorFullTimePM = 81,
    Inspector = 82,
    GeneralWarehouseAM = 83,
    GeneralWarehousePM = 84,
    DriverTrailer = 85,
    DriverStraight = 86,
    Mechanic = 87,
    GaragePM = 88,
    FacilityOperations = 89,
    ComputerOperations = 90,
    SignShop = 91,
    Inventory = 92,
    Programming = 93,
    HelpDesk = 94,
    Defunct = 95,
    TechnicalSupport = 96,
    Training = 98
}

