export const HISTORY_KEY = "navigation_history" as const;

export const drawerOpenWidth = 320;
export const drawerClosedWidth = 64;

export const MENU_LABELS = {
  FISCAL_CLOSE: "Fiscal Close",
  DECEMBER_ACTIVITIES: "December Activities",
  BENEFICIARIES: "Beneficiaries",
  DISTRIBUTIONS: "Distributions",
  RECONCILIATION: "Reconciliation",
  INQUIRIES: "Inquiries",
  YEAR_END: "Year End",
  IT_OPERATIONS: "IT OPERATIONS"
} as const;

export const ROUTES = {
  FISCAL_CLOSE: "fiscal-close",
  DISTRIBUTIONS_AND_FORFEITURES: "distributions-and-forfeitures",
  MANAGE_EXECUTIVE_HOURS: "manage-executive-hours-and-dollars",
  ELIGIBLE_EMPLOYEES: "eligible-employees",
  YTD_WAGES_EXTRACT: "ytd-wages-extract",
  DISTRIBUTIONS_BY_AGE: "distributions-by-age",
  CONTRIBUTIONS_BY_AGE: "contributions-by-age",
  FORFEITURES_BY_AGE: "forfeitures-by-age",
  BALANCE_BY_AGE: "balance-by-age",
  BALANCE_BY_YEARS: "balance-by-years",
  VESTED_AMOUNTS_BY_AGE: "vested-amounts-by-age",
  PROF_TERM: "prof-term",
  MILITARY_ENTRY_AND_MODIFICATION: "military-entry-and-modification",

  DECEMBER_PROCESS_ACCORDION: "december-process-accordion",
  DEMOGRAPHIC_BADGES: "demographic-badges-not-in-payprofit",
  DUPLICATE_SSNS: "duplicate-ssns-demographics",
  NEGATIVE_ETVA: "negative-etva-for-ssns-on-payprofit",
  DUPLICATE_NAMES: "duplicate-names-and-birthdays",
  MISSING_COMMA: "missing-comma-in-py-name",
  MILITARY_LEAVE: "employees-on-military-leave",
  REHIRE_FORFEITURES: "rehire-forfeitures",
  PROFIT_SHARE_REPORT: "profit-share-report",
  PROFIT_SHARE_REPORT_EDIT_RUN: "profit-share-report-edit-run",
  PROFIT_SHARE_REPORT_FINAL_RUN: "profit-share-report-final-run",
  PROFIT_SHARE_UPDATE: "profit-share-update",

  FROZEN_SUMMARY: "frozen-summary",
  MASTER_INQUIRY: "master-inquiry",

  PAY426_ACTIVE_18_20: "pay426-1",
  PAY426_ACTIVE_21_PLUS: "pay426-2",
  PAY426_ACTIVE_UNDER_18: "pay426-3",
  PAY426_ACTIVE_PRIOR_SHARING: "pay426-4",
  PAY426_ACTIVE_NO_PRIOR: "pay426-5",
  PAY426_TERMINATED_1000_PLUS: "pay426-6",
  PAY426_TERMINATED_NO_PRIOR: "pay426-7",
  PAY426_TERMINATED_PRIOR: "pay426-8",
  PAY426_SUMMARY: "pay426-9",
  PAY426_NON_EMPLOYEE: "pay426-10",
  FORFEIT: "forfeit",
  PAYMASTER_UPDATE: "paymaster-update",
  PROFIT_SHARE_BY_STORE: "profit-share-by-store",
  PROFIT_SHARE_GROSS_REPORT: "profit-share-gross-report",
  PAY450_SUMMARY: "pay450-summary",
  PROF_CTRLSHEET: "prof-control-sheet",
  UNDER_21_REPORT: "under-21-report",
  QPAY066_UNDER21: "qpay066-under21",
  QPAY066TA_UNDER21: "qpay066ta-under21",
  QPAY066TA: "qpay066ta",
  NEW_PS_LABELS: "new-ps-labels",
  PROFALL: "profall",
  DEMO_FREEZE: "demographic-freeze"
} as const;

export const CAPTIONS = {
  BALANCE_BY_AGE: "Get Balance by Age (PROF 130B)",
  BALANCE_BY_YEARS: "Get Balance by Years (PROF 130Y)",
  CONTRIBUTIONS_BY_AGE: "Get Contributions by Age (PROF 130)",
  CLEAN_UP_REPORTS: "Clean Up Reports",
  DEMOGRAPHIC_BADGES: "Demographic Badges Not In Payprofit",
  DECEMBER: "December",
  FISCAL_CLOSE: "Fiscal Close",
  POST_FROZEN: "Post Frozen",
  DISTRIBUTIONS_AND_FORFEITURES: "Distributions and Forfeitures (QPAY129)",
  DISTRIBUTIONS_BY_AGE: "Get Distributions by Age (PROF 130)",
  DUPLICATE_NAMES: "Duplicate Names and Birthdays",
  DUPLICATE_SSNS: "Duplicate SSNs in Demographics",
  ELIGIBLE_EMPLOYEES: "Get Eligible Employees",
  MILITARY_LEAVE: "Military Leave (QPAY 511)",
  FORFEIT: "Forfeit",
  FORFEITURES_BY_AGE: "Get Forfeitures by Age (PROF 130)",
  MANAGE_EXECUTIVE_HOURS: "Manage Executive Hours and Dollars (TPR008-09)",
  MASTER_INQUIRY: "Master Inquiry",
  MILITARY_ENTRY_AND_MODIFICATION: "Military Entry and Modification",
  MILITARY_CONTRIBUTIONS: "Military Contributions",
  REHIRE_FORFEITURES: "Rehire Forfeitures (PREVPROF)",
  MISSING_COMMA: "Missing Comma in Full Name",
  NEGATIVE_ETVA: "Negative ETVA for SSNs on Payprofit",
  NEW_PS_LABELS: "New PS Labels",
  PAY_SHARE_BY_STORE_REPORTS: "Pay Share By Store Reports",
  PAY426_ACTIVE_18_20: "Active/inactive employees age 18 - 20 with 1000 hours or more",
  PAY426_ACTIVE_21_PLUS: "Active/inactive employees age 21 & with 1000 hours or more",
  PAY426_ACTIVE_NO_PRIOR: "Active/inactive employees 18 and older with no prior profit sharing amounts and <1000 hours",
  PAY426_ACTIVE_PRIOR_SHARING:
    "Active/inactive employees 18 and older with prior profit sharing amounts and <1000 hours",
  PAY426_ACTIVE_UNDER_18: "Active/inactive employees under 18",
  PAY426_NON_EMPLOYEE: "All non-employee beneficiaries",
  PAY426_SUMMARY: "Profit sharing summary page",
  PAY426_TERMINATED_1000_PLUS: "Terminated employees 18 and older with 1000 hours or more",
  PAY426_TERMINATED_NO_PRIOR: "Terminated employees 18 and older with no prior profit sharing amounts and < 1000 hours",
  PAY426_TERMINATED_PRIOR: "Terminated employees 18 and older with prior profit sharing amounts and < 1000 hours",
  PAY450_SUMMARY: "Update Summary for Profit Sharing (Pay450)",
  PAY450: "PAY450",
  PAYMASTER_UPDATE: "Paymaster Update",
  PROF_CTRLSHEET: "Prof-CTRL-SHEET",
  PROFALL: "PROFALL Report",
  PROFIT_SHARE_BY_STORE: "Profit Share by Store",
  PROFIT_SHARE_GROSS_REPORT: "Profit Share Gross Report",
  PROFIT_SHARE_REPORT_EDIT_RUN: "Profit Share Report Edit Run (PAY426)",
  PROFIT_SHARE_REPORT_FINAL_RUN: "Profit Share Report Final Run (PAY426)",
  PROFIT_SHARE_REPORT: "Profit Share Report (PAY426)",
  PROFIT_SHARE_UPDATE: "Profit Share Update (PAY444 PAY447 PAY460 PROFTLD)",
  PROFIT_SHARING_CONTROL_SHEET: "Profit Sharing Control Sheet",
  QPAY066_UNDER21: "QPAY066-UNDR21",
  QPAY066TA_UNDER21: "QPAY066TA-UNDR21",
  QPAY066TA: "QPAY066TA",
  REPORTS_BY_AGE: "Reports by Age",
  SUMMARY: "Summary",
  TERMINATIONS: "Terminations (QPAY066)",
  VESTED_AMOUNTS_BY_AGE: "Get Vested Amounts by Age (PROF 130V)",
  YTD_WAGES_EXTRACT: "YTD Wages Extract",
  BREAKDOWN_REPORT: "Breakdown Report (QPAY066TA)",
  DEMOGRAOHIC_FREEZE: "Demographic Freeze"
} as const;

export const VIEW = "View";
