namespace Demoulas.ProfitSharing.Services.Internal.ServiceDto;

internal sealed record ProfitShareUpdateMember
{
    // ----  Who
    internal bool IsEmployee { get; init; }
    internal int Ssn { get; set; }
    internal int BadgeNumber { get; set; }
    internal string? Psn { get; set; }
    internal string? Name { get; set; }
    internal long EmployeeTypeId { get; set; }
    internal byte PayFrequencyId { get; set; }

    // ---- Overall financial status 
    internal decimal BeginningAmount { get; set; }
    internal decimal Distributions { get; set; }
    internal decimal Military { get; set; }
    internal decimal Xfer { get; set; }
    internal decimal Pxfer { get; set; }
    internal decimal EndingBalance { get; set; }

    // --- This years contributions/forfeitures
    internal decimal Contributions { get; set; }
    internal decimal IncomingForfeitures { get; set; }

    // earnings are divided into ETVA part and non ETVA part, but the "All" versions are the combined amounts.
    // the combined amounts are displayed on the PAY444 Report (summary of YE effect on a member)
    internal decimal AllEarnings { get; set; } // Earnings on both Non-ETVA and ETVA (PY-PROF-EARN)
    internal decimal AllSecondaryEarnings { get; set; } // // Earnings on both Non-ETVA and ETVA (PY-PROF-EARN2) 

    internal byte? ZeroContributionReasonId { get; set; }

    internal decimal Etva { get; set; } // PAYPROFIT.PY_PS_ETVA

    // This is the part of "All Earnings" which was generated by the ETVA portion
    internal decimal EtvaEarnings { get; set; } // PY-PROF-ETVA (a portion of Earnings which applies to ETVA)
    internal decimal SecondaryEtvaEarnings { get; set; } // PY_PROF_ETVA2 (portion of Secondary Earnings which applies to ETVA)
}
