import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3100/');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('hassam');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('hsherazi@demoulasmarketbasket.com');
  await page.getByRole('textbox', { name: 'Username' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('Demoulas!');
  await page.getByRole('textbox', { name: 'Password' }).press('Enter');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Username' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Username' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Username' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Username' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Username' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Username' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Username' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Username' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Username' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Username' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Username' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Username' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Username' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Username' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Username' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Username' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Username' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Username' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Username' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Username' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Username' }).fill('hsherazi');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Umt_0782');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('button', { name: 'INQUIRIES' }).click();
  await page.getByRole('link', { name: 'MASTER INQUIRY' }).click();
  await page.getByTestId('searchButton').click();
  await page.locator('#mui-component-select-startProfitMonth').click();
  await page.locator('#menu-startProfitMonth div').first().click();
  await page.locator('input[name="name"]').click();
  await page.locator('input[name="name"]').fill('evans');
  await page.getByTestId('searchButton').click();
  await page.getByRole('combobox', { name: 'roles' }).click();
  await page.getByRole('option', { name: 'IT-Operations' }).getByRole('checkbox').check();
  await page.locator('.MuiBackdrop-root').click();
  await page.getByTestId('searchButton').click();
  await page.getByRole('button', { name: 'next page' }).click();
  await page.getByRole('button', { name: 'next page' }).click();
  await page.getByRole('button', { name: 'next page' }).click();
  await page.getByRole('button', { name: 'next page' }).click();
  await page.getByRole('button', { name: 'next page' }).click();
  await page.getByRole('combobox', { name: 'roles' }).click();
  await page.getByRole('option', { name: 'Finance-Manager' }).getByRole('checkbox').check();
  await page.getByRole('option', { name: 'IT-Operations' }).getByRole('checkbox').uncheck();
  await page.getByRole('option', { name: 'Finance-Manager' }).getByRole('checkbox').check();
  await page.locator('.MuiBackdrop-root').click();
  await page.getByTestId('searchButton').click();
  await page.getByRole('button', { name: 'next page' }).click();
  await page.getByRole('link', { name: '701114' }).click();
  await page.getByTestId('searchButton').click();
  await page.getByLabel('rows per page').selectOption('200');
  await page.getByLabel('rows per page').selectOption('200');
  await page.getByLabel('rows per page').selectOption('50');
  await page.getByText('Page 1 of').click();
  await page.getByRole('button', { name: 'INQUIRIES' }).click();
  await page.getByRole('link', { name: 'MASTER INQUIRY' }).click();
  await page.getByTestId('searchButton').click();
  await page.getByRole('textbox', { name: 'YYYY' }).click();
  await page.getByRole('button', { name: 'Choose date, selected date is' }).click();
  await page.getByRole('radio', { name: '2024' }).click();
  await page.getByTestId('searchButton').click();
  await page.locator('input[name="badgeNumber"]').click();
  await page.locator('input[name="badgeNumber"]').fill('');
  await page.getByTestId('searchButton').click();
  await page.getByTestId('searchButton').click();
});