// <auto-generated />
using Demoulas.ProfitSharing.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Demoulas.ProfitSharing.Data.Migrations
{
    [DbContext(typeof(ProfitSharingDbContext))]
    [Migration("20240524145948_initialMigration")]
    partial class initialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("USING_NLS_COMP")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Demoulas.ProfitSharing.Data.Entities.Definition", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(24)
                        .HasColumnType("NVARCHAR2(24)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.HasKey("Key");

                    b.ToTable("Definition", (string)null);

                    b.HasData(
                        new
                        {
                            Key = "P",
                            Description = "Part Time"
                        },
                        new
                        {
                            Key = "H",
                            Description = "Full time(straight salary)"
                        },
                        new
                        {
                            Key = "G",
                            Description = "Full time accrued paid holidays"
                        },
                        new
                        {
                            Key = "F",
                            Description = "Full time 8 paid holidays "
                        },
                        new
                        {
                            Key = "PF",
                            Description = "Pay frequency (1=weekly, 2=monthly)"
                        });
                });

            modelBuilder.Entity("Demoulas.ProfitSharing.Data.Entities.Demographic", b =>
                {
                    b.Property<int>("BadgeNumber")
                        .HasPrecision(7)
                        .HasColumnType("NUMBER(7)")
                        .HasColumnName("DEM_BADGE");

                    b.Property<int>("DateOfBirth")
                        .HasPrecision(8)
                        .HasColumnType("NUMBER(8)")
                        .HasColumnName("PY_DOB");

                    b.Property<byte>("Department")
                        .HasPrecision(1)
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("PY_DP");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)")
                        .HasColumnName("PY_FUL");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("PY_FNAME");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR2(60)")
                        .HasColumnName("PY_NAM");

                    b.Property<int>("FullTimeDate")
                        .HasPrecision(8)
                        .HasColumnType("NUMBER(8)")
                        .HasColumnName("PY_FULL_DT");

                    b.Property<int>("HireDate")
                        .HasPrecision(8)
                        .HasColumnType("NUMBER(8)")
                        .HasColumnName("PY_HIRE_DT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("PY_LNAME");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(25)
                        .HasColumnType("NVARCHAR2(25)")
                        .HasColumnName("PY_MNAME");

                    b.Property<short>("PayClass")
                        .HasPrecision(3)
                        .HasColumnType("NUMBER(3)")
                        .HasColumnName("PY_CLA");

                    b.Property<char>("PayFrequency")
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("PY_FREQ");

                    b.Property<int>("ReHireDate")
                        .HasPrecision(8)
                        .HasColumnType("NUMBER(8)")
                        .HasColumnName("PY_REHIRE_DT");

                    b.Property<short>("StoreNumber")
                        .HasPrecision(3)
                        .HasColumnType("NUMBER(3)")
                        .HasColumnName("PY_STOR");

                    b.Property<int>("TerminationDate")
                        .HasPrecision(8)
                        .HasColumnType("NUMBER(8)")
                        .HasColumnName("PY_TERM_DT");

                    b.HasKey("BadgeNumber");

                    b.ToTable("DEMOGRAPHICS", (string)null);
                });

            modelBuilder.Entity("Demoulas.ProfitSharing.Data.Entities.Demographic", b =>
                {
                    b.OwnsOne("Demoulas.ProfitSharing.Data.Entities.Address", "Address", b1 =>
                        {
                            b1.Property<int>("DemographicBadgeNumber")
                                .HasColumnType("NUMBER(7)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(25)
                                .HasColumnType("NVARCHAR2(25)")
                                .HasColumnName("PY_CITY");

                            b1.Property<int>("PostalCode")
                                .HasPrecision(9)
                                .HasColumnType("NUMBER(9)")
                                .HasColumnName("PY_ZIP");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("NVARCHAR2(3)")
                                .HasColumnName("PY_STATE");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("NVARCHAR2(30)")
                                .HasColumnName("PY_ADD");

                            b1.Property<string>("Street2")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("NVARCHAR2(30)")
                                .HasColumnName("PY_ADD2");

                            b1.HasKey("DemographicBadgeNumber");

                            b1.ToTable("DEMOGRAPHICS");

                            b1.WithOwner()
                                .HasForeignKey("DemographicBadgeNumber");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
