// <auto-generated />
using Demoulas.ProfitSharing.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Demoulas.ProfitSharing.Data.Migrations
{
    [DbContext(typeof(ProfitSharingDbContext))]
    [Migration("20240522203832_initialMigration")]
    partial class initialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("USING_NLS_COMP")
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Demoulas.ProfitSharing.Data.Entities.Demographics", b =>
                {
                    b.Property<int>("BadgeNumber")
                        .HasPrecision(7)
                        .HasColumnType("NUMBER(7)")
                        .HasColumnName("DEM_BADGE");

                    b.HasKey("BadgeNumber");

                    b.ToTable("DEMOGRAPHICS", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
