// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Demoulas.ProfitSharing.Data.Migrations
{
    [DbContext(typeof(Demoulas.ProfitSharing.Data.Contexts.ProfitSharingDbContext))]
    [Migration("20250922123000_AddIsNavigableToNavigation")]
    partial class AddIsNavigableToNavigation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Intentionally left empty for committed migration designer consistency. The full model snapshot
            // is maintained in ProfitSharingDbContextModelSnapshot.cs
        }
    }
}
