// <auto-generated />
using Demoulas.ProfitSharing.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Demoulas.ProfitSharing.Data.Migrations
{
    [DbContext(typeof(ProfitSharingDbContext))]
    partial class ProfitSharingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("USING_NLS_COMP")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Demoulas.ProfitSharing.Data.Entities.Country", b =>
                {
                    b.Property<string>("ISO")
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)");

                    b.Property<short>("Id")
                        .HasPrecision(3)
                        .HasColumnType("NUMBER(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("TelephoneCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)");

                    b.HasKey("ISO");

                    b.ToTable("Country", (string)null);

                    b.HasData(
                        new
                        {
                            ISO = "AF",
                            Id = (short)1,
                            Name = "Afghanistan",
                            TelephoneCode = "+93"
                        },
                        new
                        {
                            ISO = "AL",
                            Id = (short)2,
                            Name = "Albania",
                            TelephoneCode = "+355"
                        },
                        new
                        {
                            ISO = "DZ",
                            Id = (short)3,
                            Name = "Algeria",
                            TelephoneCode = "+213"
                        },
                        new
                        {
                            ISO = "AD",
                            Id = (short)4,
                            Name = "Andorra",
                            TelephoneCode = "+376"
                        },
                        new
                        {
                            ISO = "AO",
                            Id = (short)5,
                            Name = "Angola",
                            TelephoneCode = "+244"
                        },
                        new
                        {
                            ISO = "AG",
                            Id = (short)6,
                            Name = "Antigua and Barbuda",
                            TelephoneCode = "+1-268"
                        },
                        new
                        {
                            ISO = "AR",
                            Id = (short)7,
                            Name = "Argentina",
                            TelephoneCode = "+54"
                        },
                        new
                        {
                            ISO = "AM",
                            Id = (short)8,
                            Name = "Armenia",
                            TelephoneCode = "+374"
                        },
                        new
                        {
                            ISO = "AU",
                            Id = (short)9,
                            Name = "Australia",
                            TelephoneCode = "+61"
                        },
                        new
                        {
                            ISO = "AT",
                            Id = (short)10,
                            Name = "Austria",
                            TelephoneCode = "+43"
                        },
                        new
                        {
                            ISO = "AZ",
                            Id = (short)11,
                            Name = "Azerbaijan",
                            TelephoneCode = "+994"
                        },
                        new
                        {
                            ISO = "BS",
                            Id = (short)12,
                            Name = "Bahamas",
                            TelephoneCode = "+1-242"
                        },
                        new
                        {
                            ISO = "BH",
                            Id = (short)13,
                            Name = "Bahrain",
                            TelephoneCode = "+973"
                        },
                        new
                        {
                            ISO = "BD",
                            Id = (short)14,
                            Name = "Bangladesh",
                            TelephoneCode = "+880"
                        },
                        new
                        {
                            ISO = "BB",
                            Id = (short)15,
                            Name = "Barbados",
                            TelephoneCode = "+1-246"
                        },
                        new
                        {
                            ISO = "BY",
                            Id = (short)16,
                            Name = "Belarus",
                            TelephoneCode = "+375"
                        },
                        new
                        {
                            ISO = "BE",
                            Id = (short)17,
                            Name = "Belgium",
                            TelephoneCode = "+32"
                        },
                        new
                        {
                            ISO = "BZ",
                            Id = (short)18,
                            Name = "Belize",
                            TelephoneCode = "+501"
                        },
                        new
                        {
                            ISO = "BJ",
                            Id = (short)19,
                            Name = "Benin",
                            TelephoneCode = "+229"
                        },
                        new
                        {
                            ISO = "BT",
                            Id = (short)20,
                            Name = "Bhutan",
                            TelephoneCode = "+975"
                        },
                        new
                        {
                            ISO = "BO",
                            Id = (short)21,
                            Name = "Bolivia",
                            TelephoneCode = "+591"
                        },
                        new
                        {
                            ISO = "BA",
                            Id = (short)22,
                            Name = "Bosnia and Herzegovina",
                            TelephoneCode = "+387"
                        },
                        new
                        {
                            ISO = "BW",
                            Id = (short)23,
                            Name = "Botswana",
                            TelephoneCode = "+267"
                        },
                        new
                        {
                            ISO = "BR",
                            Id = (short)24,
                            Name = "Brazil",
                            TelephoneCode = "+55"
                        },
                        new
                        {
                            ISO = "BN",
                            Id = (short)25,
                            Name = "Brunei",
                            TelephoneCode = "+673"
                        },
                        new
                        {
                            ISO = "BG",
                            Id = (short)26,
                            Name = "Bulgaria",
                            TelephoneCode = "+359"
                        },
                        new
                        {
                            ISO = "BF",
                            Id = (short)27,
                            Name = "Burkina Faso",
                            TelephoneCode = "+226"
                        },
                        new
                        {
                            ISO = "BI",
                            Id = (short)28,
                            Name = "Burundi",
                            TelephoneCode = "+257"
                        },
                        new
                        {
                            ISO = "CV",
                            Id = (short)29,
                            Name = "Cabo Verde",
                            TelephoneCode = "+238"
                        },
                        new
                        {
                            ISO = "KH",
                            Id = (short)30,
                            Name = "Cambodia",
                            TelephoneCode = "+855"
                        },
                        new
                        {
                            ISO = "CM",
                            Id = (short)31,
                            Name = "Cameroon",
                            TelephoneCode = "+237"
                        },
                        new
                        {
                            ISO = "CA",
                            Id = (short)32,
                            Name = "Canada",
                            TelephoneCode = "+1"
                        },
                        new
                        {
                            ISO = "CF",
                            Id = (short)33,
                            Name = "Central African Republic",
                            TelephoneCode = "+236"
                        },
                        new
                        {
                            ISO = "TD",
                            Id = (short)34,
                            Name = "Chad",
                            TelephoneCode = "+235"
                        },
                        new
                        {
                            ISO = "CL",
                            Id = (short)35,
                            Name = "Chile",
                            TelephoneCode = "+56"
                        },
                        new
                        {
                            ISO = "CN",
                            Id = (short)36,
                            Name = "China",
                            TelephoneCode = "+86"
                        },
                        new
                        {
                            ISO = "CO",
                            Id = (short)37,
                            Name = "Colombia",
                            TelephoneCode = "+57"
                        },
                        new
                        {
                            ISO = "KM",
                            Id = (short)38,
                            Name = "Comoros",
                            TelephoneCode = "+269"
                        },
                        new
                        {
                            ISO = "CG",
                            Id = (short)39,
                            Name = "Congo (Congo-Brazzaville)",
                            TelephoneCode = "+242"
                        },
                        new
                        {
                            ISO = "CR",
                            Id = (short)40,
                            Name = "Costa Rica",
                            TelephoneCode = "+506"
                        },
                        new
                        {
                            ISO = "HR",
                            Id = (short)41,
                            Name = "Croatia",
                            TelephoneCode = "+385"
                        },
                        new
                        {
                            ISO = "CU",
                            Id = (short)42,
                            Name = "Cuba",
                            TelephoneCode = "+53"
                        },
                        new
                        {
                            ISO = "CY",
                            Id = (short)43,
                            Name = "Cyprus",
                            TelephoneCode = "+357"
                        },
                        new
                        {
                            ISO = "CZ",
                            Id = (short)44,
                            Name = "Czechia (Czech Republic)",
                            TelephoneCode = "+420"
                        },
                        new
                        {
                            ISO = "CD",
                            Id = (short)45,
                            Name = "Democratic Republic of the Congo",
                            TelephoneCode = "+243"
                        },
                        new
                        {
                            ISO = "DK",
                            Id = (short)46,
                            Name = "Denmark",
                            TelephoneCode = "+45"
                        },
                        new
                        {
                            ISO = "DJ",
                            Id = (short)47,
                            Name = "Djibouti",
                            TelephoneCode = "+253"
                        },
                        new
                        {
                            ISO = "DM",
                            Id = (short)48,
                            Name = "Dominica",
                            TelephoneCode = "+1-767"
                        },
                        new
                        {
                            ISO = "DO",
                            Id = (short)49,
                            Name = "Dominican Republic",
                            TelephoneCode = "+1-809"
                        },
                        new
                        {
                            ISO = "EC",
                            Id = (short)50,
                            Name = "Ecuador",
                            TelephoneCode = "+593"
                        },
                        new
                        {
                            ISO = "EG",
                            Id = (short)51,
                            Name = "Egypt",
                            TelephoneCode = "+20"
                        },
                        new
                        {
                            ISO = "SV",
                            Id = (short)52,
                            Name = "El Salvador",
                            TelephoneCode = "+503"
                        },
                        new
                        {
                            ISO = "GQ",
                            Id = (short)53,
                            Name = "Equatorial Guinea",
                            TelephoneCode = "+240"
                        },
                        new
                        {
                            ISO = "ER",
                            Id = (short)54,
                            Name = "Eritrea",
                            TelephoneCode = "+291"
                        },
                        new
                        {
                            ISO = "EE",
                            Id = (short)55,
                            Name = "Estonia",
                            TelephoneCode = "+372"
                        },
                        new
                        {
                            ISO = "SZ",
                            Id = (short)56,
                            Name = "Eswatini (Swaziland)",
                            TelephoneCode = "+268"
                        },
                        new
                        {
                            ISO = "ET",
                            Id = (short)57,
                            Name = "Ethiopia",
                            TelephoneCode = "+251"
                        },
                        new
                        {
                            ISO = "FJ",
                            Id = (short)58,
                            Name = "Fiji",
                            TelephoneCode = "+679"
                        },
                        new
                        {
                            ISO = "FI",
                            Id = (short)59,
                            Name = "Finland",
                            TelephoneCode = "+358"
                        },
                        new
                        {
                            ISO = "FR",
                            Id = (short)60,
                            Name = "France",
                            TelephoneCode = "+33"
                        },
                        new
                        {
                            ISO = "GA",
                            Id = (short)61,
                            Name = "Gabon",
                            TelephoneCode = "+241"
                        },
                        new
                        {
                            ISO = "GM",
                            Id = (short)62,
                            Name = "Gambia",
                            TelephoneCode = "+220"
                        },
                        new
                        {
                            ISO = "GE",
                            Id = (short)63,
                            Name = "Georgia",
                            TelephoneCode = "+995"
                        },
                        new
                        {
                            ISO = "DE",
                            Id = (short)64,
                            Name = "Germany",
                            TelephoneCode = "+49"
                        },
                        new
                        {
                            ISO = "GH",
                            Id = (short)65,
                            Name = "Ghana",
                            TelephoneCode = "+233"
                        },
                        new
                        {
                            ISO = "GR",
                            Id = (short)66,
                            Name = "Greece",
                            TelephoneCode = "+30"
                        },
                        new
                        {
                            ISO = "GD",
                            Id = (short)67,
                            Name = "Grenada",
                            TelephoneCode = "+1-473"
                        },
                        new
                        {
                            ISO = "GT",
                            Id = (short)68,
                            Name = "Guatemala",
                            TelephoneCode = "+502"
                        },
                        new
                        {
                            ISO = "GN",
                            Id = (short)69,
                            Name = "Guinea",
                            TelephoneCode = "+224"
                        },
                        new
                        {
                            ISO = "GW",
                            Id = (short)70,
                            Name = "Guinea-Bissau",
                            TelephoneCode = "+245"
                        },
                        new
                        {
                            ISO = "GY",
                            Id = (short)71,
                            Name = "Guyana",
                            TelephoneCode = "+592"
                        },
                        new
                        {
                            ISO = "HT",
                            Id = (short)72,
                            Name = "Haiti",
                            TelephoneCode = "+509"
                        },
                        new
                        {
                            ISO = "HN",
                            Id = (short)73,
                            Name = "Honduras",
                            TelephoneCode = "+504"
                        },
                        new
                        {
                            ISO = "HU",
                            Id = (short)74,
                            Name = "Hungary",
                            TelephoneCode = "+36"
                        },
                        new
                        {
                            ISO = "IS",
                            Id = (short)75,
                            Name = "Iceland",
                            TelephoneCode = "+354"
                        },
                        new
                        {
                            ISO = "IN",
                            Id = (short)76,
                            Name = "India",
                            TelephoneCode = "+91"
                        },
                        new
                        {
                            ISO = "ID",
                            Id = (short)77,
                            Name = "Indonesia",
                            TelephoneCode = "+62"
                        },
                        new
                        {
                            ISO = "IR",
                            Id = (short)78,
                            Name = "Iran",
                            TelephoneCode = "+98"
                        },
                        new
                        {
                            ISO = "IQ",
                            Id = (short)79,
                            Name = "Iraq",
                            TelephoneCode = "+964"
                        },
                        new
                        {
                            ISO = "IE",
                            Id = (short)80,
                            Name = "Ireland",
                            TelephoneCode = "+353"
                        },
                        new
                        {
                            ISO = "IL",
                            Id = (short)81,
                            Name = "Israel",
                            TelephoneCode = "+972"
                        },
                        new
                        {
                            ISO = "IT",
                            Id = (short)82,
                            Name = "Italy",
                            TelephoneCode = "+39"
                        },
                        new
                        {
                            ISO = "JM",
                            Id = (short)83,
                            Name = "Jamaica",
                            TelephoneCode = "+1-876"
                        },
                        new
                        {
                            ISO = "JP",
                            Id = (short)84,
                            Name = "Japan",
                            TelephoneCode = "+81"
                        },
                        new
                        {
                            ISO = "JO",
                            Id = (short)85,
                            Name = "Jordan",
                            TelephoneCode = "+962"
                        },
                        new
                        {
                            ISO = "KZ",
                            Id = (short)86,
                            Name = "Kazakhstan",
                            TelephoneCode = "+7"
                        },
                        new
                        {
                            ISO = "KE",
                            Id = (short)87,
                            Name = "Kenya",
                            TelephoneCode = "+254"
                        },
                        new
                        {
                            ISO = "KI",
                            Id = (short)88,
                            Name = "Kiribati",
                            TelephoneCode = "+686"
                        },
                        new
                        {
                            ISO = "KW",
                            Id = (short)89,
                            Name = "Kuwait",
                            TelephoneCode = "+965"
                        },
                        new
                        {
                            ISO = "KG",
                            Id = (short)90,
                            Name = "Kyrgyzstan",
                            TelephoneCode = "+996"
                        },
                        new
                        {
                            ISO = "LA",
                            Id = (short)91,
                            Name = "Laos",
                            TelephoneCode = "+856"
                        },
                        new
                        {
                            ISO = "LV",
                            Id = (short)92,
                            Name = "Latvia",
                            TelephoneCode = "+371"
                        },
                        new
                        {
                            ISO = "LB",
                            Id = (short)93,
                            Name = "Lebanon",
                            TelephoneCode = "+961"
                        },
                        new
                        {
                            ISO = "LS",
                            Id = (short)94,
                            Name = "Lesotho",
                            TelephoneCode = "+266"
                        },
                        new
                        {
                            ISO = "LR",
                            Id = (short)95,
                            Name = "Liberia",
                            TelephoneCode = "+231"
                        },
                        new
                        {
                            ISO = "LY",
                            Id = (short)96,
                            Name = "Libya",
                            TelephoneCode = "+218"
                        },
                        new
                        {
                            ISO = "LI",
                            Id = (short)97,
                            Name = "Liechtenstein",
                            TelephoneCode = "+423"
                        },
                        new
                        {
                            ISO = "LT",
                            Id = (short)98,
                            Name = "Lithuania",
                            TelephoneCode = "+370"
                        },
                        new
                        {
                            ISO = "LU",
                            Id = (short)99,
                            Name = "Luxembourg",
                            TelephoneCode = "+352"
                        },
                        new
                        {
                            ISO = "MG",
                            Id = (short)100,
                            Name = "Madagascar",
                            TelephoneCode = "+261"
                        },
                        new
                        {
                            ISO = "MW",
                            Id = (short)101,
                            Name = "Malawi",
                            TelephoneCode = "+265"
                        },
                        new
                        {
                            ISO = "MY",
                            Id = (short)102,
                            Name = "Malaysia",
                            TelephoneCode = "+60"
                        },
                        new
                        {
                            ISO = "MV",
                            Id = (short)103,
                            Name = "Maldives",
                            TelephoneCode = "+960"
                        },
                        new
                        {
                            ISO = "ML",
                            Id = (short)104,
                            Name = "Mali",
                            TelephoneCode = "+223"
                        },
                        new
                        {
                            ISO = "MT",
                            Id = (short)105,
                            Name = "Malta",
                            TelephoneCode = "+356"
                        },
                        new
                        {
                            ISO = "MH",
                            Id = (short)106,
                            Name = "Marshall Islands",
                            TelephoneCode = "+692"
                        },
                        new
                        {
                            ISO = "MR",
                            Id = (short)107,
                            Name = "Mauritania",
                            TelephoneCode = "+222"
                        },
                        new
                        {
                            ISO = "MU",
                            Id = (short)108,
                            Name = "Mauritius",
                            TelephoneCode = "+230"
                        },
                        new
                        {
                            ISO = "MX",
                            Id = (short)109,
                            Name = "Mexico",
                            TelephoneCode = "+52"
                        },
                        new
                        {
                            ISO = "FM",
                            Id = (short)110,
                            Name = "Micronesia",
                            TelephoneCode = "+691"
                        },
                        new
                        {
                            ISO = "MD",
                            Id = (short)111,
                            Name = "Moldova",
                            TelephoneCode = "+373"
                        },
                        new
                        {
                            ISO = "MC",
                            Id = (short)112,
                            Name = "Monaco",
                            TelephoneCode = "+377"
                        },
                        new
                        {
                            ISO = "MN",
                            Id = (short)113,
                            Name = "Mongolia",
                            TelephoneCode = "+976"
                        },
                        new
                        {
                            ISO = "ME",
                            Id = (short)114,
                            Name = "Montenegro",
                            TelephoneCode = "+382"
                        },
                        new
                        {
                            ISO = "MA",
                            Id = (short)115,
                            Name = "Morocco",
                            TelephoneCode = "+212"
                        },
                        new
                        {
                            ISO = "MZ",
                            Id = (short)116,
                            Name = "Mozambique",
                            TelephoneCode = "+258"
                        },
                        new
                        {
                            ISO = "MM",
                            Id = (short)117,
                            Name = "Myanmar (Burma)",
                            TelephoneCode = "+95"
                        },
                        new
                        {
                            ISO = "NA",
                            Id = (short)118,
                            Name = "Namibia",
                            TelephoneCode = "+264"
                        },
                        new
                        {
                            ISO = "NR",
                            Id = (short)119,
                            Name = "Nauru",
                            TelephoneCode = "+674"
                        },
                        new
                        {
                            ISO = "NP",
                            Id = (short)120,
                            Name = "Nepal",
                            TelephoneCode = "+977"
                        },
                        new
                        {
                            ISO = "NL",
                            Id = (short)121,
                            Name = "Netherlands",
                            TelephoneCode = "+31"
                        },
                        new
                        {
                            ISO = "NZ",
                            Id = (short)122,
                            Name = "New Zealand",
                            TelephoneCode = "+64"
                        },
                        new
                        {
                            ISO = "NI",
                            Id = (short)123,
                            Name = "Nicaragua",
                            TelephoneCode = "+505"
                        },
                        new
                        {
                            ISO = "NE",
                            Id = (short)124,
                            Name = "Niger",
                            TelephoneCode = "+227"
                        },
                        new
                        {
                            ISO = "NG",
                            Id = (short)125,
                            Name = "Nigeria",
                            TelephoneCode = "+234"
                        },
                        new
                        {
                            ISO = "KP",
                            Id = (short)126,
                            Name = "North Korea",
                            TelephoneCode = "+850"
                        },
                        new
                        {
                            ISO = "MK",
                            Id = (short)127,
                            Name = "North Macedonia",
                            TelephoneCode = "+389"
                        },
                        new
                        {
                            ISO = "NO",
                            Id = (short)128,
                            Name = "Norway",
                            TelephoneCode = "+47"
                        },
                        new
                        {
                            ISO = "OM",
                            Id = (short)129,
                            Name = "Oman",
                            TelephoneCode = "+968"
                        },
                        new
                        {
                            ISO = "PK",
                            Id = (short)130,
                            Name = "Pakistan",
                            TelephoneCode = "+92"
                        },
                        new
                        {
                            ISO = "PW",
                            Id = (short)131,
                            Name = "Palau",
                            TelephoneCode = "+680"
                        },
                        new
                        {
                            ISO = "PS",
                            Id = (short)132,
                            Name = "Palestine State",
                            TelephoneCode = "+970"
                        },
                        new
                        {
                            ISO = "PA",
                            Id = (short)133,
                            Name = "Panama",
                            TelephoneCode = "+507"
                        },
                        new
                        {
                            ISO = "PG",
                            Id = (short)134,
                            Name = "Papua New Guinea",
                            TelephoneCode = "+675"
                        },
                        new
                        {
                            ISO = "PY",
                            Id = (short)135,
                            Name = "Paraguay",
                            TelephoneCode = "+595"
                        },
                        new
                        {
                            ISO = "PE",
                            Id = (short)136,
                            Name = "Peru",
                            TelephoneCode = "+51"
                        },
                        new
                        {
                            ISO = "PH",
                            Id = (short)137,
                            Name = "Philippines",
                            TelephoneCode = "+63"
                        },
                        new
                        {
                            ISO = "PL",
                            Id = (short)138,
                            Name = "Poland",
                            TelephoneCode = "+48"
                        },
                        new
                        {
                            ISO = "PT",
                            Id = (short)139,
                            Name = "Portugal",
                            TelephoneCode = "+351"
                        },
                        new
                        {
                            ISO = "QA",
                            Id = (short)140,
                            Name = "Qatar",
                            TelephoneCode = "+974"
                        },
                        new
                        {
                            ISO = "RO",
                            Id = (short)141,
                            Name = "Romania",
                            TelephoneCode = "+40"
                        },
                        new
                        {
                            ISO = "RU",
                            Id = (short)142,
                            Name = "Russia",
                            TelephoneCode = "+7"
                        },
                        new
                        {
                            ISO = "RW",
                            Id = (short)143,
                            Name = "Rwanda",
                            TelephoneCode = "+250"
                        },
                        new
                        {
                            ISO = "KN",
                            Id = (short)144,
                            Name = "Saint Kitts and Nevis",
                            TelephoneCode = "+1-869"
                        },
                        new
                        {
                            ISO = "LC",
                            Id = (short)145,
                            Name = "Saint Lucia",
                            TelephoneCode = "+1-758"
                        },
                        new
                        {
                            ISO = "VC",
                            Id = (short)146,
                            Name = "Saint Vincent and the Grenadines",
                            TelephoneCode = "+1-784"
                        },
                        new
                        {
                            ISO = "WS",
                            Id = (short)147,
                            Name = "Samoa",
                            TelephoneCode = "+685"
                        },
                        new
                        {
                            ISO = "SM",
                            Id = (short)148,
                            Name = "San Marino",
                            TelephoneCode = "+378"
                        },
                        new
                        {
                            ISO = "ST",
                            Id = (short)149,
                            Name = "Sao Tome and Principe",
                            TelephoneCode = "+239"
                        },
                        new
                        {
                            ISO = "SA",
                            Id = (short)150,
                            Name = "Saudi Arabia",
                            TelephoneCode = "+966"
                        },
                        new
                        {
                            ISO = "SN",
                            Id = (short)151,
                            Name = "Senegal",
                            TelephoneCode = "+221"
                        },
                        new
                        {
                            ISO = "RS",
                            Id = (short)152,
                            Name = "Serbia",
                            TelephoneCode = "+381"
                        },
                        new
                        {
                            ISO = "SC",
                            Id = (short)153,
                            Name = "Seychelles",
                            TelephoneCode = "+248"
                        },
                        new
                        {
                            ISO = "SL",
                            Id = (short)154,
                            Name = "Sierra Leone",
                            TelephoneCode = "+232"
                        },
                        new
                        {
                            ISO = "SG",
                            Id = (short)155,
                            Name = "Singapore",
                            TelephoneCode = "+65"
                        },
                        new
                        {
                            ISO = "SK",
                            Id = (short)156,
                            Name = "Slovakia",
                            TelephoneCode = "+421"
                        },
                        new
                        {
                            ISO = "SI",
                            Id = (short)157,
                            Name = "Slovenia",
                            TelephoneCode = "+386"
                        },
                        new
                        {
                            ISO = "SB",
                            Id = (short)158,
                            Name = "Solomon Islands",
                            TelephoneCode = "+677"
                        },
                        new
                        {
                            ISO = "SO",
                            Id = (short)159,
                            Name = "Somalia",
                            TelephoneCode = "+252"
                        },
                        new
                        {
                            ISO = "ZA",
                            Id = (short)160,
                            Name = "South Africa",
                            TelephoneCode = "+27"
                        },
                        new
                        {
                            ISO = "KR",
                            Id = (short)161,
                            Name = "South Korea",
                            TelephoneCode = "+82"
                        },
                        new
                        {
                            ISO = "SS",
                            Id = (short)162,
                            Name = "South Sudan",
                            TelephoneCode = "+211"
                        },
                        new
                        {
                            ISO = "ES",
                            Id = (short)163,
                            Name = "Spain",
                            TelephoneCode = "+34"
                        },
                        new
                        {
                            ISO = "LK",
                            Id = (short)164,
                            Name = "Sri Lanka",
                            TelephoneCode = "+94"
                        },
                        new
                        {
                            ISO = "SD",
                            Id = (short)165,
                            Name = "Sudan",
                            TelephoneCode = "+249"
                        },
                        new
                        {
                            ISO = "SR",
                            Id = (short)166,
                            Name = "Suriname",
                            TelephoneCode = "+597"
                        },
                        new
                        {
                            ISO = "SE",
                            Id = (short)167,
                            Name = "Sweden",
                            TelephoneCode = "+46"
                        },
                        new
                        {
                            ISO = "CH",
                            Id = (short)168,
                            Name = "Switzerland",
                            TelephoneCode = "+41"
                        },
                        new
                        {
                            ISO = "SY",
                            Id = (short)169,
                            Name = "Syria",
                            TelephoneCode = "+963"
                        },
                        new
                        {
                            ISO = "TW",
                            Id = (short)170,
                            Name = "Taiwan",
                            TelephoneCode = "+886"
                        },
                        new
                        {
                            ISO = "TJ",
                            Id = (short)171,
                            Name = "Tajikistan",
                            TelephoneCode = "+992"
                        },
                        new
                        {
                            ISO = "TZ",
                            Id = (short)172,
                            Name = "Tanzania",
                            TelephoneCode = "+255"
                        },
                        new
                        {
                            ISO = "TH",
                            Id = (short)173,
                            Name = "Thailand",
                            TelephoneCode = "+66"
                        },
                        new
                        {
                            ISO = "TL",
                            Id = (short)174,
                            Name = "Timor-Leste",
                            TelephoneCode = "+670"
                        },
                        new
                        {
                            ISO = "TG",
                            Id = (short)175,
                            Name = "Togo",
                            TelephoneCode = "+228"
                        },
                        new
                        {
                            ISO = "TO",
                            Id = (short)176,
                            Name = "Tonga",
                            TelephoneCode = "+676"
                        },
                        new
                        {
                            ISO = "TT",
                            Id = (short)177,
                            Name = "Trinidad and Tobago",
                            TelephoneCode = "+1-868"
                        },
                        new
                        {
                            ISO = "TN",
                            Id = (short)178,
                            Name = "Tunisia",
                            TelephoneCode = "+216"
                        },
                        new
                        {
                            ISO = "TR",
                            Id = (short)179,
                            Name = "Turkey",
                            TelephoneCode = "+90"
                        },
                        new
                        {
                            ISO = "TM",
                            Id = (short)180,
                            Name = "Turkmenistan",
                            TelephoneCode = "+993"
                        },
                        new
                        {
                            ISO = "TV",
                            Id = (short)181,
                            Name = "Tuvalu",
                            TelephoneCode = "+688"
                        },
                        new
                        {
                            ISO = "UG",
                            Id = (short)182,
                            Name = "Uganda",
                            TelephoneCode = "+256"
                        },
                        new
                        {
                            ISO = "UA",
                            Id = (short)183,
                            Name = "Ukraine",
                            TelephoneCode = "+380"
                        },
                        new
                        {
                            ISO = "AE",
                            Id = (short)184,
                            Name = "United Arab Emirates",
                            TelephoneCode = "+971"
                        },
                        new
                        {
                            ISO = "GB",
                            Id = (short)185,
                            Name = "United Kingdom",
                            TelephoneCode = "+44"
                        },
                        new
                        {
                            ISO = "US",
                            Id = (short)186,
                            Name = "United States of America",
                            TelephoneCode = "+1"
                        },
                        new
                        {
                            ISO = "UY",
                            Id = (short)187,
                            Name = "Uruguay",
                            TelephoneCode = "+598"
                        },
                        new
                        {
                            ISO = "UZ",
                            Id = (short)188,
                            Name = "Uzbekistan",
                            TelephoneCode = "+998"
                        },
                        new
                        {
                            ISO = "VU",
                            Id = (short)189,
                            Name = "Vanuatu",
                            TelephoneCode = "+678"
                        },
                        new
                        {
                            ISO = "VE",
                            Id = (short)190,
                            Name = "Venezuela",
                            TelephoneCode = "+58"
                        },
                        new
                        {
                            ISO = "VN",
                            Id = (short)191,
                            Name = "Vietnam",
                            TelephoneCode = "+84"
                        },
                        new
                        {
                            ISO = "YE",
                            Id = (short)192,
                            Name = "Yemen",
                            TelephoneCode = "+967"
                        },
                        new
                        {
                            ISO = "ZM",
                            Id = (short)193,
                            Name = "Zambia",
                            TelephoneCode = "+260"
                        },
                        new
                        {
                            ISO = "ZW",
                            Id = (short)194,
                            Name = "Zimbabwe",
                            TelephoneCode = "+263"
                        });
                });

            modelBuilder.Entity("Demoulas.ProfitSharing.Data.Entities.Demographic", b =>
                {
                    b.Property<long>("SSN")
                        .HasPrecision(9)
                        .HasColumnType("NUMBER(9)")
                        .HasColumnName("DEM_SSN");

                    b.Property<int>("BadgeNumber")
                        .HasPrecision(7)
                        .HasColumnType("NUMBER(7)")
                        .HasColumnName("DEM_BADGE");

                    b.Property<int>("DateOfBirth")
                        .HasPrecision(8)
                        .HasColumnType("NUMBER(8)")
                        .HasColumnName("PY_DOB")
                        .HasComment("DateOfBirth");

                    b.Property<byte>("DepartmentId")
                        .HasPrecision(1)
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("PY_DP")
                        .HasComment("Department");

                    b.Property<string>("EmploymentTypeId")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)")
                        .HasColumnName("PY_FUL")
                        .HasComment("EmploymentType");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("PY_FNAME")
                        .HasComment("FirstName");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR2(60)")
                        .HasColumnName("PY_NAM")
                        .HasComment("FullName");

                    b.Property<int>("FullTimeDate")
                        .HasPrecision(8)
                        .HasColumnType("NUMBER(8)")
                        .HasColumnName("PY_FULL_DT")
                        .HasComment("FullTimeDate");

                    b.Property<string>("GenderId")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("PY_GENDER")
                        .HasComment("Gender");

                    b.Property<int>("HireDate")
                        .HasPrecision(8)
                        .HasColumnType("NUMBER(8)")
                        .HasColumnName("PY_HIRE_DT")
                        .HasComment("HireDate");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("PY_LNAME")
                        .HasComment("LastName");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(25)
                        .HasColumnType("NVARCHAR2(25)")
                        .HasColumnName("PY_MNAME")
                        .HasComment("MiddleName");

                    b.Property<long>("OracleHcmId")
                        .HasPrecision(15)
                        .HasColumnType("NUMBER(15)")
                        .HasColumnName("PY_ASSIGN_ID");

                    b.Property<byte>("PayClassificationId")
                        .HasPrecision(2)
                        .HasColumnType("NUMBER(2)")
                        .HasColumnName("PY_CLA")
                        .HasComment("PayClassification");

                    b.Property<byte>("PayFrequencyId")
                        .HasMaxLength(1)
                        .HasColumnType("NUMBER(3)")
                        .HasColumnName("PY_FREQ")
                        .HasComment("PayFrequency");

                    b.Property<int>("ReHireDate")
                        .HasPrecision(8)
                        .HasColumnType("NUMBER(8)")
                        .HasColumnName("PY_REHIRE_DT")
                        .HasComment("ReHireDate");

                    b.Property<short>("StoreNumber")
                        .HasPrecision(3)
                        .HasColumnType("NUMBER(3)")
                        .HasColumnName("PY_STOR")
                        .HasComment("StoreNumber");

                    b.Property<string>("TerminationCodeId")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("PY_TERM")
                        .HasComment("TerminationCode");

                    b.Property<int?>("TerminationDate")
                        .HasPrecision(8)
                        .HasColumnType("NUMBER(8)")
                        .HasColumnName("PY_TERM_DT")
                        .HasComment("TerminationDate");

                    b.HasKey("SSN");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmploymentTypeId");

                    b.HasIndex("GenderId");

                    b.HasIndex("PayClassificationId");

                    b.HasIndex("PayFrequencyId");

                    b.HasIndex("TerminationCodeId");

                    b.ToTable("DEMOGRAPHICS", (string)null);
                });

            modelBuilder.Entity("Demoulas.ProfitSharing.Data.Entities.Department", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("NUMBER(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)");

                    b.HasKey("Id");

                    b.ToTable("Department", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            Name = "Grocery"
                        },
                        new
                        {
                            Id = (byte)2,
                            Name = "Meat"
                        },
                        new
                        {
                            Id = (byte)3,
                            Name = "Produce"
                        },
                        new
                        {
                            Id = (byte)4,
                            Name = "Deli"
                        },
                        new
                        {
                            Id = (byte)5,
                            Name = "Dairy"
                        },
                        new
                        {
                            Id = (byte)6,
                            Name = "Beer and Wine"
                        },
                        new
                        {
                            Id = (byte)7,
                            Name = "Bakery"
                        });
                });

            modelBuilder.Entity("Demoulas.ProfitSharing.Data.Entities.EmploymentType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)");

                    b.HasKey("Id");

                    b.ToTable("EmploymentType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "P",
                            Name = "PartTime"
                        },
                        new
                        {
                            Id = "H",
                            Name = "FullTimeStraightSalary"
                        },
                        new
                        {
                            Id = "G",
                            Name = "FullTimeAccruedPaidHolidays"
                        },
                        new
                        {
                            Id = "F",
                            Name = "FullTimeEightPaidHolidays"
                        });
                });

            modelBuilder.Entity("Demoulas.ProfitSharing.Data.Entities.Gender", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)");

                    b.HasKey("Id");

                    b.ToTable("Gender", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "M",
                            Name = "Male"
                        },
                        new
                        {
                            Id = "F",
                            Name = "Female"
                        },
                        new
                        {
                            Id = "X",
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("Demoulas.ProfitSharing.Data.Entities.PayClassification", b =>
                {
                    b.Property<byte>("Id")
                        .HasPrecision(2)
                        .HasColumnType("NUMBER(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasComment("Pay Classification");

                    b.HasKey("Id");

                    b.ToTable("PayClassification", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            Name = "MANAGER"
                        },
                        new
                        {
                            Id = (byte)2,
                            Name = "ASSISTANT MANAGER"
                        },
                        new
                        {
                            Id = (byte)10,
                            Name = "FRONT END MANAGER"
                        },
                        new
                        {
                            Id = (byte)11,
                            Name = "ASSISTANT HEAD CASHIER"
                        },
                        new
                        {
                            Id = (byte)13,
                            Name = "CASHIERS - AM"
                        },
                        new
                        {
                            Id = (byte)14,
                            Name = "CASHIERS - PM"
                        },
                        new
                        {
                            Id = (byte)15,
                            Name = "CASHIERS 14-15"
                        },
                        new
                        {
                            Id = (byte)16,
                            Name = "SACKERS - AM"
                        },
                        new
                        {
                            Id = (byte)17,
                            Name = "SACKERS - PM"
                        },
                        new
                        {
                            Id = (byte)18,
                            Name = "SACKERS 14-15"
                        },
                        new
                        {
                            Id = (byte)19,
                            Name = "STORE MAINTENANCE"
                        },
                        new
                        {
                            Id = (byte)20,
                            Name = "OFFICE MANAGER"
                        },
                        new
                        {
                            Id = (byte)22,
                            Name = "COURTESY BOOTH - AM"
                        },
                        new
                        {
                            Id = (byte)23,
                            Name = "COURTESY BOOTH - PM"
                        },
                        new
                        {
                            Id = (byte)24,
                            Name = "POS - FULL TIME"
                        },
                        new
                        {
                            Id = (byte)25,
                            Name = "CLERK -FULL TIME AP"
                        },
                        new
                        {
                            Id = (byte)26,
                            Name = "CLERKS - FULL TIME AR"
                        },
                        new
                        {
                            Id = (byte)27,
                            Name = "CLERKS - FULL TIME GROC"
                        },
                        new
                        {
                            Id = (byte)28,
                            Name = "CLERKS - FULL TIME PERISHABLES"
                        },
                        new
                        {
                            Id = (byte)29,
                            Name = "CLERKS - FULL TIME WAREHOUSE"
                        },
                        new
                        {
                            Id = (byte)30,
                            Name = "MERCHANDISER"
                        },
                        new
                        {
                            Id = (byte)31,
                            Name = "GROCERY MANAGER"
                        },
                        new
                        {
                            Id = (byte)32,
                            Name = "ENDS - PART TIME"
                        },
                        new
                        {
                            Id = (byte)33,
                            Name = "FIRST MEAT CUTTER"
                        },
                        new
                        {
                            Id = (byte)35,
                            Name = "NOT USED"
                        },
                        new
                        {
                            Id = (byte)37,
                            Name = "CAFE PART TIME"
                        },
                        new
                        {
                            Id = (byte)38,
                            Name = "RECEIVER"
                        },
                        new
                        {
                            Id = (byte)39,
                            Name = "NOT USED"
                        },
                        new
                        {
                            Id = (byte)40,
                            Name = "MEAT CUTTERS"
                        },
                        new
                        {
                            Id = (byte)41,
                            Name = "APPR MEAT CUTTERS"
                        },
                        new
                        {
                            Id = (byte)42,
                            Name = "MEAT CUTTER PART TIME"
                        },
                        new
                        {
                            Id = (byte)43,
                            Name = "TRAINEE MEAT CUTTER"
                        },
                        new
                        {
                            Id = (byte)44,
                            Name = "PART TIME SUBSHOP"
                        },
                        new
                        {
                            Id = (byte)45,
                            Name = "ASST SUB SHOP MANAGER"
                        },
                        new
                        {
                            Id = (byte)46,
                            Name = "SERVICE CASE - FULL TIME"
                        },
                        new
                        {
                            Id = (byte)47,
                            Name = "WRAPPERS - FULL TIME"
                        },
                        new
                        {
                            Id = (byte)48,
                            Name = "WRAPPERS - PART TIME AM"
                        },
                        new
                        {
                            Id = (byte)49,
                            Name = "WRAPPERS - PART TIME PM"
                        },
                        new
                        {
                            Id = (byte)50,
                            Name = "HEAD CLERK"
                        },
                        new
                        {
                            Id = (byte)51,
                            Name = "SUB SHOP MANAGER"
                        },
                        new
                        {
                            Id = (byte)52,
                            Name = "CLERKS - FULL TIME AM"
                        },
                        new
                        {
                            Id = (byte)53,
                            Name = "CLERKS - PART TIME AM"
                        },
                        new
                        {
                            Id = (byte)54,
                            Name = "CLERKS - PART TIME PM"
                        },
                        new
                        {
                            Id = (byte)55,
                            Name = "POS - PART TIME"
                        },
                        new
                        {
                            Id = (byte)56,
                            Name = "MARKETS KITCHEN - ASST MGR"
                        },
                        new
                        {
                            Id = (byte)57,
                            Name = "MARKETS KITCHEN FT"
                        },
                        new
                        {
                            Id = (byte)58,
                            Name = "MARKETS KITCHEN PT"
                        },
                        new
                        {
                            Id = (byte)59,
                            Name = "KITCHEN MANAGER"
                        },
                        new
                        {
                            Id = (byte)60,
                            Name = "NOT USED"
                        },
                        new
                        {
                            Id = (byte)61,
                            Name = "PT BAKERY MERCHANDISER"
                        },
                        new
                        {
                            Id = (byte)62,
                            Name = "FT CAKE & CREAMS"
                        },
                        new
                        {
                            Id = (byte)63,
                            Name = "CAKE & CREAM PT"
                        },
                        new
                        {
                            Id = (byte)64,
                            Name = "OVER WORKER PT"
                        },
                        new
                        {
                            Id = (byte)65,
                            Name = "BENCH WORKER PT"
                        },
                        new
                        {
                            Id = (byte)66,
                            Name = "FORK LIFT OPR (REC) AM"
                        },
                        new
                        {
                            Id = (byte)67,
                            Name = "FORK LIFT OPR (REC) PM"
                        },
                        new
                        {
                            Id = (byte)68,
                            Name = "FORK LIFT OPR (SHIP) AM"
                        },
                        new
                        {
                            Id = (byte)69,
                            Name = "FORK LIFT OPR (SHIP) PM"
                        },
                        new
                        {
                            Id = (byte)70,
                            Name = "FORK LIFT OPR (MISC.) AM"
                        },
                        new
                        {
                            Id = (byte)71,
                            Name = "FORK LIFT OPR (MISC.) PM"
                        },
                        new
                        {
                            Id = (byte)72,
                            Name = "LOADER - AM"
                        },
                        new
                        {
                            Id = (byte)73,
                            Name = "LOADER - PM"
                        },
                        new
                        {
                            Id = (byte)74,
                            Name = "WHSE MAINTENANCE - AM"
                        },
                        new
                        {
                            Id = (byte)75,
                            Name = "WHSE MAINTENANCE - PM"
                        },
                        new
                        {
                            Id = (byte)77,
                            Name = "SELECTOR PART TIME - AM"
                        },
                        new
                        {
                            Id = (byte)78,
                            Name = "SELECTOR PART TIME - PM"
                        },
                        new
                        {
                            Id = (byte)79,
                            Name = "SELECTOR FULL TIME - AM"
                        },
                        new
                        {
                            Id = (byte)80,
                            Name = "TEMP FULLTIME"
                        },
                        new
                        {
                            Id = (byte)81,
                            Name = "SELECTOR FULL TIME - PM"
                        },
                        new
                        {
                            Id = (byte)82,
                            Name = "INSPECTOR"
                        },
                        new
                        {
                            Id = (byte)83,
                            Name = "GENERAL WAREHOUSE - AM"
                        },
                        new
                        {
                            Id = (byte)84,
                            Name = "GENERAL WAREHOUSE - PM"
                        },
                        new
                        {
                            Id = (byte)85,
                            Name = "DRIVER - TRAILER"
                        },
                        new
                        {
                            Id = (byte)86,
                            Name = "DRIVER - STRAIGHT"
                        },
                        new
                        {
                            Id = (byte)87,
                            Name = "MECHANIC"
                        },
                        new
                        {
                            Id = (byte)88,
                            Name = "GARAGE - PM"
                        },
                        new
                        {
                            Id = (byte)89,
                            Name = "FACILITY OPERATIONS"
                        },
                        new
                        {
                            Id = (byte)90,
                            Name = "COMPUTER OPERATIONS"
                        },
                        new
                        {
                            Id = (byte)91,
                            Name = "SIGN SHOP"
                        },
                        new
                        {
                            Id = (byte)92,
                            Name = "INVENTORY"
                        },
                        new
                        {
                            Id = (byte)93,
                            Name = "PROGRAMMING"
                        },
                        new
                        {
                            Id = (byte)94,
                            Name = "HELP DESK"
                        },
                        new
                        {
                            Id = (byte)95,
                            Name = "DEFUNCT"
                        },
                        new
                        {
                            Id = (byte)96,
                            Name = "TECHNICAL SUPPORT"
                        },
                        new
                        {
                            Id = (byte)98,
                            Name = "TRAINING"
                        });
                });

            modelBuilder.Entity("Demoulas.ProfitSharing.Data.Entities.PayFrequency", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("NUMBER(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)");

                    b.HasKey("Id");

                    b.ToTable("PayFrequency", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            Name = "Weekly"
                        },
                        new
                        {
                            Id = (byte)2,
                            Name = "Monthly"
                        });
                });

            modelBuilder.Entity("Demoulas.ProfitSharing.Data.Entities.TerminationCode", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(1)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)");

                    b.HasKey("Id");

                    b.ToTable("TerminationCode", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "A",
                            Description = "Left On Own"
                        },
                        new
                        {
                            Id = "B",
                            Description = "Personal Or Family Reason"
                        },
                        new
                        {
                            Id = "C",
                            Description = "Could Not Work Available Hours"
                        },
                        new
                        {
                            Id = "D",
                            Description = "Stealing"
                        },
                        new
                        {
                            Id = "E",
                            Description = "Not Following Company Policy"
                        },
                        new
                        {
                            Id = "F",
                            Description = "FMLA Expired"
                        },
                        new
                        {
                            Id = "G",
                            Description = "Terminated Private"
                        },
                        new
                        {
                            Id = "H",
                            Description = "Job Abandonment"
                        },
                        new
                        {
                            Id = "I",
                            Description = "Health Reasons Non-FMLA"
                        },
                        new
                        {
                            Id = "J",
                            Description = "Layoff No Work"
                        });
                });

            modelBuilder.Entity("Demoulas.ProfitSharing.Data.Entities.Demographic", b =>
                {
                    b.HasOne("Demoulas.ProfitSharing.Data.Entities.Department", "Department")
                        .WithMany("Demographics")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Demoulas.ProfitSharing.Data.Entities.EmploymentType", "EmploymentType")
                        .WithMany("Demographics")
                        .HasForeignKey("EmploymentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Demoulas.ProfitSharing.Data.Entities.Gender", "Gender")
                        .WithMany("Demographics")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Demoulas.ProfitSharing.Data.Entities.PayClassification", "PayClassification")
                        .WithMany("Employees")
                        .HasForeignKey("PayClassificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Demoulas.ProfitSharing.Data.Entities.PayFrequency", "PayFrequency")
                        .WithMany("Demographics")
                        .HasForeignKey("PayFrequencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Demoulas.ProfitSharing.Data.Entities.TerminationCode", "TerminationCode")
                        .WithMany("Demographics")
                        .HasForeignKey("TerminationCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Demoulas.ProfitSharing.Data.Entities.Address", "Address", b1 =>
                        {
                            b1.Property<long>("DemographicSSN")
                                .HasColumnType("NUMBER(9)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(25)
                                .HasColumnType("NVARCHAR2(25)")
                                .HasColumnName("PY_CITY")
                                .HasComment("City");

                            b1.Property<string>("CountryISO")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(2)
                                .HasColumnType("NVARCHAR2(2)")
                                .HasDefaultValue("US")
                                .HasColumnName("CountryISO");

                            b1.Property<int>("PostalCode")
                                .HasPrecision(9)
                                .HasColumnType("NUMBER(9)")
                                .HasColumnName("PY_ZIP")
                                .HasComment("Postal Code");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("NVARCHAR2(3)")
                                .HasColumnName("PY_STATE")
                                .HasComment("State");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("NVARCHAR2(30)")
                                .HasColumnName("PY_ADD")
                                .HasComment("Street");

                            b1.Property<string>("Street2")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("NVARCHAR2(30)")
                                .HasColumnName("PY_ADD2")
                                .HasComment("Street2");

                            b1.HasKey("DemographicSSN");

                            b1.HasIndex("CountryISO");

                            b1.ToTable("DEMOGRAPHICS");

                            b1.HasOne("Demoulas.ProfitSharing.Data.Entities.Country", null)
                                .WithMany()
                                .HasForeignKey("CountryISO")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("DemographicSSN");
                        });

                    b.OwnsOne("Demoulas.ProfitSharing.Data.Entities.ContactInfo", "ContactInfo", b1 =>
                        {
                            b1.Property<long>("DemographicSSN")
                                .HasColumnType("NUMBER(9)");

                            b1.Property<string>("EmailAddress")
                                .HasMaxLength(50)
                                .HasColumnType("NVARCHAR2(50)")
                                .HasColumnName("EmailAddress");

                            b1.Property<string>("MobileNumber")
                                .HasMaxLength(15)
                                .HasColumnType("NVARCHAR2(15)")
                                .HasColumnName("MobileNumber");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("NVARCHAR2(15)")
                                .HasColumnName("PY_EMP_TELNO")
                                .HasComment("PhoneNumber");

                            b1.HasKey("DemographicSSN");

                            b1.ToTable("DEMOGRAPHICS");

                            b1.WithOwner()
                                .HasForeignKey("DemographicSSN");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("ContactInfo")
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("EmploymentType");

                    b.Navigation("Gender");

                    b.Navigation("PayClassification");

                    b.Navigation("PayFrequency");

                    b.Navigation("TerminationCode");
                });

            modelBuilder.Entity("Demoulas.ProfitSharing.Data.Entities.Department", b =>
                {
                    b.Navigation("Demographics");
                });

            modelBuilder.Entity("Demoulas.ProfitSharing.Data.Entities.EmploymentType", b =>
                {
                    b.Navigation("Demographics");
                });

            modelBuilder.Entity("Demoulas.ProfitSharing.Data.Entities.Gender", b =>
                {
                    b.Navigation("Demographics");
                });

            modelBuilder.Entity("Demoulas.ProfitSharing.Data.Entities.PayClassification", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Demoulas.ProfitSharing.Data.Entities.PayFrequency", b =>
                {
                    b.Navigation("Demographics");
                });

            modelBuilder.Entity("Demoulas.ProfitSharing.Data.Entities.TerminationCode", b =>
                {
                    b.Navigation("Demographics");
                });
#pragma warning restore 612, 618
        }
    }
}
