-- Check beneficiary allocation transactions in database
-- Code 5 = OutgoingXferBeneficiary
-- Code 6 = IncomingQdroBeneficiary

SELECT 
    PROFIT_CODE_ID,
    COUNT(*) AS TRANSACTION_COUNT,
    SUM(CONTRIBUTION) AS TOTAL_CONTRIBUTION,
    SUM(FORFEITURE) AS TOTAL_FORFEITURE,
    SUM(CASE 
        WHEN PROFIT_CODE_ID = 5 THEN -FORFEITURE
        WHEN PROFIT_CODE_ID = 6 THEN CONTRIBUTION
        ELSE 0
    END) AS CALCULATED_BEN_ALLOC
FROM PROFITSHARE.PROFIT_DETAIL
WHERE PROFIT_CODE_ID IN (5, 6)
  AND SUBSTR(PROFIT_YEAR, 1, 4) = '2025'
GROUP BY PROFIT_CODE_ID;

-- Also check per-SSN breakdown for code 5/6
SELECT 
    PR_DET_S_SEC_NUMBER AS SSN,
    PROFIT_CODE_ID,
    COUNT(*) AS TRANSACTION_COUNT,
    SUM(CONTRIBUTION) AS TOTAL_CONTRIBUTION,
    SUM(FORFEITURE) AS TOTAL_FORFEITURE,
    SUM(CASE 
        WHEN PROFIT_CODE_ID = 5 THEN -FORFEITURE
        WHEN PROFIT_CODE_ID = 6 THEN CONTRIBUTION
        ELSE 0
    END) AS CALCULATED_BEN_ALLOC
FROM PROFITSHARE.PROFIT_DETAIL
WHERE PROFIT_CODE_ID IN (5, 6)
  AND SUBSTR(PROFIT_YEAR, 1, 4) = '2025'
GROUP BY PR_DET_S_SEC_NUMBER, PROFIT_CODE_ID
ORDER BY PR_DET_S_SEC_NUMBER, PROFIT_CODE_ID;
