WITH SSN_QUERY AS (
    SELECT '700000552' AS SSN FROM dual
)
SELECT 
    (SELECT GROSSAMT FROM MTPR3.PSCALCVIEW WHERE SSN = ssn_query.SSN) AS MTPR3_GROSSAMT,
    (SELECT GROSSAMT FROM TEAM_PROFIT_SHARING2.PSCALCVIEW WHERE SSN = ssn_query.SSN) AS TEAMPS_GROSSAMT,
    (SELECT ZEROC_CHECK FROM MTPR3.PSCALCVIEW WHERE SSN = ssn_query.SSN) AS MTPR3_AGE65_CHECKVESTING,
    (SELECT ZEROC_CHECK FROM TEAM_PROFIT_SHARING2.PSCALCVIEW WHERE SSN = ssn_query.SSN) AS TEAMPS_AGE65_CHECKVESTING,
    (SELECT VESTPCT FROM MTPR3.PSCALCVIEW WHERE SSN = ssn_query.SSN) AS MTPR3_VESTPCT,
    (SELECT VESTPCT FROM TEAM_PROFIT_SHARING2.PSCALCVIEW WHERE SSN = ssn_query.SSN) AS TEAMPS_VESTPCT,
    (SELECT ((TOTAL_BALANCE + DISTRIBUTIONS - ETVA) * VESTPCT) + ETVA - DISTRIBUTIONS 
        FROM MTPR3.PSCALCVIEW WHERE SSN = ssn_query.SSN) AS MTPR3_VESTED_BALANCE,
    (SELECT ((TOTAL_BALANCE + DISTRIBUTIONS - ETVA) * VESTPCT) + ETVA - DISTRIBUTIONS 
        FROM TEAM_PROFIT_SHARING2.PSCALCVIEW WHERE SSN = ssn_query.SSN) AS TEAMPS_VESTED_BALANCE
FROM 
    SSN_QUERY;
