using Demoulas.ProfitSharing.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Demoulas.ProfitSharing.Data.Contexts.EntityMapping;
public sealed class CountryMap : IEntityTypeConfiguration<Country>
{
    public void Configure(EntityTypeBuilder<Country> builder)
    {
        _ = builder.HasKey(c => c.Iso);
        _ = builder.ToTable("COUNTRY");

        _ = builder.Property(c => c.Iso).IsRequired().HasMaxLength(2);
        _ = builder.Property(c => c.Id).IsRequired().HasPrecision(3).HasColumnName("ID");
        _ = builder.Property(c => c.Name).IsRequired().HasMaxLength(100).HasColumnName("NAME");
        _ = builder.Property(c => c.TelephoneCode).IsRequired().HasMaxLength(10).HasColumnName("TELEPHONE_CODE");

        _ = builder.HasData(GetPredefinedCountries());
    }

    private List<Country> GetPredefinedCountries()
    {
        return
        [
            new Country { Id = 1, Name = "Afghanistan", Iso = "AF", TelephoneCode = "+93" },
            new Country { Id = 2, Name = "Albania", Iso = "AL", TelephoneCode = "+355" },
            new Country { Id = 3, Name = "Algeria", Iso = "DZ", TelephoneCode = "+213" },
            new Country { Id = 4, Name = "Andorra", Iso = "AD", TelephoneCode = "+376" },
            new Country { Id = 5, Name = "Angola", Iso = "AO", TelephoneCode = "+244" },
            new Country { Id = 6, Name = "Antigua and Barbuda", Iso = "AG", TelephoneCode = "+1-268" },
            new Country { Id = 7, Name = "Argentina", Iso = "AR", TelephoneCode = "+54" },
            new Country { Id = 8, Name = "Armenia", Iso = "AM", TelephoneCode = "+374" },
            new Country { Id = 9, Name = "Australia", Iso = "AU", TelephoneCode = "+61" },
            new Country { Id = 10, Name = "Austria", Iso = "AT", TelephoneCode = "+43" },
            new Country { Id = 11, Name = "Azerbaijan", Iso = "AZ", TelephoneCode = "+994" },
            new Country { Id = 12, Name = "Bahamas", Iso = "BS", TelephoneCode = "+1-242" },
            new Country { Id = 13, Name = "Bahrain", Iso = "BH", TelephoneCode = "+973" },
            new Country { Id = 14, Name = "Bangladesh", Iso = "BD", TelephoneCode = "+880" },
            new Country { Id = 15, Name = "Barbados", Iso = "BB", TelephoneCode = "+1-246" },
            new Country { Id = 16, Name = "Belarus", Iso = "BY", TelephoneCode = "+375" },
            new Country { Id = 17, Name = "Belgium", Iso = "BE", TelephoneCode = "+32" },
            new Country { Id = 18, Name = "Belize", Iso = "BZ", TelephoneCode = "+501" },
            new Country { Id = 19, Name = "Benin", Iso = "BJ", TelephoneCode = "+229" },
            new Country { Id = 20, Name = "Bhutan", Iso = "BT", TelephoneCode = "+975" },
            new Country { Id = 21, Name = "Bolivia", Iso = "BO", TelephoneCode = "+591" },
            new Country { Id = 22, Name = "Bosnia and Herzegovina", Iso = "BA", TelephoneCode = "+387" },
            new Country { Id = 23, Name = "Botswana", Iso = "BW", TelephoneCode = "+267" },
            new Country { Id = 24, Name = "Brazil", Iso = "BR", TelephoneCode = "+55" },
            new Country { Id = 25, Name = "Brunei", Iso = "BN", TelephoneCode = "+673" },
            new Country { Id = 26, Name = "Bulgaria", Iso = "BG", TelephoneCode = "+359" },
            new Country { Id = 27, Name = "Burkina Faso", Iso = "BF", TelephoneCode = "+226" },
            new Country { Id = 28, Name = "Burundi", Iso = "BI", TelephoneCode = "+257" },
            new Country { Id = 29, Name = "Cabo Verde", Iso = "CV", TelephoneCode = "+238" },
            new Country { Id = 30, Name = "Cambodia", Iso = "KH", TelephoneCode = "+855" },
            new Country { Id = 31, Name = "Cameroon", Iso = "CM", TelephoneCode = "+237" },
            new Country { Id = 32, Name = "Canada", Iso = "CA", TelephoneCode = "+1" },
            new Country { Id = 33, Name = "Central African Republic", Iso = "CF", TelephoneCode = "+236" },
            new Country { Id = 34, Name = "Chad", Iso = "TD", TelephoneCode = "+235" },
            new Country { Id = 35, Name = "Chile", Iso = "CL", TelephoneCode = "+56" },
            new Country { Id = 36, Name = "China", Iso = "CN", TelephoneCode = "+86" },
            new Country { Id = 37, Name = "Colombia", Iso = "CO", TelephoneCode = "+57" },
            new Country { Id = 38, Name = "Comoros", Iso = "KM", TelephoneCode = "+269" },
            new Country { Id = 39, Name = "Congo (Congo-Brazzaville)", Iso = "CG", TelephoneCode = "+242" },
            new Country { Id = 40, Name = "Costa Rica", Iso = "CR", TelephoneCode = "+506" },
            new Country { Id = 41, Name = "Croatia", Iso = "HR", TelephoneCode = "+385" },
            new Country { Id = 42, Name = "Cuba", Iso = "CU", TelephoneCode = "+53" },
            new Country { Id = 43, Name = "Cyprus", Iso = "CY", TelephoneCode = "+357" },
            new Country { Id = 44, Name = "Czechia (Czech Republic)", Iso = "CZ", TelephoneCode = "+420" },
            new Country { Id = 45, Name = "Democratic Republic of the Congo", Iso = "CD", TelephoneCode = "+243" },
            new Country { Id = 46, Name = "Denmark", Iso = "DK", TelephoneCode = "+45" },
            new Country { Id = 47, Name = "Djibouti", Iso = "DJ", TelephoneCode = "+253" },
            new Country { Id = 48, Name = "Dominica", Iso = "DM", TelephoneCode = "+1-767" },
            new Country { Id = 49, Name = "Dominican Republic", Iso = "DO", TelephoneCode = "+1-809" },
            new Country { Id = 50, Name = "Ecuador", Iso = "EC", TelephoneCode = "+593" },
            new Country { Id = 51, Name = "Egypt", Iso = "EG", TelephoneCode = "+20" },
            new Country { Id = 52, Name = "El Salvador", Iso = "SV", TelephoneCode = "+503" },
            new Country { Id = 53, Name = "Equatorial Guinea", Iso = "GQ", TelephoneCode = "+240" },
            new Country { Id = 54, Name = "Eritrea", Iso = "ER", TelephoneCode = "+291" },
            new Country { Id = 55, Name = "Estonia", Iso = "EE", TelephoneCode = "+372" },
            new Country { Id = 56, Name = "Eswatini (Swaziland)", Iso = "SZ", TelephoneCode = "+268" },
            new Country { Id = 57, Name = "Ethiopia", Iso = "ET", TelephoneCode = "+251" },
            new Country { Id = 58, Name = "Fiji", Iso = "FJ", TelephoneCode = "+679" },
            new Country { Id = 59, Name = "Finland", Iso = "FI", TelephoneCode = "+358" },
            new Country { Id = 60, Name = "France", Iso = "FR", TelephoneCode = "+33" },
            new Country { Id = 61, Name = "Gabon", Iso = "GA", TelephoneCode = "+241" },
            new Country { Id = 62, Name = "Gambia", Iso = "GM", TelephoneCode = "+220" },
            new Country { Id = 63, Name = "Georgia", Iso = "GE", TelephoneCode = "+995" },
            new Country { Id = 64, Name = "Germany", Iso = "DE", TelephoneCode = "+49" },
            new Country { Id = 65, Name = "Ghana", Iso = "GH", TelephoneCode = "+233" },
            new Country { Id = 66, Name = "Greece", Iso = "GR", TelephoneCode = "+30" },
            new Country { Id = 67, Name = "Grenada", Iso = "GD", TelephoneCode = "+1-473" },
            new Country { Id = 68, Name = "Guatemala", Iso = "GT", TelephoneCode = "+502" },
            new Country { Id = 69, Name = "Guinea", Iso = "GN", TelephoneCode = "+224" },
            new Country { Id = 70, Name = "Guinea-Bissau", Iso = "GW", TelephoneCode = "+245" },
            new Country { Id = 71, Name = "Guyana", Iso = "GY", TelephoneCode = "+592" },
            new Country { Id = 72, Name = "Haiti", Iso = "HT", TelephoneCode = "+509" },
            new Country { Id = 73, Name = "Honduras", Iso = "HN", TelephoneCode = "+504" },
            new Country { Id = 74, Name = "Hungary", Iso = "HU", TelephoneCode = "+36" },
            new Country { Id = 75, Name = "Iceland", Iso = "IS", TelephoneCode = "+354" },
            new Country { Id = 76, Name = "India", Iso = "IN", TelephoneCode = "+91" },
            new Country { Id = 77, Name = "Indonesia", Iso = "ID", TelephoneCode = "+62" },
            new Country { Id = 78, Name = "Iran", Iso = "IR", TelephoneCode = "+98" },
            new Country { Id = 79, Name = "Iraq", Iso = "IQ", TelephoneCode = "+964" },
            new Country { Id = 80, Name = "Ireland", Iso = "IE", TelephoneCode = "+353" },
            new Country { Id = 81, Name = "Israel", Iso = "IL", TelephoneCode = "+972" },
            new Country { Id = 82, Name = "Italy", Iso = "IT", TelephoneCode = "+39" },
            new Country { Id = 83, Name = "Jamaica", Iso = "JM", TelephoneCode = "+1-876" },
            new Country { Id = 84, Name = "Japan", Iso = "JP", TelephoneCode = "+81" },
            new Country { Id = 85, Name = "Jordan", Iso = "JO", TelephoneCode = "+962" },
            new Country { Id = 86, Name = "Kazakhstan", Iso = "KZ", TelephoneCode = "+7" },
            new Country { Id = 87, Name = "Kenya", Iso = "KE", TelephoneCode = "+254" },
            new Country { Id = 88, Name = "Kiribati", Iso = "KI", TelephoneCode = "+686" },
            new Country { Id = 89, Name = "Kuwait", Iso = "KW", TelephoneCode = "+965" },
            new Country { Id = 90, Name = "Kyrgyzstan", Iso = "KG", TelephoneCode = "+996" },
            new Country { Id = 91, Name = "Laos", Iso = "LA", TelephoneCode = "+856" },
            new Country { Id = 92, Name = "Latvia", Iso = "LV", TelephoneCode = "+371" },
            new Country { Id = 93, Name = "Lebanon", Iso = "LB", TelephoneCode = "+961" },
            new Country { Id = 94, Name = "Lesotho", Iso = "LS", TelephoneCode = "+266" },
            new Country { Id = 95, Name = "Liberia", Iso = "LR", TelephoneCode = "+231" },
            new Country { Id = 96, Name = "Libya", Iso = "LY", TelephoneCode = "+218" },
            new Country { Id = 97, Name = "Liechtenstein", Iso = "LI", TelephoneCode = "+423" },
            new Country { Id = 98, Name = "Lithuania", Iso = "LT", TelephoneCode = "+370" },
            new Country { Id = 99, Name = "Luxembourg", Iso = "LU", TelephoneCode = "+352" },
            new Country { Id = 100, Name = "Madagascar", Iso = "MG", TelephoneCode = "+261" },
            new Country { Id = 101, Name = "Malawi", Iso = "MW", TelephoneCode = "+265" },
            new Country { Id = 102, Name = "Malaysia", Iso = "MY", TelephoneCode = "+60" },
            new Country { Id = 103, Name = "Maldives", Iso = "MV", TelephoneCode = "+960" },
            new Country { Id = 104, Name = "Mali", Iso = "ML", TelephoneCode = "+223" },
            new Country { Id = 105, Name = "Malta", Iso = "MT", TelephoneCode = "+356" },
            new Country { Id = 106, Name = "Marshall Islands", Iso = "MH", TelephoneCode = "+692" },
            new Country { Id = 107, Name = "Mauritania", Iso = "MR", TelephoneCode = "+222" },
            new Country { Id = 108, Name = "Mauritius", Iso = "MU", TelephoneCode = "+230" },
            new Country { Id = 109, Name = "Mexico", Iso = "MX", TelephoneCode = "+52" },
            new Country { Id = 110, Name = "Micronesia", Iso = "FM", TelephoneCode = "+691" },
            new Country { Id = 111, Name = "Moldova", Iso = "MD", TelephoneCode = "+373" },
            new Country { Id = 112, Name = "Monaco", Iso = "MC", TelephoneCode = "+377" },
            new Country { Id = 113, Name = "Mongolia", Iso = "MN", TelephoneCode = "+976" },
            new Country { Id = 114, Name = "Montenegro", Iso = "ME", TelephoneCode = "+382" },
            new Country { Id = 115, Name = "Morocco", Iso = "MA", TelephoneCode = "+212" },
            new Country { Id = 116, Name = "Mozambique", Iso = "MZ", TelephoneCode = "+258" },
            new Country { Id = 117, Name = "Myanmar (Burma)", Iso = "MM", TelephoneCode = "+95" },
            new Country { Id = 118, Name = "Namibia", Iso = "NA", TelephoneCode = "+264" },
            new Country { Id = 119, Name = "Nauru", Iso = "NR", TelephoneCode = "+674" },
            new Country { Id = 120, Name = "Nepal", Iso = "NP", TelephoneCode = "+977" },
            new Country { Id = 121, Name = "Netherlands", Iso = "NL", TelephoneCode = "+31" },
            new Country { Id = 122, Name = "New Zealand", Iso = "NZ", TelephoneCode = "+64" },
            new Country { Id = 123, Name = "Nicaragua", Iso = "NI", TelephoneCode = "+505" },
            new Country { Id = 124, Name = "Niger", Iso = "NE", TelephoneCode = "+227" },
            new Country { Id = 125, Name = "Nigeria", Iso = "NG", TelephoneCode = "+234" },
            new Country { Id = 126, Name = "North Korea", Iso = "KP", TelephoneCode = "+850" },
            new Country { Id = 127, Name = "North Macedonia", Iso = "MK", TelephoneCode = "+389" },
            new Country { Id = 128, Name = "Norway", Iso = "NO", TelephoneCode = "+47" },
            new Country { Id = 129, Name = "Oman", Iso = "OM", TelephoneCode = "+968" },
            new Country { Id = 130, Name = "Pakistan", Iso = "PK", TelephoneCode = "+92" },
            new Country { Id = 131, Name = "Palau", Iso = "PW", TelephoneCode = "+680" },
            new Country { Id = 132, Name = "Palestine State", Iso = "PS", TelephoneCode = "+970" },
            new Country { Id = 133, Name = "Panama", Iso = "PA", TelephoneCode = "+507" },
            new Country { Id = 134, Name = "Papua New Guinea", Iso = "PG", TelephoneCode = "+675" },
            new Country { Id = 135, Name = "Paraguay", Iso = "PY", TelephoneCode = "+595" },
            new Country { Id = 136, Name = "Peru", Iso = "PE", TelephoneCode = "+51" },
            new Country { Id = 137, Name = "Philippines", Iso = "PH", TelephoneCode = "+63" },
            new Country { Id = 138, Name = "Poland", Iso = "PL", TelephoneCode = "+48" },
            new Country { Id = 139, Name = "Portugal", Iso = "PT", TelephoneCode = "+351" },
            new Country { Id = 140, Name = "Qatar", Iso = "QA", TelephoneCode = "+974" },
            new Country { Id = 141, Name = "Romania", Iso = "RO", TelephoneCode = "+40" },
            new Country { Id = 142, Name = "Russia", Iso = "RU", TelephoneCode = "+7" },
            new Country { Id = 143, Name = "Rwanda", Iso = "RW", TelephoneCode = "+250" },
            new Country { Id = 144, Name = "Saint Kitts and Nevis", Iso = "KN", TelephoneCode = "+1-869" },
            new Country { Id = 145, Name = "Saint Lucia", Iso = "LC", TelephoneCode = "+1-758" },
            new Country { Id = 146, Name = "Saint Vincent and the Grenadines", Iso = "VC", TelephoneCode = "+1-784" },
            new Country { Id = 147, Name = "Samoa", Iso = "WS", TelephoneCode = "+685" },
            new Country { Id = 148, Name = "San Marino", Iso = "SM", TelephoneCode = "+378" },
            new Country { Id = 149, Name = "Sao Tome and Principe", Iso = "ST", TelephoneCode = "+239" },
            new Country { Id = 150, Name = "Saudi Arabia", Iso = "SA", TelephoneCode = "+966" },
            new Country { Id = 151, Name = "Senegal", Iso = "SN", TelephoneCode = "+221" },
            new Country { Id = 152, Name = "Serbia", Iso = "RS", TelephoneCode = "+381" },
            new Country { Id = 153, Name = "Seychelles", Iso = "SC", TelephoneCode = "+248" },
            new Country { Id = 154, Name = "Sierra Leone", Iso = "SL", TelephoneCode = "+232" },
            new Country { Id = 155, Name = "Singapore", Iso = "SG", TelephoneCode = "+65" },
            new Country { Id = 156, Name = "Slovakia", Iso = "SK", TelephoneCode = "+421" },
            new Country { Id = 157, Name = "Slovenia", Iso = "SI", TelephoneCode = "+386" },
            new Country { Id = 158, Name = "Solomon Islands", Iso = "SB", TelephoneCode = "+677" },
            new Country { Id = 159, Name = "Somalia", Iso = "SO", TelephoneCode = "+252" },
            new Country { Id = 160, Name = "South Africa", Iso = "ZA", TelephoneCode = "+27" },
            new Country { Id = 161, Name = "South Korea", Iso = "KR", TelephoneCode = "+82" },
            new Country { Id = 162, Name = "South Sudan", Iso = "SS", TelephoneCode = "+211" },
            new Country { Id = 163, Name = "Spain", Iso = "ES", TelephoneCode = "+34" },
            new Country { Id = 164, Name = "Sri Lanka", Iso = "LK", TelephoneCode = "+94" },
            new Country { Id = 165, Name = "Sudan", Iso = "SD", TelephoneCode = "+249" },
            new Country { Id = 166, Name = "Suriname", Iso = "SR", TelephoneCode = "+597" },
            new Country { Id = 167, Name = "Sweden", Iso = "SE", TelephoneCode = "+46" },
            new Country { Id = 168, Name = "Switzerland", Iso = "CH", TelephoneCode = "+41" },
            new Country { Id = 169, Name = "Syria", Iso = "SY", TelephoneCode = "+963" },
            new Country { Id = 170, Name = "Taiwan", Iso = "TW", TelephoneCode = "+886" },
            new Country { Id = 171, Name = "Tajikistan", Iso = "TJ", TelephoneCode = "+992" },
            new Country { Id = 172, Name = "Tanzania", Iso = "TZ", TelephoneCode = "+255" },
            new Country { Id = 173, Name = "Thailand", Iso = "TH", TelephoneCode = "+66" },
            new Country { Id = 174, Name = "Timor-Leste", Iso = "TL", TelephoneCode = "+670" },
            new Country { Id = 175, Name = "Togo", Iso = "TG", TelephoneCode = "+228" },
            new Country { Id = 176, Name = "Tonga", Iso = "TO", TelephoneCode = "+676" },
            new Country { Id = 177, Name = "Trinidad and Tobago", Iso = "TT", TelephoneCode = "+1-868" },
            new Country { Id = 178, Name = "Tunisia", Iso = "TN", TelephoneCode = "+216" },
            new Country { Id = 179, Name = "Turkey", Iso = "TR", TelephoneCode = "+90" },
            new Country { Id = 180, Name = "Turkmenistan", Iso = "TM", TelephoneCode = "+993" },
            new Country { Id = 181, Name = "Tuvalu", Iso = "TV", TelephoneCode = "+688" },
            new Country { Id = 182, Name = "Uganda", Iso = "UG", TelephoneCode = "+256" },
            new Country { Id = 183, Name = "Ukraine", Iso = "UA", TelephoneCode = "+380" },
            new Country { Id = 184, Name = "United Arab Emirates", Iso = "AE", TelephoneCode = "+971" },
            new Country { Id = 185, Name = "United Kingdom", Iso = "GB", TelephoneCode = "+44" },
            new Country { Id = 186, Name = "United States of America", Iso = "US", TelephoneCode = "+1" },
            new Country { Id = 187, Name = "Uruguay", Iso = "UY", TelephoneCode = "+598" },
            new Country { Id = 188, Name = "Uzbekistan", Iso = "UZ", TelephoneCode = "+998" },
            new Country { Id = 189, Name = "Vanuatu", Iso = "VU", TelephoneCode = "+678" },
            new Country { Id = 190, Name = "Venezuela", Iso = "VE", TelephoneCode = "+58" },
            new Country { Id = 191, Name = "Vietnam", Iso = "VN", TelephoneCode = "+84" },
            new Country { Id = 192, Name = "Yemen", Iso = "YE", TelephoneCode = "+967" },
            new Country { Id = 193, Name = "Zambia", Iso = "ZM", TelephoneCode = "+260" },
            new Country { Id = 194, Name = "Zimbabwe", Iso = "ZW", TelephoneCode = "+263" }
        ];
    }
}
