using Demoulas.ProfitSharing.Data.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;

namespace Demoulas.ProfitSharing.Data.Contexts.EntityMapping;
public sealed class CountryMap : IEntityTypeConfiguration<Country>
{
    public void Configure(EntityTypeBuilder<Country> builder)
    {
        _ = builder.HasKey(c => c.ISO);
        _ = builder.ToTable("Country");

        _ = builder.Property(c => c.ISO).IsRequired().HasMaxLength(2);
        _ = builder.Property(c => c.Id).IsRequired().HasPrecision(3).HasColumnName("ID");
        _ = builder.Property(c => c.Name).IsRequired().HasMaxLength(100).HasColumnName("NAME");
        _ = builder.Property(c => c.TelephoneCode).IsRequired().HasMaxLength(10).HasColumnName("TELEPHONE_CODE");

        _ = builder.HasData(GetPredefinedCountries());
    }

    private List<Country> GetPredefinedCountries()
    {
        return
        [
            new Country { Id = 1, Name = "Afghanistan", ISO = "AF", TelephoneCode = "+93" },
            new Country { Id = 2, Name = "Albania", ISO = "AL", TelephoneCode = "+355" },
            new Country { Id = 3, Name = "Algeria", ISO = "DZ", TelephoneCode = "+213" },
            new Country { Id = 4, Name = "Andorra", ISO = "AD", TelephoneCode = "+376" },
            new Country { Id = 5, Name = "Angola", ISO = "AO", TelephoneCode = "+244" },
            new Country { Id = 6, Name = "Antigua and Barbuda", ISO = "AG", TelephoneCode = "+1-268" },
            new Country { Id = 7, Name = "Argentina", ISO = "AR", TelephoneCode = "+54" },
            new Country { Id = 8, Name = "Armenia", ISO = "AM", TelephoneCode = "+374" },
            new Country { Id = 9, Name = "Australia", ISO = "AU", TelephoneCode = "+61" },
            new Country { Id = 10, Name = "Austria", ISO = "AT", TelephoneCode = "+43" },
            new Country { Id = 11, Name = "Azerbaijan", ISO = "AZ", TelephoneCode = "+994" },
            new Country { Id = 12, Name = "Bahamas", ISO = "BS", TelephoneCode = "+1-242" },
            new Country { Id = 13, Name = "Bahrain", ISO = "BH", TelephoneCode = "+973" },
            new Country { Id = 14, Name = "Bangladesh", ISO = "BD", TelephoneCode = "+880" },
            new Country { Id = 15, Name = "Barbados", ISO = "BB", TelephoneCode = "+1-246" },
            new Country { Id = 16, Name = "Belarus", ISO = "BY", TelephoneCode = "+375" },
            new Country { Id = 17, Name = "Belgium", ISO = "BE", TelephoneCode = "+32" },
            new Country { Id = 18, Name = "Belize", ISO = "BZ", TelephoneCode = "+501" },
            new Country { Id = 19, Name = "Benin", ISO = "BJ", TelephoneCode = "+229" },
            new Country { Id = 20, Name = "Bhutan", ISO = "BT", TelephoneCode = "+975" },
            new Country { Id = 21, Name = "Bolivia", ISO = "BO", TelephoneCode = "+591" },
            new Country { Id = 22, Name = "Bosnia and Herzegovina", ISO = "BA", TelephoneCode = "+387" },
            new Country { Id = 23, Name = "Botswana", ISO = "BW", TelephoneCode = "+267" },
            new Country { Id = 24, Name = "Brazil", ISO = "BR", TelephoneCode = "+55" },
            new Country { Id = 25, Name = "Brunei", ISO = "BN", TelephoneCode = "+673" },
            new Country { Id = 26, Name = "Bulgaria", ISO = "BG", TelephoneCode = "+359" },
            new Country { Id = 27, Name = "Burkina Faso", ISO = "BF", TelephoneCode = "+226" },
            new Country { Id = 28, Name = "Burundi", ISO = "BI", TelephoneCode = "+257" },
            new Country { Id = 29, Name = "Cabo Verde", ISO = "CV", TelephoneCode = "+238" },
            new Country { Id = 30, Name = "Cambodia", ISO = "KH", TelephoneCode = "+855" },
            new Country { Id = 31, Name = "Cameroon", ISO = "CM", TelephoneCode = "+237" },
            new Country { Id = 32, Name = "Canada", ISO = "CA", TelephoneCode = "+1" },
            new Country { Id = 33, Name = "Central African Republic", ISO = "CF", TelephoneCode = "+236" },
            new Country { Id = 34, Name = "Chad", ISO = "TD", TelephoneCode = "+235" },
            new Country { Id = 35, Name = "Chile", ISO = "CL", TelephoneCode = "+56" },
            new Country { Id = 36, Name = "China", ISO = "CN", TelephoneCode = "+86" },
            new Country { Id = 37, Name = "Colombia", ISO = "CO", TelephoneCode = "+57" },
            new Country { Id = 38, Name = "Comoros", ISO = "KM", TelephoneCode = "+269" },
            new Country { Id = 39, Name = "Congo (Congo-Brazzaville)", ISO = "CG", TelephoneCode = "+242" },
            new Country { Id = 40, Name = "Costa Rica", ISO = "CR", TelephoneCode = "+506" },
            new Country { Id = 41, Name = "Croatia", ISO = "HR", TelephoneCode = "+385" },
            new Country { Id = 42, Name = "Cuba", ISO = "CU", TelephoneCode = "+53" },
            new Country { Id = 43, Name = "Cyprus", ISO = "CY", TelephoneCode = "+357" },
            new Country { Id = 44, Name = "Czechia (Czech Republic)", ISO = "CZ", TelephoneCode = "+420" },
            new Country { Id = 45, Name = "Democratic Republic of the Congo", ISO = "CD", TelephoneCode = "+243" },
            new Country { Id = 46, Name = "Denmark", ISO = "DK", TelephoneCode = "+45" },
            new Country { Id = 47, Name = "Djibouti", ISO = "DJ", TelephoneCode = "+253" },
            new Country { Id = 48, Name = "Dominica", ISO = "DM", TelephoneCode = "+1-767" },
            new Country { Id = 49, Name = "Dominican Republic", ISO = "DO", TelephoneCode = "+1-809" },
            new Country { Id = 50, Name = "Ecuador", ISO = "EC", TelephoneCode = "+593" },
            new Country { Id = 51, Name = "Egypt", ISO = "EG", TelephoneCode = "+20" },
            new Country { Id = 52, Name = "El Salvador", ISO = "SV", TelephoneCode = "+503" },
            new Country { Id = 53, Name = "Equatorial Guinea", ISO = "GQ", TelephoneCode = "+240" },
            new Country { Id = 54, Name = "Eritrea", ISO = "ER", TelephoneCode = "+291" },
            new Country { Id = 55, Name = "Estonia", ISO = "EE", TelephoneCode = "+372" },
            new Country { Id = 56, Name = "Eswatini (Swaziland)", ISO = "SZ", TelephoneCode = "+268" },
            new Country { Id = 57, Name = "Ethiopia", ISO = "ET", TelephoneCode = "+251" },
            new Country { Id = 58, Name = "Fiji", ISO = "FJ", TelephoneCode = "+679" },
            new Country { Id = 59, Name = "Finland", ISO = "FI", TelephoneCode = "+358" },
            new Country { Id = 60, Name = "France", ISO = "FR", TelephoneCode = "+33" },
            new Country { Id = 61, Name = "Gabon", ISO = "GA", TelephoneCode = "+241" },
            new Country { Id = 62, Name = "Gambia", ISO = "GM", TelephoneCode = "+220" },
            new Country { Id = 63, Name = "Georgia", ISO = "GE", TelephoneCode = "+995" },
            new Country { Id = 64, Name = "Germany", ISO = "DE", TelephoneCode = "+49" },
            new Country { Id = 65, Name = "Ghana", ISO = "GH", TelephoneCode = "+233" },
            new Country { Id = 66, Name = "Greece", ISO = "GR", TelephoneCode = "+30" },
            new Country { Id = 67, Name = "Grenada", ISO = "GD", TelephoneCode = "+1-473" },
            new Country { Id = 68, Name = "Guatemala", ISO = "GT", TelephoneCode = "+502" },
            new Country { Id = 69, Name = "Guinea", ISO = "GN", TelephoneCode = "+224" },
            new Country { Id = 70, Name = "Guinea-Bissau", ISO = "GW", TelephoneCode = "+245" },
            new Country { Id = 71, Name = "Guyana", ISO = "GY", TelephoneCode = "+592" },
            new Country { Id = 72, Name = "Haiti", ISO = "HT", TelephoneCode = "+509" },
            new Country { Id = 73, Name = "Honduras", ISO = "HN", TelephoneCode = "+504" },
            new Country { Id = 74, Name = "Hungary", ISO = "HU", TelephoneCode = "+36" },
            new Country { Id = 75, Name = "Iceland", ISO = "IS", TelephoneCode = "+354" },
            new Country { Id = 76, Name = "India", ISO = "IN", TelephoneCode = "+91" },
            new Country { Id = 77, Name = "Indonesia", ISO = "ID", TelephoneCode = "+62" },
            new Country { Id = 78, Name = "Iran", ISO = "IR", TelephoneCode = "+98" },
            new Country { Id = 79, Name = "Iraq", ISO = "IQ", TelephoneCode = "+964" },
            new Country { Id = 80, Name = "Ireland", ISO = "IE", TelephoneCode = "+353" },
            new Country { Id = 81, Name = "Israel", ISO = "IL", TelephoneCode = "+972" },
            new Country { Id = 82, Name = "Italy", ISO = "IT", TelephoneCode = "+39" },
            new Country { Id = 83, Name = "Jamaica", ISO = "JM", TelephoneCode = "+1-876" },
            new Country { Id = 84, Name = "Japan", ISO = "JP", TelephoneCode = "+81" },
            new Country { Id = 85, Name = "Jordan", ISO = "JO", TelephoneCode = "+962" },
            new Country { Id = 86, Name = "Kazakhstan", ISO = "KZ", TelephoneCode = "+7" },
            new Country { Id = 87, Name = "Kenya", ISO = "KE", TelephoneCode = "+254" },
            new Country { Id = 88, Name = "Kiribati", ISO = "KI", TelephoneCode = "+686" },
            new Country { Id = 89, Name = "Kuwait", ISO = "KW", TelephoneCode = "+965" },
            new Country { Id = 90, Name = "Kyrgyzstan", ISO = "KG", TelephoneCode = "+996" },
            new Country { Id = 91, Name = "Laos", ISO = "LA", TelephoneCode = "+856" },
            new Country { Id = 92, Name = "Latvia", ISO = "LV", TelephoneCode = "+371" },
            new Country { Id = 93, Name = "Lebanon", ISO = "LB", TelephoneCode = "+961" },
            new Country { Id = 94, Name = "Lesotho", ISO = "LS", TelephoneCode = "+266" },
            new Country { Id = 95, Name = "Liberia", ISO = "LR", TelephoneCode = "+231" },
            new Country { Id = 96, Name = "Libya", ISO = "LY", TelephoneCode = "+218" },
            new Country { Id = 97, Name = "Liechtenstein", ISO = "LI", TelephoneCode = "+423" },
            new Country { Id = 98, Name = "Lithuania", ISO = "LT", TelephoneCode = "+370" },
            new Country { Id = 99, Name = "Luxembourg", ISO = "LU", TelephoneCode = "+352" },
            new Country { Id = 100, Name = "Madagascar", ISO = "MG", TelephoneCode = "+261" },
            new Country { Id = 101, Name = "Malawi", ISO = "MW", TelephoneCode = "+265" },
            new Country { Id = 102, Name = "Malaysia", ISO = "MY", TelephoneCode = "+60" },
            new Country { Id = 103, Name = "Maldives", ISO = "MV", TelephoneCode = "+960" },
            new Country { Id = 104, Name = "Mali", ISO = "ML", TelephoneCode = "+223" },
            new Country { Id = 105, Name = "Malta", ISO = "MT", TelephoneCode = "+356" },
            new Country { Id = 106, Name = "Marshall Islands", ISO = "MH", TelephoneCode = "+692" },
            new Country { Id = 107, Name = "Mauritania", ISO = "MR", TelephoneCode = "+222" },
            new Country { Id = 108, Name = "Mauritius", ISO = "MU", TelephoneCode = "+230" },
            new Country { Id = 109, Name = "Mexico", ISO = "MX", TelephoneCode = "+52" },
            new Country { Id = 110, Name = "Micronesia", ISO = "FM", TelephoneCode = "+691" },
            new Country { Id = 111, Name = "Moldova", ISO = "MD", TelephoneCode = "+373" },
            new Country { Id = 112, Name = "Monaco", ISO = "MC", TelephoneCode = "+377" },
            new Country { Id = 113, Name = "Mongolia", ISO = "MN", TelephoneCode = "+976" },
            new Country { Id = 114, Name = "Montenegro", ISO = "ME", TelephoneCode = "+382" },
            new Country { Id = 115, Name = "Morocco", ISO = "MA", TelephoneCode = "+212" },
            new Country { Id = 116, Name = "Mozambique", ISO = "MZ", TelephoneCode = "+258" },
            new Country { Id = 117, Name = "Myanmar (Burma)", ISO = "MM", TelephoneCode = "+95" },
            new Country { Id = 118, Name = "Namibia", ISO = "NA", TelephoneCode = "+264" },
            new Country { Id = 119, Name = "Nauru", ISO = "NR", TelephoneCode = "+674" },
            new Country { Id = 120, Name = "Nepal", ISO = "NP", TelephoneCode = "+977" },
            new Country { Id = 121, Name = "Netherlands", ISO = "NL", TelephoneCode = "+31" },
            new Country { Id = 122, Name = "New Zealand", ISO = "NZ", TelephoneCode = "+64" },
            new Country { Id = 123, Name = "Nicaragua", ISO = "NI", TelephoneCode = "+505" },
            new Country { Id = 124, Name = "Niger", ISO = "NE", TelephoneCode = "+227" },
            new Country { Id = 125, Name = "Nigeria", ISO = "NG", TelephoneCode = "+234" },
            new Country { Id = 126, Name = "North Korea", ISO = "KP", TelephoneCode = "+850" },
            new Country { Id = 127, Name = "North Macedonia", ISO = "MK", TelephoneCode = "+389" },
            new Country { Id = 128, Name = "Norway", ISO = "NO", TelephoneCode = "+47" },
            new Country { Id = 129, Name = "Oman", ISO = "OM", TelephoneCode = "+968" },
            new Country { Id = 130, Name = "Pakistan", ISO = "PK", TelephoneCode = "+92" },
            new Country { Id = 131, Name = "Palau", ISO = "PW", TelephoneCode = "+680" },
            new Country { Id = 132, Name = "Palestine State", ISO = "PS", TelephoneCode = "+970" },
            new Country { Id = 133, Name = "Panama", ISO = "PA", TelephoneCode = "+507" },
            new Country { Id = 134, Name = "Papua New Guinea", ISO = "PG", TelephoneCode = "+675" },
            new Country { Id = 135, Name = "Paraguay", ISO = "PY", TelephoneCode = "+595" },
            new Country { Id = 136, Name = "Peru", ISO = "PE", TelephoneCode = "+51" },
            new Country { Id = 137, Name = "Philippines", ISO = "PH", TelephoneCode = "+63" },
            new Country { Id = 138, Name = "Poland", ISO = "PL", TelephoneCode = "+48" },
            new Country { Id = 139, Name = "Portugal", ISO = "PT", TelephoneCode = "+351" },
            new Country { Id = 140, Name = "Qatar", ISO = "QA", TelephoneCode = "+974" },
            new Country { Id = 141, Name = "Romania", ISO = "RO", TelephoneCode = "+40" },
            new Country { Id = 142, Name = "Russia", ISO = "RU", TelephoneCode = "+7" },
            new Country { Id = 143, Name = "Rwanda", ISO = "RW", TelephoneCode = "+250" },
            new Country { Id = 144, Name = "Saint Kitts and Nevis", ISO = "KN", TelephoneCode = "+1-869" },
            new Country { Id = 145, Name = "Saint Lucia", ISO = "LC", TelephoneCode = "+1-758" },
            new Country { Id = 146, Name = "Saint Vincent and the Grenadines", ISO = "VC", TelephoneCode = "+1-784" },
            new Country { Id = 147, Name = "Samoa", ISO = "WS", TelephoneCode = "+685" },
            new Country { Id = 148, Name = "San Marino", ISO = "SM", TelephoneCode = "+378" },
            new Country { Id = 149, Name = "Sao Tome and Principe", ISO = "ST", TelephoneCode = "+239" },
            new Country { Id = 150, Name = "Saudi Arabia", ISO = "SA", TelephoneCode = "+966" },
            new Country { Id = 151, Name = "Senegal", ISO = "SN", TelephoneCode = "+221" },
            new Country { Id = 152, Name = "Serbia", ISO = "RS", TelephoneCode = "+381" },
            new Country { Id = 153, Name = "Seychelles", ISO = "SC", TelephoneCode = "+248" },
            new Country { Id = 154, Name = "Sierra Leone", ISO = "SL", TelephoneCode = "+232" },
            new Country { Id = 155, Name = "Singapore", ISO = "SG", TelephoneCode = "+65" },
            new Country { Id = 156, Name = "Slovakia", ISO = "SK", TelephoneCode = "+421" },
            new Country { Id = 157, Name = "Slovenia", ISO = "SI", TelephoneCode = "+386" },
            new Country { Id = 158, Name = "Solomon Islands", ISO = "SB", TelephoneCode = "+677" },
            new Country { Id = 159, Name = "Somalia", ISO = "SO", TelephoneCode = "+252" },
            new Country { Id = 160, Name = "South Africa", ISO = "ZA", TelephoneCode = "+27" },
            new Country { Id = 161, Name = "South Korea", ISO = "KR", TelephoneCode = "+82" },
            new Country { Id = 162, Name = "South Sudan", ISO = "SS", TelephoneCode = "+211" },
            new Country { Id = 163, Name = "Spain", ISO = "ES", TelephoneCode = "+34" },
            new Country { Id = 164, Name = "Sri Lanka", ISO = "LK", TelephoneCode = "+94" },
            new Country { Id = 165, Name = "Sudan", ISO = "SD", TelephoneCode = "+249" },
            new Country { Id = 166, Name = "Suriname", ISO = "SR", TelephoneCode = "+597" },
            new Country { Id = 167, Name = "Sweden", ISO = "SE", TelephoneCode = "+46" },
            new Country { Id = 168, Name = "Switzerland", ISO = "CH", TelephoneCode = "+41" },
            new Country { Id = 169, Name = "Syria", ISO = "SY", TelephoneCode = "+963" },
            new Country { Id = 170, Name = "Taiwan", ISO = "TW", TelephoneCode = "+886" },
            new Country { Id = 171, Name = "Tajikistan", ISO = "TJ", TelephoneCode = "+992" },
            new Country { Id = 172, Name = "Tanzania", ISO = "TZ", TelephoneCode = "+255" },
            new Country { Id = 173, Name = "Thailand", ISO = "TH", TelephoneCode = "+66" },
            new Country { Id = 174, Name = "Timor-Leste", ISO = "TL", TelephoneCode = "+670" },
            new Country { Id = 175, Name = "Togo", ISO = "TG", TelephoneCode = "+228" },
            new Country { Id = 176, Name = "Tonga", ISO = "TO", TelephoneCode = "+676" },
            new Country { Id = 177, Name = "Trinidad and Tobago", ISO = "TT", TelephoneCode = "+1-868" },
            new Country { Id = 178, Name = "Tunisia", ISO = "TN", TelephoneCode = "+216" },
            new Country { Id = 179, Name = "Turkey", ISO = "TR", TelephoneCode = "+90" },
            new Country { Id = 180, Name = "Turkmenistan", ISO = "TM", TelephoneCode = "+993" },
            new Country { Id = 181, Name = "Tuvalu", ISO = "TV", TelephoneCode = "+688" },
            new Country { Id = 182, Name = "Uganda", ISO = "UG", TelephoneCode = "+256" },
            new Country { Id = 183, Name = "Ukraine", ISO = "UA", TelephoneCode = "+380" },
            new Country { Id = 184, Name = "United Arab Emirates", ISO = "AE", TelephoneCode = "+971" },
            new Country { Id = 185, Name = "United Kingdom", ISO = "GB", TelephoneCode = "+44" },
            new Country { Id = 186, Name = "United States of America", ISO = "US", TelephoneCode = "+1" },
            new Country { Id = 187, Name = "Uruguay", ISO = "UY", TelephoneCode = "+598" },
            new Country { Id = 188, Name = "Uzbekistan", ISO = "UZ", TelephoneCode = "+998" },
            new Country { Id = 189, Name = "Vanuatu", ISO = "VU", TelephoneCode = "+678" },
            new Country { Id = 190, Name = "Venezuela", ISO = "VE", TelephoneCode = "+58" },
            new Country { Id = 191, Name = "Vietnam", ISO = "VN", TelephoneCode = "+84" },
            new Country { Id = 192, Name = "Yemen", ISO = "YE", TelephoneCode = "+967" },
            new Country { Id = 193, Name = "Zambia", ISO = "ZM", TelephoneCode = "+260" },
            new Country { Id = 194, Name = "Zimbabwe", ISO = "ZW", TelephoneCode = "+263" }
        ];
    }
}
