using Demoulas.ProfitSharing.Common.Contracts;
using Demoulas.ProfitSharing.Data.Entities;

namespace Demoulas.ProfitSharing.Services.CheckRun;

/// <summary>
/// Service for managing check run workflows including state tracking and reprint limit enforcement.
/// Enforces business rule: Maximum 2 reprints allowed on same day as original CheckRunDate.
/// </summary>
public interface ICheckRunWorkflowService
{
    /// <summary>
    /// Retrieves the current active workflow for the specified profit year.
    /// </summary>
    /// <param name="profitYear">The profit-sharing year (e.g., 2024).</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>
    /// Result with active CheckRunWorkflow, or Failure if no active workflow exists.
    /// </returns>
    Task<Result<CheckRunWorkflow>> GetCurrentRunAsync(int profitYear, CancellationToken cancellationToken = default);

    /// <summary>
    /// Creates a new check run workflow with the specified initial check number.
    /// </summary>
    /// <param name="profitYear">The profit-sharing year for this run.</param>
    /// <param name="initialCheckNumber">First check number in range 5,000-10,000 (randomly generated by caller).</param>
    /// <param name="userId">User ID creating the workflow.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>
    /// Result with newly created CheckRunWorkflow, or Failure if an active run already exists for the year.
    /// </returns>
    Task<Result<CheckRunWorkflow>> StartNewRunAsync(int profitYear, int initialCheckNumber, Guid userId, CancellationToken cancellationToken = default);

    /// <summary>
    /// Marks the specified workflow step as completed and advances to next step.
    /// </summary>
    /// <param name="runId">Unique identifier of the workflow instance.</param>
    /// <param name="stepNumber">Step number being completed (1=FTP, 2=Print, 3=Reconciliation).</param>
    /// <param name="userId">User ID performing the step completion.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>
    /// Result indicating success or failure of step completion.
    /// </returns>
    Task<Result> RecordStepCompletionAsync(Guid runId, int stepNumber, Guid userId, CancellationToken cancellationToken = default);

    /// <summary>
    /// Validates whether reprinting is allowed for the specified workflow.
    /// Per business requirements: Maximum 2 reprints allowed on same day as original CheckRunDate.
    /// After midnight, reprints are no longer allowed for that run.
    /// </summary>
    /// <param name="runId">Unique identifier of the workflow instance.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>
    /// Result with boolean indicating whether reprint is allowed (true) or not (false).
    /// Validation logic: ReprintCount &lt; MaxReprintCount AND CheckRunDate == Today
    /// </returns>
    Task<Result<bool>> CanReprintAsync(Guid runId, CancellationToken cancellationToken = default);

    /// <summary>
    /// Increments the reprint count after a successful reprint operation.
    /// </summary>
    /// <param name="runId">Unique identifier of the workflow instance.</param>
    /// <param name="userId">User ID performing the reprint.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>
    /// Result indicating success or failure of reprint count increment.
    /// </returns>
    Task<Result> IncrementReprintCountAsync(Guid runId, Guid userId, CancellationToken cancellationToken = default);
}
