using Demoulas.ProfitSharing.Common.Contracts.Request;
using Demoulas.ProfitSharing.Common.Contracts.Response;
using Demoulas.ProfitSharing.Common.Interfaces;
using Demoulas.ProfitSharing.Endpoints.Groups;
using Demoulas.ProfitSharing.Endpoints.Base;
using Demoulas.ProfitSharing.Data.Entities.Navigations;
using Demoulas.ProfitSharing.Security;
using FastEndpoints;

namespace Demoulas.ProfitSharing.Endpoints.Endpoints.Reports.YearEnd.PostFrozen;

public sealed class ProfitControlSheetEndpoint: ProfitSharingEndpoint<ProfitYearRequest, ProfitControlSheetResponse>
{
    private readonly IFrozenReportService _frozenReportService;

    public ProfitControlSheetEndpoint(IFrozenReportService frozenReportService) : base(Navigation.Constants.ProfControlSheet)
    {
        _frozenReportService = frozenReportService;
    }

    public override void Configure()
    {
        Get("post-frozen/control-sheet");
        Summary(s =>
        {
            s.Summary = "Control Sheet previously generated by PROF-CNTRL-SHEET";
            s.Description = "Produces a breakdown of profit sharing amounts by various groups";
            s.ExampleRequest = ProfitYearRequest.RequestExample();
            s.ResponseExamples = new Dictionary<int, object>
            {
                {200,  ProfitControlSheetResponse.ResponseExample()}
            };
            s.Responses[403] = $"Forbidden.  Requires roles of {Role.ADMINISTRATOR} or {Role.FINANCEMANAGER}";
        });
        Group<YearEndGroup>();
    }

    public override Task<ProfitControlSheetResponse> ExecuteAsync(ProfitYearRequest req, CancellationToken ct)
    {
        return _frozenReportService.GetProfitControlSheet(req, ct);
    }
}