using Demoulas.ProfitSharing.Common.Contracts.Request;
using Demoulas.ProfitSharing.Common.Contracts.Response;
using Demoulas.ProfitSharing.Common.Interfaces;
using Demoulas.ProfitSharing.Common.Telemetry;
using Demoulas.ProfitSharing.Data.Entities.Navigations;
using Demoulas.ProfitSharing.Endpoints.Base;
using Demoulas.ProfitSharing.Endpoints.Extensions;
using Demoulas.ProfitSharing.Endpoints.Groups;
using Demoulas.ProfitSharing.Security;
using Microsoft.Extensions.Logging;

namespace Demoulas.ProfitSharing.Endpoints.Endpoints.Reports.YearEnd.PostFrozen;

public sealed class ProfitControlSheetEndpoint : ProfitSharingEndpoint<ProfitYearRequest, ProfitControlSheetResponse>
{
    private readonly IFrozenReportService _frozenReportService;
    private readonly ILogger<ProfitControlSheetEndpoint> _logger;

    public ProfitControlSheetEndpoint(IFrozenReportService frozenReportService, ILogger<ProfitControlSheetEndpoint> logger) : base(Navigation.Constants.ProfControlSheet)
    {
        _frozenReportService = frozenReportService;
        _logger = logger;
    }

    public override void Configure()
    {
        Get("post-frozen/control-sheet");
        Summary(s =>
        {
            s.Summary = "Control Sheet previously generated by PROF-CNTRL-SHEET";
            s.Description = "Produces a breakdown of profit sharing amounts by various groups";
            s.ExampleRequest = ProfitYearRequest.RequestExample();
            s.ResponseExamples = new Dictionary<int, object>
            {
                {200,  ProfitControlSheetResponse.ResponseExample()}
            };
            s.Responses[403] = $"Forbidden.  Requires roles of {Role.ADMINISTRATOR} or {Role.FINANCEMANAGER}";
        });
        Group<YearEndGroup>();
    }

    public override async Task<ProfitControlSheetResponse> ExecuteAsync(ProfitYearRequest req, CancellationToken ct)
    {
        using var activity = this.StartEndpointActivity(HttpContext);
        this.RecordRequestMetrics(HttpContext, _logger, req);

        try
        {
            var result = await _frozenReportService.GetProfitControlSheet(req, ct);

            // Record business operation metrics
            EndpointTelemetry.BusinessOperationsTotal.Add(1,
                new("operation", "profit_control_sheet"),
                new("profit_year", req.ProfitYear.ToString()));

            _logger.LogInformation("Year-end post-frozen profit control sheet generated (correlation: {CorrelationId})",
                HttpContext.TraceIdentifier);

            if (result != null)
            {
                this.RecordResponseMetrics(HttpContext, _logger, result);
                return result;
            }

            var emptyResult = new ProfitControlSheetResponse();
            this.RecordResponseMetrics(HttpContext, _logger, emptyResult);
            return emptyResult;
        }
        catch (Exception ex)
        {
            this.RecordException(HttpContext, _logger, ex, activity);
            throw;
        }
    }
}
