DECLARE 
	FAILED_STATEMENT NUMBER;
BEGIN
	SELECT COUNT(*)
	  INTO FAILED_STATEMENT
	  FROM DEMOGRAPHIC d 
	  FULL OUTER JOIN {SOURCE_PROFITSHARE_SCHEMA}.DEMOGRAPHICS d2 ON d.BADGE_NUMBER = d2.DEM_BADGE
	  WHERE d.ID IS NULL OR d2.DEM_BADGE IS NULL;
	 
	IF FAILED_STATEMENT > 0 THEN 
	  	raise_application_error(-20000, TO_CHAR(FAILED_STATEMENT) || ' Demographic Mismatches');
	END IF;

	SELECT COUNT(*)
	  INTO FAILED_STATEMENT
  FROM DEMOGRAPHIC_HISTORY dh 
  JOIN DEMOGRAPHIC d ON dh.DEMOGRAPHIC_ID  = d.ID  
  FULL OUTER JOIN {SOURCE_PROFITSHARE_SCHEMA}.DEMOGRAPHICS d2 ON d.BADGE_NUMBER = d2.DEM_BADGE 
  WHERE dh.ID  IS NULL OR d2.DEM_BADGE IS NULL;	 
	IF FAILED_STATEMENT > 0 THEN 
	  	raise_application_error(-20000, TO_CHAR(FAILED_STATEMENT) || ' Demographic History Mismatches');
	END IF;

	SELECT COUNT(*)
	  INTO FAILED_STATEMENT
  FROM BENEFICIARY_CONTACT bc
  FULL OUTER JOIN {SOURCE_PROFITSHARE_SCHEMA}.PAYBEN p ON bc.SSN = p.PYBEN_PAYSSN 
  WHERE bc.ID  IS NULL OR p.PYBEN_PAYSSN IS NULL;
	IF FAILED_STATEMENT > 0 THEN 
	  	raise_application_error(-20000, TO_CHAR(FAILED_STATEMENT) || ' Beneficiary Contact Mismatches');
	END IF;

	--Check for Duplicate SSNs in PYBEN
    SELECT COUNT(*)
    INTO FAILED_STATEMENT
	FROM ( 
		SELECT p.PYBEN_PAYSSN
		FROM {SOURCE_PROFITSHARE_SCHEMA}.PAYBEN p 
		GROUP BY p.PYBEN_PAYSSN
		HAVING COUNT(*) > 1
	) x;
	IF FAILED_STATEMENT > 0 THEN 
	  	raise_application_error(-20000, TO_CHAR(FAILED_STATEMENT) || ' duplicate beneficiary SSNs');
	END IF;

    --Check for out of range PSN numbers in PYBEN
    SELECT COUNT(*)
	  INTO FAILED_STATEMENT
    FROM {SOURCE_PROFITSHARE_SCHEMA}.PAYBEN p
    WHERE p.PYBEN_PSN < 1000000000; 
    IF FAILED_STATEMENT > 0 THEN 
	  	raise_application_error(-20000, TO_CHAR(FAILED_STATEMENT) || ' PSNs out of range');
	END IF;

	SELECT COUNT(*)
	  INTO FAILED_STATEMENT
  FROM {SOURCE_PROFITSHARE_SCHEMA}.PAYBEN p
  JOIN {SOURCE_PROFITSHARE_SCHEMA}.PAYREL pr ON p.PYBEN_PSN  = pr.PYREL_PSN 
  FULL OUTER JOIN BENEFICIARY b ON TO_NUMBER(SUBSTR(LPAD(p.PYBEN_PSN,11,0),1,7)) = b.BADGE_NUMBER AND TO_NUMBER(SUBSTR(LPAD(p.PYBEN_PSN, 11, 0), 8)) = b.PSN_SUFFIX 
  WHERE p.PYBEN_PSN IS NULL OR b.ID  IS NULL;
	IF FAILED_STATEMENT > 0 THEN 
	  	raise_application_error(-20000, TO_CHAR(FAILED_STATEMENT) || ' Beneficiary Mismatches');
	END IF;

SELECT COUNT(*)
  INTO FAILED_STATEMENT
  FROM (
	  SELECT pd.SSN, Sum(pd.EARNINGS) AS Earnings , Sum(pd.CONTRIBUTION) AS Contributions , Sum(pd.FORFEITURE) AS forfeitures, Sum(pd.FEDERAL_TAXES) AS federal_taxes, Sum(pd.STATE_TAXES) AS state_taxes
	  FROM PROFIT_DETAIL pd 
	  GROUP BY pd.SSN
	  ) sm
	  FULL OUTER JOIN (
	  	SELECT SSN, Sum(psCmb.Earnings) AS Earnings, Sum(psCmb.Contributions)  AS Contributions , Sum(psCmb.forfeitures) AS forfeitures, Sum(psCmb.federal_taxes) AS federal_taxes, Sum(psCmb.state_taxes) AS state_taxes
		    FROM (
		  SELECT pd2.PR_DET_S_SEC_NUMBER AS SSN, pd2.PROFIT_EARN Earnings, pd2.PROFIT_CONT AS Contributions, pd2.PROFIT_FORT AS forfeitures, pd2.PROFIT_FED_TAXES AS federal_taxes, pd2.PROFIT_STATE_TAXES AS state_taxes
		    FROM {SOURCE_PROFITSHARE_SCHEMA}.PROFIT_DETAIL pd2 
		  UNION ALL
		  SELECT psd.PR_SS_D_S_SEC_NUMBER, psd.PROFIT_SS_EARN, psd.PROFIT_SS_CONT, PROFIT_SS_FORT, psd.PROFIT_SS_FED_TAXES, psd.PROFIT_SS_STATE_TAXES
		    FROM {SOURCE_PROFITSHARE_SCHEMA}.PROFIT_SS_DETAIL psd
	      ) psCmb
	      GROUP BY psCmB.SSN
	  ) rd ON sm.SSN = rd.SSN
	WHERE sm.SSN IS NULL OR rd.SSN IS NULL OR 
		  sm.Earnings <> rd.Earnings OR
		  sm.Contributions <> rd.Contributions OR
	 	  sm.forfeitures <> rd.forfeitures OR 
	 	  sm.federal_taxes <> rd.federal_taxes OR
	   	  sm.state_taxes <> rd.state_taxes;  
	   	 
	IF FAILED_STATEMENT > 0 THEN 
	  	raise_application_error(-20000, TO_CHAR(FAILED_STATEMENT) || ' Profit Detail Mismatches');
	END IF;

	SELECT COUNT(*)
	INTO FAILED_STATEMENT
	FROM (
		SELECT d.SSN, pp.CURRENT_HOURS_YEAR, pp.CURRENT_INCOME_YEAR, pp.ETVA, pp.HOURS_EXECUTIVE, pp.INCOME_EXECUTIVE
		  FROM PAY_PROFIT pp 
		  JOIN DEMOGRAPHIC d ON pp.DEMOGRAPHIC_ID = d.ID
		 WHERE pp.PROFIT_YEAR = {CURRENT_YEAR}
	) spp
	FULL OUTER JOIN (
		SELECT p.PAYPROF_SSN ssn, p.PY_PH AS CURRENT_HOURS_YEAR, p.PY_PD AS CURRENT_INCOME_YEAR, p.PY_PS_ETVA AS ETVA, p.PY_PH_EXEC AS HOURS_EXECUTIVE, p.PY_PD_EXEC AS INCOME_EXECUTIVE
		  FROM {SOURCE_PROFITSHARE_SCHEMA}.PAYPROFIT p 
	) rpp ON spp.SSN = rpp.SSN
	WHERE spp.SSN IS NULL OR rpp.SSN IS NULL 
	OR spp.CURRENT_HOURS_YEAR <> rpp.CURRENT_HOURS_YEAR
	OR spp.CURRENT_INCOME_YEAR <> rpp.CURRENT_INCOME_YEAR
    OR spp.ETVA <> rpp.ETVA
    OR spp.HOURS_EXECUTIVE <> rpp.HOURS_EXECUTIVE
    OR spp.INCOME_EXECUTIVE <> rpp.INCOME_EXECUTIVE;

	IF FAILED_STATEMENT > 0 THEN 
	  	raise_application_error(-20000, TO_CHAR(FAILED_STATEMENT) || ' Current year Pay Profit Mismatches');
	END IF;

	SELECT COUNT(*)
	INTO FAILED_STATEMENT
	FROM (
		SELECT d.SSN, pp.CURRENT_HOURS_YEAR, pp.CURRENT_INCOME_YEAR
		  FROM PAY_PROFIT pp 
		  JOIN DEMOGRAPHIC d ON pp.DEMOGRAPHIC_ID = d.ID
		 WHERE pp.PROFIT_YEAR = ({CURRENT_YEAR} -1)

	) spp
	FULL OUTER JOIN (
		SELECT  p.PAYPROF_SSN AS SSN, p.PY_PH_LASTYR AS CURRENT_HOURS_YEAR, p.PY_PD_LASTYR AS CURRENT_INCOME_YEAR
		  FROM {SOURCE_PROFITSHARE_SCHEMA}.PAYPROFIT p
	) rpp ON spp.SSN = rpp.SSN
	WHERE spp.SSN IS NULL OR rpp.SSN IS NULL 
	OR spp.CURRENT_HOURS_YEAR <> rpp.CURRENT_HOURS_YEAR
	OR spp.CURRENT_INCOME_YEAR <> rpp.CURRENT_INCOME_YEAR;

	IF FAILED_STATEMENT > 0 THEN 
	  	raise_application_error(-20000, TO_CHAR(FAILED_STATEMENT) || ' Prior year Pay Profit Mismatches');
	END IF;

END;      	 
