
-- FIRST EMPTY OUT THE TABLE
TRUNCATE TABLE DISTRIBUTION_THIRDPARTY_PAYEE;
TRUNCATE TABLE DISTRIBUTION_PAYEE;
TRUNCATE TABLE DISTRIBUTION;

-- Migrate data into DISTRIBUTION_PAYEE table from PROFITSHARE_PROFDIST
-- Ensure that there are no duplicate entries based on unique PAYEE (SSN, NAME, and ADDRESS)
INSERT INTO DISTRIBUTION_PAYEE (SSN, NAME, STREET, CITY, STATE, POSTAL_CODE, COUNTRY_ISO, MEMO)
SELECT DISTINCT
    PROFDIST_PAYSSN,
    PROFDIST_PAYNAME,
    PROFDIST_PAYADDR1,
    PROFDIST_PAYCITY,
    PROFDIST_PAYSTATE,
    TO_NCHAR(PROFDIST_PAYZIP1) || PROFDIST_PAYZIP2,
    N'US', -- Default country
    NULL -- No memo available in original data
FROM C##LEGACY.PROFDIST
WHERE PROFDIST_PAYSSN IS NOT NULL;


-- Migrate data into DISTRIBUTION_THIRDPARTY_PAYEE table from PROFITSHARE_PROFDIST
-- Ensure that there are no duplicate entries based on unique third-party payee (SSN, NAME, and ADDRESS)
INSERT INTO DISTRIBUTION_THIRDPARTY_PAYEE (PAYEE, NAME, ACCOUNT, STREET, STREET2, CITY, STATE, POSTAL_CODE, COUNTRY_ISO, MEMO)
SELECT DISTINCT
     PROFDIST_3RDPAYTO,
    PROFDIST_3RDNAME,
    PROFDIST_3RDACCT,
    PROFDIST_3RDADDR1,
    PROFDIST_3RDADDR2,
    PROFDIST_3RDCITY,
    PROFDIST_3RDSTATE,
    TO_NCHAR(PROFDIST_3RDZIP1) || PROFDIST_3RDZIP2,
    N'US', -- Default country
    NULL -- No memo available in original data
FROM C##LEGACY.PROFDIST
WHERE (PROFDIST_3RDPAYTO IS NOT NULL AND TRIM(PROFDIST_3RDPAYTO) != '');


--LOAD DISTRIBUTION TABLE TO - "YOUR CURRENT SCHEMA" FROM - PROFITSHARE
INSERT INTO DISTRIBUTION
   (SSN,
     PAYMENT_SEQUENCE,
    EMPLOYEE_NAME,
    FREQUENCY_ID,
    STATUS_ID,
    PAYEE_ID,
    THIRD_PARTY_PAYEE_ID,
    FORTHEBENEFITOF_PAYEE,
    FORTHEBENEFITOF_ACCOUNT_TYPE,
    TAX1099_FOR_EMPLOYEE,
    TAX1099_FOR_BENEFICIARY,
    FEDERAL_TAX_PERCENTAGE,
    STATE_TAX_PERCENTAGE,
    GROSS_AMOUNT,
    FEDERAL_TAX_AMOUNT,
    STATE_TAX_AMOUNT,
    CHECK_AMOUNT,
    TAX_CODE_ID,
    DECEASED,
    GENDER_ID,
    QDRO,
    MEMO,
    ROTH_IRA)
SELECT
    PROFDIST_SSN,
     PROFDIST_PAYSEQ,
    PROFDIST_EMPNAME,
    PROFDIST_PAYFREQ,
    PROFDIST_PAYFLAG,

    -- Map to DISTRIBUTION_PAYEE table (using a subquery to fetch the correct PAYEE_ID)
    (SELECT ID FROM DISTRIBUTION_PAYEE
     WHERE SSN = PROFDIST_PAYSSN
       AND NAME = PROFDIST_PAYNAME
       AND STREET = PROFDIST_PAYADDR1),

    -- Map to DISTRIBUTION_THIRDPARTY_PAYEE table (using a subquery to fetch the correct THIRD_PARTY_PAYEE_ID)
    (SELECT ID FROM DISTRIBUTION_THIRDPARTY_PAYEE
     WHERE ACCOUNT = PROFDIST_3RDACCT
       AND NAME = PROFDIST_3RDNAME
       AND STREET = PROFDIST_3RDADDR1),

    PROFDIST_FBOPAYTO,
    PROFDIST_FBOTYPE,
    CASE
         WHEN PROFDIST_1099_INFO_EMP = 'Y' THEN 1
         ELSE 0
    END as acode,
    CASE
         WHEN PROFDIST_OTHER_BENEFICIARY = 'Y' THEN 1
         ELSE 0
    END as bcode,
    PROFDIST_FEDPCT,
    PROFDIST_STATEPCT,
    PROFDIST_GROSSAMT,
    PROFDIST_FEDTAX,
    PROFDIST_STATETAX,
    PROFDIST_CHECKAMT,
    PROFDIST_TAXCODE,
     CASE
         WHEN PROFDIST_DECEASED = 'Y' THEN 1
         ELSE 0
    END as ccode,
    CASE
         WHEN PROFDIST_SEX = 'M' THEN 'M'
         WHEN PROFDIST_SEX ='F' THEN 'F'
           ELSE NULL
    END as psex,
    CASE
         WHEN PROFDIST_QDRO = 'Y' THEN 1
         ELSE 0
    END as dcode,
    PROFDIST_MEMO,
    CASE
         WHEN PROFDIST_ROTH_IRA = 'Y' THEN 1
         ELSE 0
    END as ecode
FROM C##LEGACY.PROFDIST;

COMMIT;
