--Transfer outs XFER>07000711000
UPDATE PROFIT_DETAIL pd
SET COMMENT_TYPE_ID = 1,
	COMMENT_RELATED_ORACLE_HCM_ID = (SELECT ORACLE_HCM_ID FROM DEMOGRAPHIC d WHERE d.BADGE_NUMBER = TO_NUMBER(SUBSTR(pd.REMARK,6,7))),
	COMMENT_RELATED_PSN_SUFFIX  = TO_NUMBER(SUBSTR(PD.REMARK,13,4))
WHERE REMARK LIKE 'XFER>%';

UPDATE PROFIT_DETAIL pd
SET COMMENT_TYPE_ID = 1,
	COMMENT_RELATED_ORACLE_HCM_ID = (SELECT ORACLE_HCM_ID FROM DEMOGRAPHIC d WHERE d.BADGE_NUMBER = TO_NUMBER(SUBSTR(pd.REMARK,7,7))),
	COMMENT_RELATED_PSN_SUFFIX  = TO_NUMBER(SUBSTR(PD.REMARK,14,4))
WHERE REMARK LIKE 'XFER >%';

--Tranfer Ins XFER<07000710000
UPDATE PROFIT_DETAIL pd
SET COMMENT_TYPE_ID = 2,
	COMMENT_RELATED_ORACLE_HCM_ID = (SELECT ORACLE_HCM_ID FROM DEMOGRAPHIC d WHERE d.BADGE_NUMBER = TO_NUMBER(SUBSTR(pd.REMARK,6,7))),
	COMMENT_RELATED_PSN_SUFFIX  = TO_NUMBER(SUBSTR(PD.REMARK,13,4))
WHERE REMARK LIKE 'XFER<%';

UPDATE PROFIT_DETAIL pd
SET COMMENT_TYPE_ID = 2,
	COMMENT_RELATED_ORACLE_HCM_ID = (SELECT ORACLE_HCM_ID FROM DEMOGRAPHIC d WHERE d.BADGE_NUMBER = TO_NUMBER(SUBSTR(pd.REMARK,7,7))),
	COMMENT_RELATED_PSN_SUFFIX  = TO_NUMBER(SUBSTR(PD.REMARK,14,4))
WHERE REMARK LIKE 'XFER <%';

--QDRO Out QDRO>07002111000
UPDATE PROFIT_DETAIL pd
SET COMMENT_TYPE_ID = 3,
	COMMENT_RELATED_ORACLE_HCM_ID = (SELECT ORACLE_HCM_ID FROM DEMOGRAPHIC d WHERE d.BADGE_NUMBER = TO_NUMBER(SUBSTR(pd.REMARK,6,7))),
	COMMENT_RELATED_PSN_SUFFIX  = TO_NUMBER(SUBSTR(PD.REMARK,13,4))
WHERE REMARK LIKE 'QDRO>%';

UPDATE PROFIT_DETAIL pd
SET COMMENT_TYPE_ID = 3,
	COMMENT_RELATED_ORACLE_HCM_ID = (SELECT ORACLE_HCM_ID FROM DEMOGRAPHIC d WHERE d.BADGE_NUMBER = TO_NUMBER(SUBSTR(pd.REMARK,7,7))),
	COMMENT_RELATED_PSN_SUFFIX  = TO_NUMBER(SUBSTR(PD.REMARK,14,4))
WHERE REMARK LIKE 'QDRO >%';

--QDRO In QDRO<07002110000
UPDATE PROFIT_DETAIL pd
SET COMMENT_TYPE_ID = 4,
	COMMENT_RELATED_ORACLE_HCM_ID = (SELECT ORACLE_HCM_ID FROM DEMOGRAPHIC d WHERE d.BADGE_NUMBER = TO_NUMBER(SUBSTR(pd.REMARK,6,7))),
	COMMENT_RELATED_PSN_SUFFIX  = TO_NUMBER(SUBSTR(PD.REMARK,13,4))
WHERE REMARK LIKE 'QDRO<%';

UPDATE PROFIT_DETAIL pd
SET COMMENT_TYPE_ID = 4,
	COMMENT_RELATED_ORACLE_HCM_ID = (SELECT ORACLE_HCM_ID FROM DEMOGRAPHIC d WHERE d.BADGE_NUMBER = TO_NUMBER(SUBSTR(pd.REMARK,7,7))),
	COMMENT_RELATED_PSN_SUFFIX  = TO_NUMBER(SUBSTR(PD.REMARK,14,4))
WHERE REMARK LIKE 'QDRO <%';

--V-Only
UPDATE PROFIT_DETAIL pd
SET COMMENT_TYPE_ID = 5
WHERE REMARK LIKE 'V-ONLY%';

--Forfeit
UPDATE PROFIT_DETAIL pd
SET COMMENT_TYPE_ID = 6
WHERE REMARK LIKE 'FORFEIT%';

--Un-Forfeit
UPDATE PROFIT_DETAIL pd
SET COMMENT_TYPE_ID = 7
WHERE REMARK LIKE 'UN-FORFEIT%';

--Class Action
UPDATE PROFIT_DETAIL pd
SET COMMENT_TYPE_ID = 8
WHERE REMARK LIKE 'CLASS-ACTION';

--Voided VOIDED 012257 MA
UPDATE PROFIT_DETAIL pd
SET COMMENT_TYPE_ID = 9,
    COMMENT_RELATED_CHECK_NUMBER = TO_NUMBER(CASE WHEN LENGTH(TRIM(pd.REMARK)) > 14 THEN SUBSTR(pd.REMARK, 8, 6) ELSE NULL END),
    COMMENT_IS_PARTIAL_TRANSACTION = CASE WHEN SUBSTR(pd.REMARK,14,1) = '+' THEN 1 ELSE 0 END,
    COMMENT_RELATED_STATE = SUBSTR(pd.REMARK,15,2)
WHERE REMARK LIKE 'VOIDED%';

--Hardship HRDSHP 021103 MA
UPDATE PROFIT_DETAIL pd
SET COMMENT_TYPE_ID = 10,
    COMMENT_RELATED_CHECK_NUMBER = TO_NUMBER(CASE WHEN LENGTH(TRIM(pd.REMARK)) > 14 THEN SUBSTR(pd.REMARK, 8, 6) ELSE NULL END),
    COMMENT_IS_PARTIAL_TRANSACTION = CASE WHEN SUBSTR(pd.REMARK,14,1) = '+' THEN 1 ELSE 0 END,
    COMMENT_RELATED_STATE = SUBSTR(pd.REMARK,15,2)
WHERE REMARK LIKE 'HRDSHP%';

--Distribution
UPDATE PROFIT_DETAIL pd
SET COMMENT_TYPE_ID = 11,
    COMMENT_RELATED_CHECK_NUMBER = TO_NUMBER(CASE WHEN LENGTH(TRIM(pd.REMARK)) > 14 THEN SUBSTR(pd.REMARK, 8, 6) ELSE NULL END),
    COMMENT_IS_PARTIAL_TRANSACTION = CASE WHEN SUBSTR(pd.REMARK,14,1) = '+' THEN 1 ELSE 0 END,
    COMMENT_RELATED_STATE = SUBSTR(pd.REMARK,15,2)
WHERE REMARK LIKE 'DISTRB%';

UPDATE PROFIT_DETAIL pd
SET COMMENT_TYPE_ID = 11
WHERE REMARK LIKE 'DISTRIBUTION';

--Payoff
UPDATE PROFIT_DETAIL pd
SET COMMENT_TYPE_ID = 12
WHERE REMARK LIKE 'PAYOFF';

--DirPay DIRPAY 048465+MA
UPDATE PROFIT_DETAIL pd
SET COMMENT_TYPE_ID = 13,
    COMMENT_RELATED_CHECK_NUMBER = TO_NUMBER(CASE WHEN LENGTH(TRIM(pd.REMARK)) > 14 THEN SUBSTR(pd.REMARK, 8, 6) ELSE NULL END),
    COMMENT_IS_PARTIAL_TRANSACTION = CASE WHEN SUBSTR(pd.REMARK,14,1) = '+' THEN 1 ELSE 0 END,
    COMMENT_RELATED_STATE = SUBSTR(pd.REMARK,15,2)
WHERE REMARK LIKE 'DIRPAY%';

--Rollover ROLOVR 029663 NH
UPDATE PROFIT_DETAIL pd
SET COMMENT_TYPE_ID = 14,
    COMMENT_RELATED_CHECK_NUMBER = TO_NUMBER(CASE WHEN LENGTH(TRIM(pd.REMARK)) > 14 THEN SUBSTR(pd.REMARK, 8, 6) ELSE NULL END),
    COMMENT_IS_PARTIAL_TRANSACTION = CASE WHEN SUBSTR(pd.REMARK,14,1) = '+' THEN 1 ELSE 0 END,
    COMMENT_RELATED_STATE = SUBSTR(pd.REMARK,15,2)
WHERE REMARK LIKE 'ROLOVR%';

--Rollover ROTHIR 053087+FL
UPDATE PROFIT_DETAIL pd
SET COMMENT_TYPE_ID = 15,
    COMMENT_RELATED_CHECK_NUMBER = TO_NUMBER(CASE WHEN LENGTH(TRIM(pd.REMARK)) > 14 THEN SUBSTR(pd.REMARK, 8, 6) ELSE NULL END),
    COMMENT_IS_PARTIAL_TRANSACTION = CASE WHEN SUBSTR(pd.REMARK,14,1) = '+' THEN 1 ELSE 0 END,
    COMMENT_RELATED_STATE = SUBSTR(pd.REMARK,15,2)
WHERE REMARK LIKE 'ROTHIR%';

--Over 64, years vested
UPDATE PROFIT_DETAIL pd
SET COMMENT_TYPE_ID = 16
WHERE REMARK LIKE '>64-1 YR VEST' OR REMARK LIKE '>64 - 1 YR VEST';

UPDATE PROFIT_DETAIL pd
SET COMMENT_TYPE_ID = 17
WHERE REMARK LIKE '>64-2 YR VEST' OR REMARK LIKE '>64 - 2 YR VEST';

UPDATE PROFIT_DETAIL pd
SET COMMENT_TYPE_ID = 18
WHERE REMARK LIKE '>64-3 YR VEST' OR REMARK LIKE '>64 - 3 YR VEST';

--Military
UPDATE PROFIT_DETAIL pd
SET COMMENT_TYPE_ID = 19
WHERE REMARK LIKE 'MILITARY';

--Other
UPDATE PROFIT_DETAIL pd
SET COMMENT_TYPE_ID = 20
WHERE REMARK LIKE 'OTHER';

--Rev
UPDATE PROFIT_DETAIL pd
SET COMMENT_TYPE_ID = 21
WHERE REMARK LIKE 'REV%';

--Un-Rev
UPDATE PROFIT_DETAIL pd
SET COMMENT_TYPE_ID = 22
WHERE REMARK LIKE 'UN-REV%';