-- Empty both the BENEFICIARY and BENEFICIARY_CONTACT tables
TRUNCATE TABLE BENEFICIARY;
TRUNCATE TABLE BENEFICIARY_CONTACT;

-- Insert contact information into the BENEFICIARY_CONTACT table
INSERT INTO BENEFICIARY_CONTACT
   (SSN,
    FIRST_NAME,
    LAST_NAME,
    DATE_OF_BIRTH,
    STREET,
    CITY,
    STATE,
    POSTAL_CODE,
    PHONE_NUMBER,
    MOBILE_NUMBER,
    EMAIL_ADDRESS)
SELECT
    PYBEN.PYBEN_PAYSSN AS SSN,
    SUBSTR(PYBEN.PYBEN_NAME, INSTR(PYBEN.PYBEN_NAME, ', ') + 2) AS FIRSTNAME,
    SUBSTR(PYBEN.PYBEN_NAME, 1, INSTR(PYBEN.PYBEN_NAME, ',') - 1) AS LASTNAME,
    CASE
        WHEN LENGTH(PYBEN.PYBEN_DOBIRTH) = 8
             AND TO_NUMBER(SUBSTR(PYBEN.PYBEN_DOBIRTH, 5, 2)) BETWEEN 1 AND 12
             AND (
                (TO_NUMBER(SUBSTR(PYBEN.PYBEN_DOBIRTH, 5, 2)) IN (1, 3, 5, 7, 8, 10, 12) AND TO_NUMBER(SUBSTR(PYBEN.PYBEN_DOBIRTH, 7, 2)) BETWEEN 1 AND 31) OR
                (TO_NUMBER(SUBSTR(PYBEN.PYBEN_DOBIRTH, 5, 2)) IN (4, 6, 9, 11) AND TO_NUMBER(SUBSTR(PYBEN.PYBEN_DOBIRTH, 7, 2)) BETWEEN 1 AND 30) OR
                (TO_NUMBER(SUBSTR(PYBEN.PYBEN_DOBIRTH, 5, 2)) = 2 AND TO_NUMBER(SUBSTR(PYBEN.PYBEN_DOBIRTH, 7, 2)) BETWEEN 1 AND 
                    CASE
                        WHEN MOD(TO_NUMBER(SUBSTR(PYBEN.PYBEN_DOBIRTH, 1, 4)), 400) = 0 OR (MOD(TO_NUMBER(SUBSTR(PYBEN.PYBEN_DOBIRTH, 1, 4)), 4) = 0 AND MOD(TO_NUMBER(SUBSTR(PYBEN.PYBEN_DOBIRTH, 1, 4)), 100) != 0)
                        THEN 29
                        ELSE 28
                    END
                )
            )
        THEN TO_DATE(PYBEN.PYBEN_DOBIRTH, 'YYYYMMDD')
        ELSE DATE '1900-01-01'
    END AS DATE_OF_BIRTH,
    PYBEN.PYBEN_ADD AS STREET,
    PYBEN.PYBEN_CITY AS CITY,
    PYBEN.PYBEN_STATE AS STATE,
    PYBEN.PYBEN_ZIP AS POSTAL_CODE,
    PYBEN.PYBEN_PHONE AS PHONE_NUMBER,
    NULL AS MOBILE_NUMBER,  -- Assuming mobile number isn't available
    NULL AS EMAIL_ADDRESS  -- Assuming email isn't available
FROM
    PROFITSHARE.PYBEN;

-- Insert data into the BENEFICIARY table, referencing BENEFICIARY_CONTACT
INSERT INTO BENEFICIARY
   (PSN,
    BENEFICIARYCONTACTID,
    RELATIONSHIP,
    KIND_ID,
    DISTRIBUTION,
    AMOUNT,
    EARNINGS,
    SECONDARY_EARNINGS,
    PERCENT)
SELECT
    PYBEN.PYBEN_PSN AS PSN,
    BC.ID AS BENEFICIARYCONTACTID,  -- Link to BENEFICIARY_CONTACT
    PAYREL.PYREL_TYPE AS RELATIONSHIP,
    CASE 
        WHEN PAYREL.PYREL_TYPE = ' ' THEN NULL
        ELSE PAYREL.PYREL_TYPE
    END AS KIND_ID,
    PYBEN.PYBEN_PSDISB AS DISTRIBUTION,
    PYBEN.PYBEN_PSAMT AS AMOUNT,
    PYBEN.PYBEN_PROF_EARN AS EARNINGS,
    PYBEN.PYBEN_PROF_EARN2 AS SECONDARY_EARNINGS,
    PAYREL.PYREL_PERCENT AS PERCENT
FROM
    PROFITSHARE.PYBEN
JOIN
    BENEFICIARY_CONTACT BC ON PYBEN.PYBEN_PAYSSN = BC.SSN
LEFT JOIN
    PAYREL ON PYBEN.PYBEN_PSN = PAYREL.PYREL_PSN;
