
---THIS SCRIPT WILL LOAD ALL SMART PROFIT SHARING TABLES
---TO "YOUR CURRENT SCHEMA" FROM - PROFITSHARE 
-------------------------------------------------------------------------------------
DECLARE
    this_year NUMBER := 2023; -- Set this to the current year
    last_year NUMBER := 2022; -- Set this to the previous year
BEGIN

-- FIRST EMPTY OUT THE TABLE
EXECUTE IMMEDIATE 'TRUNCATE TABLE PAY_PROFIT';
EXECUTE IMMEDIATE 'TRUNCATE TABLE DEMOGRAPHIC';
EXECUTE IMMEDIATE 'TRUNCATE TABLE PROFIT_DETAIL';
EXECUTE IMMEDIATE 'TRUNCATE TABLE BENEFICIARY_CONTACT';
EXECUTE IMMEDIATE 'TRUNCATE TABLE BENEFICIARY';
EXECUTE IMMEDIATE 'TRUNCATE TABLE DISTRIBUTION';
EXECUTE IMMEDIATE 'TRUNCATE TABLE DISTRIBUTION_PAYEE';
EXECUTE IMMEDIATE 'TRUNCATE TABLE DISTRIBUTION_THIRDPARTY_PAYEE';
--LOAD DEMOGRAPHIC TABLE TO - "YOUR CURRENT SCHEMA" FROM - PROFITSHARE 


INSERT INTO DEMOGRAPHIC
   (ORACLE_HCM_ID,
    SSN,
    BADGE_NUMBER,
    FULL_NAME,
    LAST_NAME,
    FIRST_NAME,
    MIDDLE_NAME,
    STORE_NUMBER,
    PAY_CLASSIFICATION_ID,
    PHONE_NUMBER,
    STREET,
    STREET2,
    CITY,
    STATE,
    POSTAL_CODE,
    DATE_OF_BIRTH,
    FULL_TIME_DATE,
    HIRE_DATE,
    REHIRE_DATE,
    TERMINATION_DATE,
    DEPARTMENT,
    EMPLOYMENT_TYPE_ID,
    GENDER_ID,
    PAY_FREQUENCY_ID,
    TERMINATION_CODE_ID,
    EMPLOYMENT_STATUS_ID)
SELECT
    ROWNUM AS ORACLEHCMID,     
    DEM_SSN,
    DEM_BADGE,
    PY_NAM,
    PY_LNAME,
    PY_FNAME,
    PY_MNAME,
    PY_STOR,
    PY_CLA,
    PY_EMP_TELNO,
    PY_ADD,
    PY_ADD2,
    PY_CITY,
    PY_STATE,
    PY_ZIP,
    CASE
            WHEN LENGTH(PY_DOB) = 8
                AND TO_NUMBER(SUBSTR(PY_DOB, 5, 2)) BETWEEN 1 AND 12
                AND (
                    (TO_NUMBER(SUBSTR(PY_DOB, 5, 2)) IN (1, 3, 5, 7, 8, 10, 12) AND TO_NUMBER(SUBSTR(PY_DOB, 7, 2)) BETWEEN 1 AND 31) OR
                    (TO_NUMBER(SUBSTR(PY_DOB, 5, 2)) IN (4, 6, 9, 11) AND TO_NUMBER(SUBSTR(PY_DOB, 7, 2)) BETWEEN 1 AND 30) OR
                    (TO_NUMBER(SUBSTR(PY_DOB, 5, 2)) = 2 AND TO_NUMBER(SUBSTR(PY_DOB, 7, 2)) BETWEEN 1 AND 
                        CASE
                            WHEN MOD(TO_NUMBER(SUBSTR(PY_DOB, 1, 4)), 400) = 0 OR (MOD(TO_NUMBER(SUBSTR(PY_DOB, 1, 4)), 4) = 0 AND MOD(TO_NUMBER(SUBSTR(PY_DOB, 1, 4)), 100) != 0)
                            THEN 29
                            ELSE 28
                        END
                    )
                )
            THEN TO_DATE(PY_DOB, 'YYYYMMDD')
            ELSE DATE '1900-01-01'
    END AS converted_date,
    CASE
            WHEN PY_FULL_DT = 0 THEN NULL
            WHEN LENGTH(PY_FULL_DT) = 8
                AND TO_NUMBER(SUBSTR(PY_FULL_DT, 5, 2)) BETWEEN 1 AND 12
                AND (
                    (TO_NUMBER(SUBSTR(PY_FULL_DT, 5, 2)) IN (1, 3, 5, 7, 8, 10, 12) AND TO_NUMBER(SUBSTR(PY_FULL_DT, 7, 2)) BETWEEN 1 AND 31) OR
                    (TO_NUMBER(SUBSTR(PY_FULL_DT, 5, 2)) IN (4, 6, 9, 11) AND TO_NUMBER(SUBSTR(PY_FULL_DT, 7, 2)) BETWEEN 1 AND 30) OR
                    (TO_NUMBER(SUBSTR(PY_FULL_DT, 5, 2)) = 2 AND TO_NUMBER(SUBSTR(PY_FULL_DT, 7, 2)) BETWEEN 1 AND 
                        CASE
                            WHEN MOD(TO_NUMBER(SUBSTR(PY_FULL_DT, 1, 4)), 400) = 0 OR (MOD(TO_NUMBER(SUBSTR(PY_FULL_DT, 1, 4)), 4) = 0 AND MOD(TO_NUMBER(SUBSTR(PY_FULL_DT, 1, 4)), 100) != 0)
                            THEN 29
                            ELSE 28
                        END
                    )
                )
            THEN TO_DATE(PY_FULL_DT, 'YYYYMMDD')
            ELSE DATE '1900-01-01'
    END AS converted_date,
    CASE
            WHEN LENGTH(PY_HIRE_DT) = 8
                AND TO_NUMBER(SUBSTR(PY_HIRE_DT, 5, 2)) BETWEEN 1 AND 12
                AND (
                    (TO_NUMBER(SUBSTR(PY_HIRE_DT, 5, 2)) IN (1, 3, 5, 7, 8, 10, 12) AND TO_NUMBER(SUBSTR(PY_HIRE_DT, 7, 2)) BETWEEN 1 AND 31) OR
                    (TO_NUMBER(SUBSTR(PY_HIRE_DT, 5, 2)) IN (4, 6, 9, 11) AND TO_NUMBER(SUBSTR(PY_HIRE_DT, 7, 2)) BETWEEN 1 AND 30) OR
                    (TO_NUMBER(SUBSTR(PY_HIRE_DT, 5, 2)) = 2 AND TO_NUMBER(SUBSTR(PY_HIRE_DT, 7, 2)) BETWEEN 1 AND 
                        CASE
                            WHEN MOD(TO_NUMBER(SUBSTR(PY_HIRE_DT, 1, 4)), 400) = 0 OR (MOD(TO_NUMBER(SUBSTR(PY_HIRE_DT, 1, 4)), 4) = 0 AND MOD(TO_NUMBER(SUBSTR(PY_HIRE_DT, 1, 4)), 100) != 0)
                            THEN 29
                            ELSE 28
                        END
                    )
                )
            THEN TO_DATE(PY_HIRE_DT, 'YYYYMMDD')
            ELSE DATE '1900-01-01'
    END AS converted_date,
    CASE
            WHEN PY_REHIRE_DT = 0 THEN NULL
            WHEN LENGTH(PY_REHIRE_DT) = 8
                AND TO_NUMBER(SUBSTR(PY_REHIRE_DT, 5, 2)) BETWEEN 1 AND 12
                AND (
                    (TO_NUMBER(SUBSTR(PY_REHIRE_DT, 5, 2)) IN (1, 3, 5, 7, 8, 10, 12) AND TO_NUMBER(SUBSTR(PY_REHIRE_DT, 7, 2)) BETWEEN 1 AND 31) OR
                    (TO_NUMBER(SUBSTR(PY_REHIRE_DT, 5, 2)) IN (4, 6, 9, 11) AND TO_NUMBER(SUBSTR(PY_REHIRE_DT, 7, 2)) BETWEEN 1 AND 30) OR
                    (TO_NUMBER(SUBSTR(PY_REHIRE_DT, 5, 2)) = 2 AND TO_NUMBER(SUBSTR(PY_REHIRE_DT, 7, 2)) BETWEEN 1 AND 
                        CASE
                            WHEN MOD(TO_NUMBER(SUBSTR(PY_REHIRE_DT, 1, 4)), 400) = 0 OR (MOD(TO_NUMBER(SUBSTR(PY_REHIRE_DT, 1, 4)), 4) = 0 AND MOD(TO_NUMBER(SUBSTR(PY_REHIRE_DT, 1, 4)), 100) != 0)
                            THEN 29
                            ELSE 28
                        END
                    )
                )
            THEN TO_DATE(PY_REHIRE_DT, 'YYYYMMDD')
            ELSE DATE '1900-01-01'
    END AS converted_date,
    CASE
            WHEN PY_TERM_DT = 0 THEN NULL
            WHEN LENGTH(PY_TERM_DT) = 8
                AND TO_NUMBER(SUBSTR(PY_TERM_DT, 5, 2)) BETWEEN 1 AND 12
                AND (
                    (TO_NUMBER(SUBSTR(PY_TERM_DT, 5, 2)) IN (1, 3, 5, 7, 8, 10, 12) AND TO_NUMBER(SUBSTR(PY_TERM_DT, 7, 2)) BETWEEN 1 AND 31) OR
                    (TO_NUMBER(SUBSTR(PY_TERM_DT, 5, 2)) IN (4, 6, 9, 11) AND TO_NUMBER(SUBSTR(PY_TERM_DT, 7, 2)) BETWEEN 1 AND 30) OR
                    (TO_NUMBER(SUBSTR(PY_TERM_DT, 5, 2)) = 2 AND TO_NUMBER(SUBSTR(PY_TERM_DT, 7, 2)) BETWEEN 1 AND 
                        CASE
                            WHEN MOD(TO_NUMBER(SUBSTR(PY_TERM_DT, 1, 4)), 400) = 0 OR (MOD(TO_NUMBER(SUBSTR(PY_TERM_DT, 1, 4)), 4) = 0 AND MOD(TO_NUMBER(SUBSTR(PY_TERM_DT, 1, 4)), 100) != 0)
                            THEN 29
                            ELSE 28
                        END
                    )
                )
            THEN TO_DATE(PY_TERM_DT, 'YYYYMMDD')
            ELSE DATE '1900-01-01'
    END AS converted_date, 
    PY_DP,
    TRIM(PY_FUL),
    PY_GENDER,
    PY_FREQ,
    CASE
            WHEN PY_TERM = ' ' THEN NULL
            ELSE PY_TERM
    END as termcd,
    (
     SELECT ID
     FROM EMPLOYMENT_STATUS
     WHERE ID=LOWER(PY_SCOD)
    ) AS EMPLOYMENT_STATUS_ID
FROM PROFITSHARE.DEMOGRAPHICS;

--------------------------------------------------------------------------------------


-- Insert contact information into the BENEFICIARY_CONTACT table
INSERT INTO BENEFICIARY_CONTACT
   (SSN,
    FIRST_NAME,
    LAST_NAME,
    DATE_OF_BIRTH,
    STREET,
    CITY,
    STATE,
    POSTAL_CODE,
    PHONE_NUMBER,
    MOBILE_NUMBER,
    EMAIL_ADDRESS)
SELECT
    PYBEN.PYBEN_PAYSSN AS SSN,
    SUBSTR(PYBEN.PYBEN_NAME, INSTR(PYBEN.PYBEN_NAME, ', ') + 2) AS FIRSTNAME,
    SUBSTR(PYBEN.PYBEN_NAME, 1, INSTR(PYBEN.PYBEN_NAME, ',') - 1) AS LASTNAME,
    CASE
        WHEN LENGTH(PYBEN.PYBEN_DOBIRTH) = 8
             AND TO_NUMBER(SUBSTR(PYBEN.PYBEN_DOBIRTH, 5, 2)) BETWEEN 1 AND 12
             AND (
                (TO_NUMBER(SUBSTR(PYBEN.PYBEN_DOBIRTH, 5, 2)) IN (1, 3, 5, 7, 8, 10, 12) AND TO_NUMBER(SUBSTR(PYBEN.PYBEN_DOBIRTH, 7, 2)) BETWEEN 1 AND 31) OR
                (TO_NUMBER(SUBSTR(PYBEN.PYBEN_DOBIRTH, 5, 2)) IN (4, 6, 9, 11) AND TO_NUMBER(SUBSTR(PYBEN.PYBEN_DOBIRTH, 7, 2)) BETWEEN 1 AND 30) OR
                (TO_NUMBER(SUBSTR(PYBEN.PYBEN_DOBIRTH, 5, 2)) = 2 AND TO_NUMBER(SUBSTR(PYBEN.PYBEN_DOBIRTH, 7, 2)) BETWEEN 1 AND 
                    CASE
                        WHEN MOD(TO_NUMBER(SUBSTR(PYBEN.PYBEN_DOBIRTH, 1, 4)), 400) = 0 OR (MOD(TO_NUMBER(SUBSTR(PYBEN.PYBEN_DOBIRTH, 1, 4)), 4) = 0 AND MOD(TO_NUMBER(SUBSTR(PYBEN.PYBEN_DOBIRTH, 1, 4)), 100) != 0)
                        THEN 29
                        ELSE 28
                    END
                )
            )
        THEN TO_DATE(PYBEN.PYBEN_DOBIRTH, 'YYYYMMDD')
        ELSE DATE '1900-01-01'
    END AS DATE_OF_BIRTH,
    PYBEN.PYBEN_ADD AS STREET,
    PYBEN.PYBEN_CITY AS CITY,
    PYBEN.PYBEN_STATE AS STATE,
    PYBEN.PYBEN_ZIP AS POSTAL_CODE,
    NULL AS PHONE_NUMBER, -- phone number isn't available
    NULL AS MOBILE_NUMBER,  -- mobile number isn't available
    NULL AS EMAIL_ADDRESS  -- email isn't available
FROM
    PROFITSHARE.PAYBEN PYBEN;

INSERT INTO BENEFICIARY
   (PSN_SUFFIX,
    BADGE_NUMBER,
    ORACLE_HCM_ID,
    BENEFICIARY_CONTACT_ID,
    RELATIONSHIP,
    KIND_ID,
    DISTRIBUTION,
    AMOUNT,
    EARNINGS,
    SECONDARY_EARNINGS,
    PERCENT)
SELECT
    TO_NUMBER(SUBSTR( PYBEN.PYBEN_PSN, 7)) AS PSN_SUFFIX,
    TO_NUMBER(SUBSTR( PYBEN.PYBEN_PSN, 0, 6)) AS BADGE_NUMBER,
    DEMOGRAPHIC.ORACLE_HCM_ID,
     BC.ID AS BENEFICIARY_CONTACT_ID,  -- Link to BENEFICIARY_CONTACT
PAYREL.PYREL_RELATION AS RELATION,
    CASE
            WHEN PAYREL.PYREL_TYPE = ' ' THEN NULL
            ELSE PAYREL.PYREL_TYPE
    END AS KIND_ID,
    PYBEN.PYBEN_PSAMT,
    PYBEN.PYBEN_PSDISB,
    PYBEN.PYBEN_PROF_EARN,
    PYBEN.PYBEN_PROF_EARN2,
    PAYREL.PYREL_PERCENT AS PERCENT    
FROM PROFITSHARE.PAYBEN PYBEN
INNER JOIN BENEFICIARY_CONTACT BC ON PYBEN.PYBEN_PAYSSN = BC.SSN
INNER JOIN DEMOGRAPHIC ON TO_NUMBER(SUBSTR( PYBEN.PYBEN_PSN, 0, 6)) = DEMOGRAPHIC.BADGE_NUMBER
LEFT JOIN PROFITSHARE.PAYREL ON PYBEN.PYBEN_PSN = PAYREL.PYREL_PSN;

--------------------------------------------------------------------------------------------------

 

-------------------------------------------------------------------------------
    -- Insert THIS YEARS data into the PAY_PROFIT table
    INSERT INTO PAY_PROFIT
       (ORACLE_HCM_ID,
        PROFIT_YEAR,
        CURRENT_HOURS_YEAR,
        CURRENT_INCOME_YEAR,
        EARNINGS_ETVA_VALUE,
        SECONDARY_EARNINGS,
        SECONDARY_ETVA_EARNINGS,
        WEEKS_WORKED_YEAR,
        PS_CERTIFICATE_ISSUED_DATE,
        ENROLLMENT_ID,
        BENEFICIARY_TYPE_ID,
        EMPLOYEE_TYPE_ID,
        ZERO_CONTRIBUTION_REASON_ID,
        HOURS_EXECUTIVE,
        INCOME_EXECUTIVE)
    SELECT
        (select ORACLE_HCM_ID from DEMOGRAPHIC where BADGE_NUMBER = PAYPROF_BADGE) AS ORACLE_HCM_ID,
        this_year AS PROFIT_YEAR,
        PY_PH AS CURRENT_HOURS_YEAR,
        PY_PD AS CURRENT_INCOME_YEAR,
        PY_PROF_ETVA AS EARNINGS_ETVA_VALUE,
        PY_PROF_EARN2 AS SECONDARY_EARNINGS,
        PY_PROF_ETVA2 AS SECONDARY_ETVA_EARNINGS,
        PY_WEEKS_WORK AS WEEKS_WORKED_YEAR,
        CASE
            WHEN PY_PROF_CERT = '1' THEN
                TO_DATE(TO_CHAR(this_year) || '-01-01', 'YYYY-MM-DD')
            ELSE NULL
        END AS PS_CERTIFICATE_ISSUED_DATE,
        PY_PS_ENROLLED AS ENROLLMENT_ID,
        PY_PROF_BENEFICIARY AS BENEFICIARY_ID,
        PY_PROF_NEWEMP AS EMPLOYEE_TYPE_ID,
        PY_PROF_ZEROCONT AS ZERO_CONTRIBUTION_REASON_ID,
        NVL(PY_PH_EXEC, 0) AS HOURS_EXECUTIVE,
        NVL(PY_PD_EXEC, 0) AS INCOME_EXECUTIVE
    FROM PROFITSHARE.PAYPROFIT
    where PAYPROF_BADGE in ( select BADGE_NUMBER from DEMOGRAPHIC  );

    -- Insert LAST YEARS data into the PAY_PROFIT table
    INSERT INTO PAY_PROFIT
       (ORACLE_HCM_ID,
        PROFIT_YEAR,
        CURRENT_HOURS_YEAR,
        CURRENT_INCOME_YEAR,
        EARNINGS_ETVA_VALUE,
        SECONDARY_EARNINGS,
        SECONDARY_ETVA_EARNINGS,
        WEEKS_WORKED_YEAR,
        PS_CERTIFICATE_ISSUED_DATE,
        ENROLLMENT_ID,
        BENEFICIARY_TYPE_ID,
        EMPLOYEE_TYPE_ID,
        ZERO_CONTRIBUTION_REASON_ID,
        HOURS_EXECUTIVE,
        INCOME_EXECUTIVE)
    SELECT
        (select ORACLE_HCM_ID from DEMOGRAPHIC where BADGE_NUMBER = PAYPROF_BADGE) AS ORACLE_HCM_ID,
        last_year AS PROFIT_YEAR,
        PY_PH_LASTYR AS CURRENT_HOURS_YEAR,
        PY_PD_LASTYR AS CURRENT_INCOME_YEAR,
        PY_PROF_ETVA AS EARNINGS_ETVA_VALUE,
        0 AS SECONDARY_EARNINGS, -- History not previously tracked
        0 AS SECONDARY_ETVA_EARNINGS, -- History not previously tracked
        PY_WEEKS_WORK_LAST AS WEEKS_WORKED_YEAR,
        null AS PS_CERTIFICATE_ISSUED_DATE,
        9 AS ENROLLMENT_ID, -- 9/History not previously tracked
        PY_PROF_BENEFICIARY AS BENEFICIARY_ID,
         CASE
            WHEN PY_PROF_NEWEMP  = '1' THEN
                0
            ELSE 0
        END AS EMPLOYEE_TYPE_ID,
        8 AS ZERO_CONTRIBUTION_REASON_ID, -- 8/History not previously tracked (Unknown)
        0 AS HOURS_EXECUTIVE, -- History not previously tracked
        0 AS INCOME_EXECUTIVE -- History not previously tracked
    FROM PROFITSHARE.PAYPROFIT
    where PAYPROF_BADGE in ( select BADGE_NUMBER from DEMOGRAPHIC  );

---------------------------------------------------------------

-- Migrate data into DISTRIBUTION_PAYEE table from PROFITSHARE_PROFDIST
-- Ensure that there are no duplicate entries based on unique PAYEE (SSN, NAME, and ADDRESS)
INSERT INTO DISTRIBUTION_PAYEE (SSN, NAME, STREET, CITY, STATE, POSTAL_CODE, COUNTRY_ISO, MEMO)
SELECT DISTINCT
    PROFDIST_PAYSSN,
    PROFDIST_PAYNAME,
    PROFDIST_PAYADDR1,
    PROFDIST_PAYCITY,
    PROFDIST_PAYSTATE,
    TO_NCHAR(PROFDIST_PAYZIP1) || PROFDIST_PAYZIP2,
    N'US', -- Default country
    NULL -- No memo available in original data
FROM PROFITSHARE.PROFDIST
WHERE PROFDIST_PAYSSN IS NOT NULL;


-- Migrate data into DISTRIBUTION_THIRDPARTY_PAYEE table from PROFITSHARE_PROFDIST
-- Ensure that there are no duplicate entries based on unique third-party payee (SSN, NAME, and ADDRESS)
INSERT INTO DISTRIBUTION_THIRDPARTY_PAYEE (PAYEE, NAME, ACCOUNT, STREET, STREET2, CITY, STATE, POSTAL_CODE, COUNTRY_ISO, MEMO)
SELECT DISTINCT
     PROFDIST_3RDPAYTO,
    PROFDIST_3RDNAME,
    PROFDIST_3RDACCT,
    PROFDIST_3RDADDR1,
    PROFDIST_3RDADDR2,
    PROFDIST_3RDCITY,
    PROFDIST_3RDSTATE,
    TO_NCHAR(PROFDIST_3RDZIP1) || PROFDIST_3RDZIP2,
    N'US', -- Default country
    NULL -- No memo available in original data
FROM PROFITSHARE.PROFDIST
WHERE (PROFDIST_3RDPAYTO IS NOT NULL AND TRIM(PROFDIST_3RDPAYTO) != '');


--LOAD DISTRIBUTION TABLE TO - "YOUR CURRENT SCHEMA" FROM - PROFITSHARE
INSERT INTO DISTRIBUTION
   (SSN,
     PAYMENT_SEQUENCE,
    EMPLOYEE_NAME,
    FREQUENCY_ID,
    STATUS_ID,
    PAYEE_ID,
    THIRD_PARTY_PAYEE_ID,
    FORTHEBENEFITOF_PAYEE,
    FORTHEBENEFITOF_ACCOUNT_TYPE,
    TAX1099_FOR_EMPLOYEE,
    TAX1099_FOR_BENEFICIARY,
    FEDERAL_TAX_PERCENTAGE,
    STATE_TAX_PERCENTAGE,
    GROSS_AMOUNT,
    FEDERAL_TAX_AMOUNT,
    STATE_TAX_AMOUNT,
    CHECK_AMOUNT,
    TAX_CODE_ID,
    DECEASED,
    GENDER_ID,
    QDRO,
    MEMO,
    ROTH_IRA)
SELECT
    PROFDIST_SSN,
     PROFDIST_PAYSEQ,
    PROFDIST_EMPNAME,
    PROFDIST_PAYFREQ,
    PROFDIST_PAYFLAG,

    -- Map to DISTRIBUTION_PAYEE table (using a subquery to fetch the correct PAYEE_ID)
    (SELECT ID FROM DISTRIBUTION_PAYEE
     WHERE SSN = PROFDIST_PAYSSN
       AND NAME = PROFDIST_PAYNAME
       AND STREET = PROFDIST_PAYADDR1),

    -- Map to DISTRIBUTION_THIRDPARTY_PAYEE table (using a subquery to fetch the correct THIRD_PARTY_PAYEE_ID)
    (SELECT ID FROM DISTRIBUTION_THIRDPARTY_PAYEE
     WHERE ACCOUNT = PROFDIST_3RDACCT
       AND NAME = PROFDIST_3RDNAME
       AND STREET = PROFDIST_3RDADDR1),

    PROFDIST_FBOPAYTO,
    PROFDIST_FBOTYPE,
    CASE
         WHEN PROFDIST_1099_INFO_EMP = 'Y' THEN 1
         ELSE 0
    END as acode,
    CASE
         WHEN PROFDIST_OTHER_BENEFICIARY = 'Y' THEN 1
         ELSE 0
    END as bcode,
    PROFDIST_FEDPCT,
    PROFDIST_STATEPCT,
    PROFDIST_GROSSAMT,
    PROFDIST_FEDTAX,
    PROFDIST_STATETAX,
    PROFDIST_CHECKAMT,
    PROFDIST_TAXCODE,
     CASE
         WHEN PROFDIST_DECEASED = 'Y' THEN 1
         ELSE 0
    END as ccode,
    CASE
         WHEN PROFDIST_SEX = 'M' THEN 'M'
         WHEN PROFDIST_SEX ='F' THEN 'F'
           ELSE NULL
    END as psex,
    CASE
         WHEN PROFDIST_QDRO = 'Y' THEN 1
         ELSE 0
    END as dcode,
    PROFDIST_MEMO,
    CASE
         WHEN PROFDIST_ROTH_IRA = 'Y' THEN 1
         ELSE 0
    END as ecode
FROM PROFITSHARE.PROFDIST;

INSERT INTO PROFIT_DETAIL
   (PROFIT_YEAR,
    PROFIT_YEAR_ITERATION,
    PROFIT_CODE_ID,
    CONTRIBUTION,
    EARNINGS,
    FORFEITURE,
    ZERO_CONTRIBUTION_REASON_ID,
    FEDERAL_TAXES,
    STATE_TAXES,
    TAX_CODE_ID,
    SSN,
    DISTRIBUTION_SEQUENCE,
    MONTH_TO_DATE,
    REMARK,
    YEAR_TO_DATE,
    IS_TRANSFER_IN,
    IS_TRANSFER_OUT,
    TRANSFER_PSN)
SELECT
    TRUNC(PROFIT_YEAR),
    MOD(PROFIT_YEAR * 10, 10),
    PROFIT_CODE,
    PROFIT_CONT,
    PROFIT_EARN,
    PROFIT_FORT,
    CASE
         WHEN PROFIT_ZEROCONT = ' ' THEN NULL
         ELSE PROFIT_ZEROCONT
    END as Zcode,
    NVL(PROFIT_FED_TAXES,0),
    NVL(PROFIT_STATE_TAXES,0),
    CASE
        WHEN PROFIT_TAX_CODE = ' ' THEN NULL
        ELSE PROFIT_TAX_CODE
    END as ptcode,
    PR_DET_S_SEC_NUMBER,
    PROFIT_DET_PR_DET_S_SEQNUM,
    PROFIT_MDTE,
    CASE
         WHEN TRIM(PROFIT_CMNT) = '' THEN NULL
         ELSE PROFIT_CMNT
    END as pcmnt,
    CASE
        WHEN TO_NUMBER(PROFIT_YDTE) >= 59 THEN '19' || PROFIT_YDTE
        ELSE '20' || PROFIT_YDTE
    END AS FOUR_DIGIT_YEAR,
    CASE WHEN SUBSTR(PROFIT_CMNT,1,5) = 'XFER<'
         THEN 1 ELSE 0 
    END AS IS_TRANSFER_IN,
    CASE WHEN SUBSTR(PROFIT_CMNT,1,5) = 'XFER>'
         THEN 1 ELSE 0 
    END AS IS_TRANSFER_OUT,
    CASE WHEN SUBSTR(PROFIT_CMNT,1,4) = 'XFER'
    	THEN SUBSTR(PROFIT_CMNT,6) ELSE NULL
    END AS TRANSFER_PSN 
FROM PROFITSHARE.PROFIT_DETAIL;

-----------------THIS IS THE OTHER TABLE THAT ALSO GOES TO PROFIT_DETAIL----------------
-- DO NOT TRUNCATE TABLE

 INSERT INTO PROFIT_DETAIL
   (PROFIT_YEAR,
    PROFIT_YEAR_ITERATION,
    PROFIT_CODE_ID,
    CONTRIBUTION,
    EARNINGS,
    FORFEITURE,
    ZERO_CONTRIBUTION_REASON_ID,
    FEDERAL_TAXES,
    STATE_TAXES,
    TAX_CODE_ID,
    SSN,
    DISTRIBUTION_SEQUENCE,
    MONTH_TO_DATE,
    REMARK,
    YEAR_TO_DATE,
    IS_TRANSFER_IN,
    IS_TRANSFER_OUT,
    TRANSFER_PSN)
SELECT
    TRUNC(PROFIT_SS_YEAR),
    MOD(PROFIT_SS_YEAR * 10, 10),
    PROFIT_SS_CODE,
    PROFIT_SS_CONT,
    PROFIT_SS_EARN,
    PROFIT_SS_FORT,
    CASE
         WHEN PROFIT_SS_ZEROCONT = ' ' THEN NULL
         ELSE PROFIT_SS_ZEROCONT
    END as Zcode,
    NVL(PROFIT_SS_FED_TAXES,0),
    NVL(PROFIT_SS_STATE_TAXES,0),
    CASE
        WHEN PROFIT_SS_TAX_CODE = ' ' THEN NULL
        ELSE PROFIT_SS_TAX_CODE
    END as ptcode,
    PR_SS_D_S_SEC_NUMBER,
    PROFIT_SS_DET_PR_SS_D_S_SEQNUM,
    PROFIT_SS_MDTE,
    CASE
         WHEN TRIM(PROFIT_SS_CMNT) = '' THEN NULL
         ELSE PROFIT_SS_CMNT
    END as pcmnt,
    CASE
        WHEN TO_NUMBER(PROFIT_SS_YDTE) >= 59 THEN '19' || PROFIT_SS_YDTE
        ELSE '20' || PROFIT_SS_YDTE
    END AS FOUR_DIGIT_YEAR,
    CASE WHEN SUBSTR(PROFIT_SS_CMNT,1,5) = 'XFER<'
         THEN 1 ELSE 0 
    END AS IS_TRANSFER_IN,
    CASE WHEN SUBSTR(PROFIT_SS_CMNT,1,5) = 'XFER>'
         THEN 1 ELSE 0 
    END AS IS_TRANSFER_OUT,
    CASE WHEN SUBSTR(PROFIT_SS_CMNT,1,4) = 'XFER'
    	THEN SUBSTR(PROFIT_SS_CMNT,6) ELSE NULL
    END AS TRANSFER_PSN 
FROM PROFITSHARE.PROFIT_SS_DETAIL;
---------------------------------------------------------------------------------------------------------------------
END;
COMMIT ;