DECLARE
    this_year NUMBER := 2023; -- Set this to the current year
    last_year NUMBER := 2022; -- Set this to the previous year
BEGIN
    -- Truncate the table before inserting data
    EXECUTE IMMEDIATE 'TRUNCATE TABLE PAY_PROFIT';

    -- Insert THIS YEARS data into the PAY_PROFIT table
    INSERT INTO PAY_PROFIT
       (ORACLE_HCM_ID,
        PROFIT_YEAR,
        CURRENT_HOURS_YEAR,
        CURRENT_INCOME_YEAR,
        EARNINGS_ETVA_VALUE,
        SECONDARY_EARNINGS,
        SECONDARY_ETVA_EARNINGS,
        WEEKS_WORKED_YEAR,
        PS_CERTIFICATE_ISSUED_DATE,
        ENROLLMENT_ID,
        BENEFICIARY_ID,
        EMPLOYEE_TYPE_ID,
        ZERO_CONTRIBUTION_REASON_ID,
        HOURS_EXECUTIVE,
        INCOME_EXECUTIVE,
        POINTS_EARNED)
    SELECT
        (select ORACLE_HCM_ID from DEMOGRAPHIC where BADGE_NUMBER = PAYPROF_BADGE) AS ORACLE_HCM_ID,
        this_year AS PROFIT_YEAR,
        PY_PH AS CURRENT_HOURS_YEAR,
        PY_PD AS CURRENT_INCOME_YEAR,
        PY_PROF_ETVA AS EARNINGS_ETVA_VALUE,
        PY_PROF_EARN2 AS SECONDARY_EARNINGS,
        PY_PROF_ETVA2 AS SECONDARY_ETVA_EARNINGS,
        PY_WEEKS_WORK AS WEEKS_WORKED_YEAR,
        CASE
            WHEN PY_PROF_CERT = '1' THEN
                TO_DATE(TO_CHAR(this_year) || '-01-01', 'YYYY-MM-DD')
            ELSE NULL
        END AS PS_CERTIFICATE_ISSUED_DATE,
        PY_PS_ENROLLED AS ENROLLMENT_ID,
        PY_PROF_BENEFICIARY AS BENEFICIARY_ID,
        PY_PROF_NEWEMP AS EMPLOYEE_TYPE_ID,
        PY_PROF_ZEROCONT AS ZERO_CONTRIBUTION_REASON_ID,
        NVL(PY_PH_EXEC, 0) AS HOURS_EXECUTIVE,
        NVL(PY_PD_EXEC, 0) AS INCOME_EXECUTIVE,
        0 -- Field in current system is for prior year, not current
    FROM PROFITSHARE.PAYPROFIT
    where PAYPROF_BADGE in ( select BADGE_NUMBER from DEMOGRAPHIC  );

    -- Insert LAST YEARS data into the PAY_PROFIT table
    INSERT INTO PAY_PROFIT
       (ORACLE_HCM_ID,
        PROFIT_YEAR,
        CURRENT_HOURS_YEAR,
        CURRENT_INCOME_YEAR,
        EARNINGS_ETVA_VALUE,
        SECONDARY_EARNINGS,
        SECONDARY_ETVA_EARNINGS,
        WEEKS_WORKED_YEAR,
        PS_CERTIFICATE_ISSUED_DATE,
        ENROLLMENT_ID,
        BENEFICIARY_ID,
        EMPLOYEE_TYPE_ID,
        ZERO_CONTRIBUTION_REASON_ID,
        HOURS_EXECUTIVE,
        INCOME_EXECUTIVE,
        POINTS_EARNED)
    SELECT
        (select ORACLE_HCM_ID from DEMOGRAPHIC where BADGE_NUMBER = PAYPROF_BADGE) AS ORACLE_HCM_ID,
        last_year AS PROFIT_YEAR,
        PY_PH_LASTYR AS CURRENT_HOURS_YEAR,
        PY_PD_LASTYR AS CURRENT_INCOME_YEAR,
        PY_PROF_ETVA AS EARNINGS_ETVA_VALUE,
        0 AS SECONDARY_EARNINGS, -- History not previously tracked
        0 AS SECONDARY_ETVA_EARNINGS, -- History not previously tracked
        PY_WEEKS_WORK_LAST AS WEEKS_WORKED_YEAR,
        null AS PS_CERTIFICATE_ISSUED_DATE,
        9 AS ENROLLMENT_ID, -- 9/History not previously tracked
        PY_PROF_BENEFICIARY AS BENEFICIARY_ID,
         CASE
            WHEN PY_PROF_NEWEMP  = '1' THEN
                0
            ELSE 0
        END AS EMPLOYEE_TYPE_ID,
        8 AS ZERO_CONTRIBUTION_REASON_ID, -- 8/History not previously tracked (Unknown)
        0 AS HOURS_EXECUTIVE, -- History not previously tracked
        0 AS INCOME_EXECUTIVE, -- History not previously tracked
        PY_PROF_POINTS  as POINTS_EARNED
    FROM PROFITSHARE.PAYPROFIT
    where PAYPROF_BADGE in ( select BADGE_NUMBER from DEMOGRAPHIC  );
END;
COMMIT ;
