-- Empty both the BENEFICIARY and BENEFICIARY_CONTACT tables
TRUNCATE TABLE BENEFICIARY;
TRUNCATE TABLE BENEFICIARY_CONTACT;

-- Insert contact information into the BENEFICIARY_CONTACT table
INSERT INTO BENEFICIARY_CONTACT
   (SSN,
    FIRST_NAME,
    LAST_NAME,
    DATE_OF_BIRTH,
    STREET,
    CITY,
    STATE,
    POSTAL_CODE,
    PHONE_NUMBER,
    MOBILE_NUMBER,
    EMAIL_ADDRESS)
SELECT
    PYBEN.PYBEN_PAYSSN AS SSN,
    SUBSTR(PYBEN.PYBEN_NAME, INSTR(PYBEN.PYBEN_NAME, ', ') + 2) AS FIRSTNAME,
    SUBSTR(PYBEN.PYBEN_NAME, 1, INSTR(PYBEN.PYBEN_NAME, ',') - 1) AS LASTNAME,
    CASE
        WHEN LENGTH(PYBEN.PYBEN_DOBIRTH) = 8
             AND TO_NUMBER(SUBSTR(PYBEN.PYBEN_DOBIRTH, 5, 2)) BETWEEN 1 AND 12
             AND (
                (TO_NUMBER(SUBSTR(PYBEN.PYBEN_DOBIRTH, 5, 2)) IN (1, 3, 5, 7, 8, 10, 12) AND TO_NUMBER(SUBSTR(PYBEN.PYBEN_DOBIRTH, 7, 2)) BETWEEN 1 AND 31) OR
                (TO_NUMBER(SUBSTR(PYBEN.PYBEN_DOBIRTH, 5, 2)) IN (4, 6, 9, 11) AND TO_NUMBER(SUBSTR(PYBEN.PYBEN_DOBIRTH, 7, 2)) BETWEEN 1 AND 30) OR
                (TO_NUMBER(SUBSTR(PYBEN.PYBEN_DOBIRTH, 5, 2)) = 2 AND TO_NUMBER(SUBSTR(PYBEN.PYBEN_DOBIRTH, 7, 2)) BETWEEN 1 AND 
                    CASE
                        WHEN MOD(TO_NUMBER(SUBSTR(PYBEN.PYBEN_DOBIRTH, 1, 4)), 400) = 0 OR (MOD(TO_NUMBER(SUBSTR(PYBEN.PYBEN_DOBIRTH, 1, 4)), 4) = 0 AND MOD(TO_NUMBER(SUBSTR(PYBEN.PYBEN_DOBIRTH, 1, 4)), 100) != 0)
                        THEN 29
                        ELSE 28
                    END
                )
            )
        THEN TO_DATE(PYBEN.PYBEN_DOBIRTH, 'YYYYMMDD')
        ELSE DATE '1900-01-01'
    END AS DATE_OF_BIRTH,
    PYBEN.PYBEN_ADD AS STREET,
    PYBEN.PYBEN_CITY AS CITY,
    PYBEN.PYBEN_STATE AS STATE,
    PYBEN.PYBEN_ZIP AS POSTAL_CODE,
    NULL AS PHONE_NUMBER, -- phone number isn't available
    NULL AS MOBILE_NUMBER,  -- mobile number isn't available
    NULL AS EMAIL_ADDRESS  -- email isn't available
FROM
    PROFITSHARE.PAYBEN PYBEN;

INSERT INTO BENEFICIARY
   (PSN_SUFFIX,
    EMPLOYEE_ID,
    ORACLE_HCM_ID,
    BENEFICIARYCONTACTID,
    RELATIONSHIP,
    KIND_ID,
    DISTRIBUTION,
    AMOUNT,
    EARNINGS,
    SECONDARY_EARNINGS,
    PERCENT)
SELECT
    TO_NUMBER(SUBSTR( PYBEN.PYBEN_PSN, 7)) AS PSN_SUFFIX,
    TO_NUMBER(SUBSTR( PYBEN.PYBEN_PSN, 0, 6)) AS EMPLOYEE_ID,
    DEMOGRAPHIC.ORACLE_HCM_ID,
     BC.ID AS BENEFICIARYCONTACTID,  -- Link to BENEFICIARY_CONTACT
PAYREL.PYREL_RELATION AS RELATION,
    CASE
            WHEN PAYREL.PYREL_TYPE = ' ' THEN NULL
            ELSE PAYREL.PYREL_TYPE
    END AS KIND_ID,
    PYBEN.PYBEN_PSAMT,
    PYBEN.PYBEN_PSDISB,
    PYBEN.PYBEN_PROF_EARN,
    PYBEN.PYBEN_PROF_EARN2,
    PAYREL.PYREL_PERCENT AS PERCENT    
FROM PROFITSHARE.PAYBEN PYBEN
INNER JOIN BENEFICIARY_CONTACT BC ON PYBEN.PYBEN_PAYSSN = BC.SSN
INNER JOIN DEMOGRAPHIC ON TO_NUMBER(SUBSTR( PYBEN.PYBEN_PSN, 0, 6)) = DEMOGRAPHIC.EMPLOYEE_ID
LEFT JOIN PROFITSHARE.PAYREL ON PYBEN.PYBEN_PSN = PAYREL.PYREL_PSN;

COMMIT;
