-- FIRST EMPTY OUT THE TABLE
TRUNCATE TABLE PROFIT_DETAIL;

 INSERT INTO PROFIT_DETAIL
   (PROFIT_YEAR,
    PROFIT_YEAR_ITERATION,
    PROFIT_CODE_ID,
    CONTRIBUTION,
    EARNINGS,
    FORFEITURE,
    ZERO_CONTRIBUTION_REASON_ID,
    FEDERAL_TAXES,
    STATE_TAXES,
    TAX_CODE_ID,
    SSN,
    DISTRIBUTION_SEQUENCE,
    MONTH_TO_DATE,
    REMARK,
    YEAR_TO_DATE,
    IS_TRANSFER_IN,
    IS_TRANSFER_OUT,
    TRANSFER_PSN)
SELECT
    TRUNC(PROFIT_YEAR),
    MOD(PROFIT_YEAR * 10, 10),
    PROFIT_CODE,
    PROFIT_CONT,
    PROFIT_EARN,
    PROFIT_FORT,
    CASE
         WHEN PROFIT_ZEROCONT = ' ' THEN NULL
         ELSE PROFIT_ZEROCONT
    END as Zcode,
    NVL(PROFIT_FED_TAXES,0),
    NVL(PROFIT_STATE_TAXES,0),
    CASE
        WHEN PROFIT_TAX_CODE = ' ' THEN NULL
        ELSE PROFIT_TAX_CODE
    END as ptcode,
    PR_DET_S_SEC_NUMBER,
    PROFIT_DET_PR_DET_S_SEQNUM,
    PROFIT_MDTE,
    CASE
         WHEN TRIM(PROFIT_CMNT) = '' THEN NULL
         ELSE PROFIT_CMNT           
    END as pcmnt,
    CASE 
        WHEN TO_NUMBER(PROFIT_YDTE) >= 59 THEN '19' || PROFIT_YDTE
        ELSE '20' || PROFIT_YDTE
    END AS FOUR_DIGIT_YEAR,
    CASE WHEN SUBSTR(PROFIT_CMNT,1,5) = 'XFER<'
         THEN 1 ELSE 0 
    END AS IS_TRANSFER_IN,
    CASE WHEN SUBSTR(PROFIT_CMNT,1,5) = 'XFER>'
         THEN 1 ELSE 0 
    END AS IS_TRANSFER_OUT,
    CASE WHEN SUBSTR(PROFIT_CMNT,1,4) = 'XFER'
    	THEN SUBSTR(PROFIT_CMNT,6) ELSE NULL
    END AS TRANSFER_PSN 
FROM PROFITSHARE.PROFIT_DETAIL;

-----------------THIS IS THE OTHER TABLE THAT ALSO GOES TO PROFIT_DETAIL----------------
-- DO NOT TRUNCATE TABLE

 INSERT INTO PROFIT_DETAIL
   (PROFIT_YEAR,
    PROFIT_YEAR_ITERATION,
    PROFIT_CODE_ID,
    CONTRIBUTION,
    EARNINGS,
    FORFEITURE,
    ZERO_CONTRIBUTION_REASON_ID,
    FEDERAL_TAXES,
    STATE_TAXES,
    TAX_CODE_ID,
    SSN,
    DISTRIBUTION_SEQUENCE,
    MONTH_TO_DATE,
    REMARK,
    YEAR_TO_DATE,
    IS_TRANSFER_IN,
    IS_TRANSFER_OUT,
    TRANSFER_PSN)
SELECT
    TRUNC(PROFIT_SS_YEAR),
    MOD(PROFIT_SS_YEAR * 10, 10),
    PROFIT_SS_CODE,
    PROFIT_SS_CONT,
    PROFIT_SS_EARN,
    PROFIT_SS_FORT,
    CASE
         WHEN PROFIT_SS_ZEROCONT = ' ' THEN NULL
         ELSE PROFIT_SS_ZEROCONT
    END as Zcode,
    NVL(PROFIT_SS_FED_TAXES,0),
    NVL(PROFIT_SS_STATE_TAXES,0),
    CASE
        WHEN PROFIT_SS_TAX_CODE = ' ' THEN NULL
        ELSE PROFIT_SS_TAX_CODE
    END as ptcode,
    PR_SS_D_S_SEC_NUMBER,
    PROFIT_SS_DET_PR_SS_D_S_SEQNUM,
    PROFIT_SS_MDTE,
    CASE
         WHEN TRIM(PROFIT_SS_CMNT) = '' THEN NULL
         ELSE PROFIT_SS_CMNT           
    END as pcmnt,
    CASE 
        WHEN TO_NUMBER(PROFIT_SS_YDTE) >= 59 THEN '19' || PROFIT_SS_YDTE
        ELSE '20' || PROFIT_SS_YDTE
    END AS FOUR_DIGIT_YEAR,
    CASE WHEN SUBSTR(PROFIT_SS_CMNT,1,5) = 'XFER<'
         THEN 1 ELSE 0 
    END AS IS_TRANSFER_IN,
    CASE WHEN SUBSTR(PROFIT_SS_CMNT,1,5) = 'XFER>'
         THEN 1 ELSE 0 
    END AS IS_TRANSFER_OUT,
    CASE WHEN SUBSTR(PROFIT_SS_CMNT,1,4) = 'XFER'
    	THEN SUBSTR(PROFIT_SS_CMNT,6) ELSE NULL
    END AS TRANSFER_PSN 
FROM PROFITSHARE.PROFIT_SS_DETAIL;
