-- FIRST EMPTY OUT THE TABLE
TRUNCATE TABLE BENEFICIARY;

INSERT INTO BENEFICIARY
   (PSN,
    SSN,
    FIRST_NAME,
    LAST_NAME,
    DATE_OF_BIRTH,
    STREET,
    CITY,
    STATE,
    POSTAL_CODE,
    KIND_ID,
    AMOUNT,
    DISTRIBUTION,
    EARNINGS,
    SECONDARY_EARNINGS,
    PERCENT,
    RELATIONSHIP)
SELECT
    PYBEN.PYBEN_PSN,     
    PYBEN.PYBEN_PAYSSN,
    SUBSTR(PYBEN.PYBEN_NAME, INSTR(PYBEN.PYBEN_NAME, ', ') + 2) AS FIRSTNAME,
    SUBSTR(PYBEN.PYBEN_NAME, 1, INSTR(PYBEN.PYBEN_NAME, ',') - 1) AS LASTNAME,
    CASE
            WHEN LENGTH(PYBEN.PYBEN_DOBIRTH) = 8
                AND TO_NUMBER(SUBSTR(PYBEN.PYBEN_DOBIRTH, 5, 2)) BETWEEN 1 AND 12
                AND (
                    (TO_NUMBER(SUBSTR(PYBEN.PYBEN_DOBIRTH, 5, 2)) IN (1, 3, 5, 7, 8, 10, 12) AND TO_NUMBER(SUBSTR(PYBEN.PYBEN_DOBIRTH, 7, 2)) BETWEEN 1 AND 31) OR
                    (TO_NUMBER(SUBSTR(PYBEN.PYBEN_DOBIRTH, 5, 2)) IN (4, 6, 9, 11) AND TO_NUMBER(SUBSTR(PYBEN.PYBEN_DOBIRTH, 7, 2)) BETWEEN 1 AND 30) OR
                    (TO_NUMBER(SUBSTR(PYBEN.PYBEN_DOBIRTH, 5, 2)) = 2 AND TO_NUMBER(SUBSTR(PYBEN.PYBEN_DOBIRTH, 7, 2)) BETWEEN 1 AND 
                        CASE
                            WHEN MOD(TO_NUMBER(SUBSTR(PYBEN.PYBEN_DOBIRTH, 1, 4)), 400) = 0 OR (MOD(TO_NUMBER(SUBSTR(PYBEN.PYBEN_DOBIRTH, 1, 4)), 4) = 0 AND MOD(TO_NUMBER(SUBSTR(PYBEN.PYBEN_DOBIRTH, 1, 4)), 100) != 0)
                            THEN 29
                            ELSE 28
                        END
                    )
                )
            THEN TO_DATE(PYBEN.PYBEN_DOBIRTH, 'YYYYMMDD')
            ELSE DATE '1900-01-01'
    END AS converted_date,
    PYBEN.PYBEN_ADD,
    PYBEN.PYBEN_CITY,
    PYBEN.PYBEN_STATE,
    PYBEN.PYBEN_ZIP,
    CASE 
            WHEN PAYREL.PYREL_TYPE = ' ' THEN NULL
            ELSE PAYREL.PYREL_TYPE
    END AS KIND_ID,     
    PYBEN.PYBEN_PSAMT,
    PYBEN.PYBEN_PSDISB,
    PYBEN.PYBEN_PROF_EARN,
    PYBEN.PYBEN_PROF_EARN2,
    PAYREL.PYREL_PERCENT AS PERCENT,
    PAYREL.PYREL_RELATION AS RELATION
FROM PROFITSHARE.PAYBEN PYBEN
LEFT JOIN PROFITSHARE.PAYREL ON PYBEN.PYBEN_PSN = PAYREL.PYREL_PSN;