
-- FIRST EMPTY OUT THE TABLE
TRUNCATE TABLE DISTRIBUTION;

--LOAD DISTRIBUTION TABLE TO - "YOUR CURRENT SCHEMA" FROM - PROFITSHARE
INSERT INTO DISTRIBUTION
   (SSN,
     PAYMENT_SEQUENCE,
    EMPLOYEE_NAME,
    FREQUENCY_ID,
    STATUS_ID,
    PAYEE_ID, 
    THIRD_PARTY_PAYEE_ID,
    FORTHEBENEFITOF_PAYEE,
    FORTHEBENEFITOF_ACCOUNT_TYPE,
    TAX1099_FOR_EMPLOYEE,
    TAX1099_FOR_BENEFICIARY,
    FEDERAL_TAX_PERCENTAGE,
    STATE_TAX_PERCENTAGE,
    GROSS_AMOUNT,
    FEDERAL_TAX_AMOUNT,
    STATE_TAX_AMOUNT,
    CHECK_AMOUNT,
    TAX_CODE_ID,
    DECEASED,
    GENDER_ID,
    QDRO,
    MEMO,
    ROTH_IRA)
SELECT
    PROFDIST_SSN,
     PROFDIST_PAYSEQ,
    PROFDIST_EMPNAME,
    PROFDIST_PAYFREQ,
    PROFDIST_PAYFLAG,
    
    -- Map to DISTRIBUTION_PAYEE table (using a subquery to fetch the correct PAYEE_ID)
    (SELECT ID FROM DISTRIBUTION_PAYEE 
     WHERE SSN = PROFDIST_PAYSSN 
       AND NAME = PROFDIST_PAYNAME
       AND STREET = PROFDIST_PAYADDR1),
    
    -- Map to DISTRIBUTION_THIRDPARTY_PAYEE table (using a subquery to fetch the correct THIRD_PARTY_PAYEE_ID)
    (SELECT ID FROM DISTRIBUTION_THIRDPARTY_PAYEE 
     WHERE SSN = PROFDIST_SSN 
       AND NAME = PROFDIST_3RDNAME
       AND STREET = PROFDIST_3RDADDR1),

    PROFDIST_FBOPAYTO,
    PROFDIST_FBOTYPE,
    CASE
         WHEN PROFDIST_1099_INFO_EMP = 'Y' THEN 1
         ELSE 0
    END as acode,
    CASE
         WHEN PROFDIST_OTHER_BENEFICIARY = 'Y' THEN 1
         ELSE 0
    END as bcode,
    PROFDIST_FEDPCT,
    PROFDIST_STATEPCT,
    PROFDIST_GROSSAMT,
    PROFDIST_FEDTAX,
    PROFDIST_STATETAX,
    PROFDIST_CHECKAMT,
    PROFDIST_TAXCODE,
     CASE
         WHEN PROFDIST_DECEASED = 'Y' THEN 1
         ELSE 0
    END as ccode,
    CASE
         WHEN PROFDIST_SEX = 'M' THEN 'M'
         WHEN PROFDIST_SEX ='F' THEN 'F'
           ELSE NULL
    END as psex,
    CASE
         WHEN PROFDIST_QDRO = 'Y' THEN 1
         ELSE 0
    END as dcode,
    PROFDIST_MEMO,
    CASE
         WHEN PROFDIST_ROTH_IRA = 'Y' THEN 1
         ELSE 0
    END as ecode
FROM C##LEGACY.PROFDIST;

COMMIT;
