/*
    This script creates a table to store log messages generated by the other scripts. 
*/

CREATE TABLE LOG_MESSAGES (
    MESSAGE_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    CALLER VARCHAR2(60) NOT NULL,
    SQL_ERROR_CODE NUMBER,
    ERROR_MESSAGE VARCHAR2(512),
    ADDITIONAL_INFORMATION VARCHAR2(512),
    CREATED_ON DATE NOT NULL,
    PRIMARY KEY(MESSAGE_ID)
);

/*
    drop table log_messages;
*/