/*

This script creates :
- two temporary tables
- supporting indexes on them
- sequences to quickly generate replacement SSN and PSNs

The first has original and replacement SSNs, the fields (yes/no values) 
in other tables where the SSNs need to be updated with the new value, 
address fields that need to accompany the SSN in some tables, and a DONE 
flag when the row is completed.

The second for original and replacement PSNs, the fields (yes/no values) 
in other tables where the PSNs need to be updated with the new value, 
address fields that need to accompany the PSN in some tables, and a DONE 
flag when the row is completed.

One important thing for the first table is that either the DEMOGRAPHICS_SSN
or PYBEN_PAYSSN is populated.  This indicates whether we are working with 
an employee or beneficiary SSN. That is necessary to know when doing the changes.

Similarly, the second table has two PSN columns to differentiate between 
employees and beneficiaries.

Note that there is address information for each row. This is so that
when a table is altered for SSN, that the previously obfuscated 
address can be used there also.

NOTE: It matters what the ranges are for SSN and PSN replacements, determined by the sequences we create. Other values may conflict and 
cause uniqueness problems in existing or replacement data. So, for SSN 
the numbers in the 7xx -> range were never used after the 1930s, and 
no living person will have one in there.

These sequences mean that when SSN_TASKS and PSN_TASKS rows are created, 
there is no need to add in replacement PSNs or SSNs, they are created by 
the table automatically.

*/

-- Create dedicated field range for obfuscated SSNs
CREATE SEQUENCE SSN_REPL START WITH 700000001;

-- Dedicated range for PSNs
CREATE SEQUENCE PSN_REPL START WITH 7000000;  

-- Dedicated range for disconnected PSNs
CREATE SEQUENCE PSN_RANDOM START WITH 9000000;  

-- Create sequence for obfuscated check numbers
CREATE SEQUENCE CHECK_REPL START WITH 888000;

CREATE TABLE SSN_TASKS (
    TASK_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    DEMOGRAPHICS_SSN NUMBER(9),
    PYBEN_PAYSSN NUMBER(9),
    EMP_NAME VARCHAR(50),
    BEN_NAME VARCHAR(50),
    REPLACEMENT_SSN NUMBER(9) DEFAULT SSN_REPL.NEXTVAL,
    PROFDIST_SSN VARCHAR(1),
    PROFDIST_PAYSSN VARCHAR(1),
    PROFIT_SHARE_CHECKS_EMPLOYEE_SSN VARCHAR(1),
    PROFIT_SHARE_CHECKS_SSN_NUMBER VARCHAR(1),
    PAYBEN_PYBEN_PAYSSN VARCHAR(1),
    PAYREL_PAYSSN VARCHAR(1),
    PROFIT_DETAIL_PR_DET_S_SEC_NUMBER VARCHAR(1),
    PR_SS_D_S_SEC_NUMBER VARCHAR(1),
    PAYPROFIT_SSN VARCHAR(1),
    SOC_SEC_SSN VARCHAR(1),
    NEW_ADDRESS VARCHAR(30),
    NEW_CITY VARCHAR(30),
    NEW_STATE VARCHAR(2),
    NEW_ZIP NUMBER(5, 0),
    DONE NUMBER(1) DEFAULT 0
);

COMMIT;

DROP INDEX SSN_TEMP_KEYS_DONE_I;
DROP INDEX SSN_TEMP_KEYS_PYBEN_PAYSSN_I;
-- Bitmap indexes are better when there are few potential values
CREATE BITMAP INDEX SSN_TEMP_KEYS_DONE_I ON SSN_TASKS (DONE );
CREATE INDEX SSN_TEMP_KEYS_PYBEN_PAYSSN_I ON SSN_TASKS ( PYBEN_PAYSSN, DONE );


CREATE TABLE PSN_TASKS (
    TASK_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    DEMOGRAPHICS_PSN NUMBER(7),
    PAYBEN_PSN NUMBER(11),
    REPLACEMENT_PSN NUMBER(7) DEFAULT PSN_REPL.NEXTVAL,
    REPLACEMENT_BEN_PSN NUMBER(11),
    PAYREL_PSN VARCHAR(1),
    PROF_DIST_REQ_PSN VARCHAR(1),
    PROF_DIST_REQ_EMP VARCHAR(1),
    --PROFIT_SHARE_CHECKS_EMPLOYEE_NUMBER VARCHAR(1),
    PAYPROFIT_PSN VARCHAR(1),
    PROFIT_CMNT_PSN VARCHAR(1),
    PROFIT_SS_CMNT_PSN VARCHAR(1),
    DONE NUMBER(1) DEFAULT 0
);

COMMIT;

DROP INDEX PSN_TEMP_KEYS_DONE_I;
DROP INDEX PSN_TEMP_KEYS_PAYBEN_PSN_I;
-- Bitmap indexes are better when there are few potential values
CREATE BITMAP INDEX PSN_TEMP_KEYS_DONE_I ON PSN_TASKS (DONE );
CREATE INDEX PSN_TEMP_KEYS_PAYBEN_PSN_I ON PSN_TASKS ( PAYBEN_PSN, DONE );

COMMIT;
/*

drop table ssn_tasks;
drop table psn_tasks;
drop sequence ssn_repl;
drop sequence psn_repl;

*/

