create table "__EFMigrationsHistory"
(
    MIGRATIONID    NVARCHAR2(150) not null
        constraint PK___EFMIGRATIONSHISTORY
            primary key,
    PRODUCTVERSION NVARCHAR2(32)  not null
)
/

create table BENEFICIARY_TYPE
(
    ID   NUMBER(3)     not null
        constraint ID
            primary key,
    NAME NVARCHAR2(20) not null
)
/

create table CALDAR_RECORD
(
    ACC_WKEND_N      NUMBER(10) not null
        constraint PK_CALDAR_RECORD
            primary key,
    ACC_WKEND2_N     NUMBER(10) not null,
    ACC_APWKEND      NUMBER(10) not null,
    ACC_WEEKN        NUMBER(10),
    ACC_PERIOD       NUMBER(10),
    ACC_QUARTER      NUMBER(10),
    ACC_CALPERIOD    NUMBER(10),
    ACC_CLN60_WEEK   NUMBER(10),
    ACC_CLN60_PERIOD NUMBER(10),
    ACC_CLN61_WEEK   NUMBER(10),
    ACC_CLN61_PERIOD NUMBER(10),
    ACC_CLN7X_WEEK   NUMBER(10),
    ACC_CLN7X_PERIOD NUMBER(10),
    ACC_CLN6X_WEEK   NUMBER(10),
    ACC_CLN6X_PERIOD NUMBER(10),
    ACC_ALT_KEY_NUM  NUMBER(19)
)
/

create unique index CALDAR_RECORD_ACC_APWKEND_N
    on CALDAR_RECORD (ACC_APWKEND)
/

create unique index CALDAR_RECORD_ACC_WEDATE2
    on CALDAR_RECORD (ACC_WKEND2_N)
/

create table COUNTRY
(
    ISO            NVARCHAR2(2)   not null
        constraint PK_COUNTRY
            primary key,
    ID             NUMBER(3)      not null,
    NAME           NVARCHAR2(100) not null,
    TELEPHONE_CODE NVARCHAR2(10)  not null
)
/

create table DEMOGRAPHIC_SYNC_AUDIT
(
    ID            NUMBER(19) generated by default on null as identity
        constraint PK_DEMOGRAPHIC_SYNC_AUDIT
            primary key,
    BADGE_NUMBER  NUMBER(7)      not null,
    INVALID_VALUE NVARCHAR2(256),
    USERNAME      NVARCHAR2(96),
    PROPERTY_NAME NVARCHAR2(128),
    MESSAGE       NVARCHAR2(512) not null,
    CREATED       DATE           not null
)
/

create index IX_DEMOGRAPHIC_SYNC_AUDIT_BADGENUMBER
    on DEMOGRAPHIC_SYNC_AUDIT (BADGE_NUMBER)
/

create table DEPARTMENT
(
    ID   NUMBER(3)     not null
        constraint PK_DEPARTMENT
            primary key,
    NAME NVARCHAR2(64) not null
)
/

create table DISTRIBUTION_FREQUENCY
(
    ID   NVARCHAR2(1)  not null
        constraint PK_DISTRIBUTION_FREQUENCY
            primary key,
    NAME NVARCHAR2(20) not null
)
/

create table DISTRIBUTION_STATUS
(
    ID   NVARCHAR2(1)   not null
        constraint PK_DISTRIBUTION_STATUS
            primary key,
    NAME NVARCHAR2(100) not null
)
/

create table DISTRIBUTIONREQUESTREASON
(
    ID   NUMBER(3)       not null
        constraint PK_DISTRIBUTIONREQUESTREASON
            primary key,
    NAME NVARCHAR2(2000) not null
)
/

create table DISTRIBUTIONREQUESTSTATUS
(
    ID   NVARCHAR2(1)    not null
        constraint PK_DISTRIBUTIONREQUESTSTATUS
            primary key,
    NAME NVARCHAR2(2000) not null
)
/

create table DISTRIBUTIONREQUESTTYPE
(
    ID   NUMBER(3)       not null
        constraint PK_DISTRIBUTIONREQUESTTYPE
            primary key,
    NAME NVARCHAR2(2000) not null
)
/

create table EMPLOYEE_TYPE
(
    ID   NUMBER(3)     not null
        constraint PK_EMPLOYEE_TYPE
            primary key,
    NAME NVARCHAR2(30) not null
)
/

create table EMPLOYMENT_STATUS
(
    ID   NVARCHAR2(1)  not null
        constraint PK_EMPLOYMENT_STATUS
            primary key,
    NAME NVARCHAR2(20) not null
)
/

create table EMPLOYMENT_TYPE
(
    ID   NVARCHAR2(1)  not null
        constraint PK_EMPLOYMENT_TYPE
            primary key,
    NAME NVARCHAR2(64) not null
)
/

create table ENROLLMENT
(
    ID   NUMBER(3)     not null
        constraint PK_ENROLLMENT
            primary key,
    NAME NVARCHAR2(84) not null
)
/

create table GENDER
(
    ID   NVARCHAR2(1)  not null
        constraint PK_GENDER
            primary key,
    NAME NVARCHAR2(64) not null
)
/

create table JOBSTARTMETHOD
(
    ID   NUMBER(3)     not null
        constraint PK_JOBSTARTMETHOD
            primary key,
    NAME NVARCHAR2(30) not null
)
/

create table JOBSTATUS
(
    ID   NUMBER(3)     not null
        constraint PK_JOBSTATUS
            primary key,
    NAME NVARCHAR2(30) not null
)
/

create table JOBTYPE
(
    ID   NUMBER(3)     not null
        constraint PK_JOBTYPE
            primary key,
    NAME NVARCHAR2(30) not null
)
/

create table PAY_CLASSIFICATION
(
    ID   NUMBER(2)     not null
        constraint PK_PAY_CLASSIFICATION
            primary key,
    NAME NVARCHAR2(64) not null
)
/

comment on column PAY_CLASSIFICATION.NAME is ' P a y   C l a s s i f i c a t i o n'
/

create table PAY_FREQUENCY
(
    ID   NUMBER(3)     not null
        constraint PK_PAY_FREQUENCY
            primary key,
    NAME NVARCHAR2(64) not null
)
/

create table PROFIT_CODE
(
    ID        NUMBER(3)      not null
        constraint PK_PROFIT_CODE
            primary key,
    NAME      NVARCHAR2(128) not null,
    FREQUENCY NVARCHAR2(128) not null
)
/

create table STATE_TAX
(
    ABBREVIATION  NVARCHAR2(2)  not null
        constraint PK_STATE_TAX
            primary key,
    RATE          NUMBER(9, 2)  not null,
    USER_MODIFIED NVARCHAR2(20) not null,
    DATE_MODIFIED DATE          not null
)
/

create table TAX_CODE
(
    CODE        NVARCHAR2(1)   not null
        constraint PK_TAX_CODE
            primary key,
    DESCRIPTION NVARCHAR2(128) not null
)
/

create table TERMINATION_CODE
(
    ID   NVARCHAR2(1)  not null
        constraint PK_TERMINATION_CODE
            primary key,
    NAME NVARCHAR2(64) not null
)
/

create table ZERO_CONTRIBUTION_REASON
(
    ID   NUMBER(3)      not null
        constraint PK_ZERO_CONTRIBUTION_REASON
            primary key,
    NAME NVARCHAR2(100) not null
)
/

create table BENEFICIARY_CONTACT
(
    ID            NUMBER(10)   default "C##PROFIT"."ISEQ$$_135488".nextval generated by default on null as identity
		constraint PK_BENEFICIARY_CONTACT
			primary key,
    SSN           NUMBER(9)                      not null,
    FIRST_NAME    NVARCHAR2(30)                  not null,
    MIDDLE_NAME   NVARCHAR2(30),
    LAST_NAME     NVARCHAR2(30)                  not null,
    DATE_OF_BIRTH DATE                           not null,
    STREET        NVARCHAR2(30)                  not null,
    STREET2       NVARCHAR2(30),
    STREET3       NVARCHAR2(30),
    STREET4       NVARCHAR2(30),
    CITY          NVARCHAR2(25)                  not null,
    STATE         NVARCHAR2(3)                   not null,
    POSTAL_CODE   NVARCHAR2(9)                   not null,
    COUNTRY_ISO   NVARCHAR2(2) default N'US'
        constraint FK_BENEFICIARY_CONTACT_COUNTRY_COUNTRY_ISO
            references COUNTRY,
    PHONE_NUMBER  NVARCHAR2(16),
    MOBILE_NUMBER NVARCHAR2(16),
    EMAIL_ADDRESS NVARCHAR2(64),
    CREATED_DATE  DATE         default (SYSDATE) not null
)
/

comment on column BENEFICIARY_CONTACT.STREET is ' S t r e e t'
/

comment on column BENEFICIARY_CONTACT.STREET2 is ' S t r e e t 2'
/

comment on column BENEFICIARY_CONTACT.STREET3 is ' S t r e e t 3'
/

comment on column BENEFICIARY_CONTACT.STREET4 is ' S t r e e t 4'
/

comment on column BENEFICIARY_CONTACT.CITY is ' C i t y'
/

comment on column BENEFICIARY_CONTACT.STATE is ' S t a t e'
/

comment on column BENEFICIARY_CONTACT.POSTAL_CODE is ' P o s t a l   C o d e'
/

create index IX_BENEFICIARY_CONTACT_COUNTRY_ISO
    on BENEFICIARY_CONTACT (COUNTRY_ISO)
/

create index IX_BENEFICIARY_CONTACT_SSN
    on BENEFICIARY_CONTACT (SSN)
/

create table DISTRIBUTION_PAYEE
(
    ID          NUMBER(10)   default "C##PROFIT"."ISEQ$$_135491".nextval generated by default on null as identity
		constraint PK_DISTRIBUTION_PAYEE
			primary key,
    SSN         NUMBER(9)     not null,
    NAME        NVARCHAR2(84) not null,
    STREET      NVARCHAR2(30) not null,
    STREET2     NVARCHAR2(30),
    STREET3     NVARCHAR2(30),
    STREET4     NVARCHAR2(30),
    CITY        NVARCHAR2(25),
    STATE       NVARCHAR2(3),
    POSTAL_CODE NVARCHAR2(9),
    COUNTRY_ISO NVARCHAR2(2) default N'US'
        constraint FK_DISTRIBUTION_PAYEE_COUNTRY_COUNTRY_ISO
            references COUNTRY,
    MEMO        NVARCHAR2(128)
)
/

create index IX_DISTRIBUTION_PAYEE_COUNTRY_ISO
    on DISTRIBUTION_PAYEE (COUNTRY_ISO)
/

create index IX_DISTRIBUTION_PAYEE_SSN
    on DISTRIBUTION_PAYEE (SSN)
/

create table DISTRIBUTION_THIRDPARTY_PAYEE
(
    ID          NUMBER(10)   default "C##PROFIT"."ISEQ$$_135494".nextval generated by default on null as identity
		constraint PK_DISTRIBUTION_THIRDPARTY_PAYEE
			primary key,
    PAYEE       NVARCHAR2(64),
    NAME        NVARCHAR2(84),
    ACCOUNT     NVARCHAR2(30),
    STREET      NVARCHAR2(30) not null,
    STREET2     NVARCHAR2(30),
    STREET3     NVARCHAR2(30),
    STREET4     NVARCHAR2(30),
    CITY        NVARCHAR2(25),
    STATE       NVARCHAR2(3),
    POSTAL_CODE NVARCHAR2(9),
    COUNTRY_ISO NVARCHAR2(2) default N'US'
        constraint FK_DISTRIBUTION_THIRDPARTY_PAYEE_COUNTRY_COUNTRY_ISO
            references COUNTRY,
    MEMO        NVARCHAR2(128)
)
/

create index IX_DISTRIBUTION_THIRDPARTY_PAYEE_COUNTRY_ISO
    on DISTRIBUTION_THIRDPARTY_PAYEE (COUNTRY_ISO)
/

create table JOB
(
    ID            NUMBER(10) generated by default on null as identity
        constraint PK_JOB
            primary key,
    JOBTYPEID     NUMBER(3)     not null
        constraint FK_JOB_JOBTYPE_JOBTYPEID
            references JOBTYPE,
    STARTMETHODID NUMBER(3)     not null
        constraint FK_JOB_JOBSTARTMETHOD_STARTMETHODID
            references JOBSTARTMETHOD,
    REQUESTEDBY   NVARCHAR2(30) not null,
    JOBSTATUSID   NUMBER(3)     not null
        constraint FK_JOB_JOBSTATUS_JOBSTATUSID
            references JOBSTATUS,
    STARTED       DATE          not null,
    COMPLETED     DATE
)
/

create index IX_JOB_JOBSTATUSID
    on JOB (JOBSTATUSID)
/

create index IX_JOB_JOBTYPEID
    on JOB (JOBTYPEID)
/

create index IX_JOB_STARTMETHODID
    on JOB (STARTMETHODID)
/

create table DISTRIBUTION_REQUEST
(
    ID                NUMBER(19) generated by default on null as identity
        constraint PK_DISTRIBUTION_REQUEST
            primary key,
    PSN               NUMBER(11)    not null,
    REASON_ID         NUMBER(3)     not null
        constraint FK_DISTRIBUTION_REQUEST_DISTRIBUTIONREQUESTREASON_REASONID
            references DISTRIBUTIONREQUESTREASON,
    STATUS_ID         NVARCHAR2(1)  not null
        constraint FK_DISTRIBUTION_REQUEST_DISTRIBUTIONREQUESTSTATUS_STATUSID
            references DISTRIBUTIONREQUESTSTATUS,
    TYPE_ID           NUMBER(3)     not null
        constraint FK_DISTRIBUTION_REQUEST_DISTRIBUTIONREQUESTTYPE_TYPEID
            references DISTRIBUTIONREQUESTTYPE,
    REASON_TEXT       NVARCHAR2(250),
    REASON_OTHER      NVARCHAR2(500),
    AMOUNT_REQUESTED  NUMBER(10, 2) not null,
    AMOUNT_AUTHORIZED NUMBER(10, 2),
    DATE_REQUESTED    DATE          not null,
    DATE_DECIDED      DATE,
    TAXCODECODE       NVARCHAR2(1)  not null
        constraint FK_DISTRIBUTION_REQUEST_TAXCODES_TAXCODECODE
            references TAX_CODE
)
/

create index IX_DISTRIBUTION_REQUEST_REASONID
    on DISTRIBUTION_REQUEST (REASON_ID)
/

create index IX_DISTRIBUTION_REQUEST_STATUSID
    on DISTRIBUTION_REQUEST (STATUS_ID)
/

create index IX_DISTRIBUTION_REQUEST_TAXCODECODE
    on DISTRIBUTION_REQUEST (TAXCODECODE)
/

create index IX_DISTRIBUTION_REQUEST_TYPEID
    on DISTRIBUTION_REQUEST (TYPE_ID)
/

create table DEMOGRAPHIC
(
    ORACLE_HCM_ID         NUMBER(15)                     not null
        constraint PK_DEMOGRAPHIC
            primary key,
    SSN                   NUMBER(9)                      not null,
    BADGE_NUMBER          NUMBER(7)                      not null,
    LAST_MODIFIED_DATE    DATE         default (SYSDATE) not null,
    FULL_NAME             NVARCHAR2(84)                  not null,
    LAST_NAME             NVARCHAR2(30)                  not null,
    FIRST_NAME            NVARCHAR2(30)                  not null,
    MIDDLE_NAME           NVARCHAR2(25),
    STORE_NUMBER          NUMBER(3)                      not null,
    PAY_CLASSIFICATION_ID NUMBER(2)                      not null
        constraint FK_DEMOGRAPHIC_PAYCLASSIFICATIONS_PAYCLASSIFICATIONID
            references PAY_CLASSIFICATION,
    PHONE_NUMBER          NVARCHAR2(15),
    MOBILE_NUMBER         NVARCHAR2(15),
    EMAIL_ADDRESS         NVARCHAR2(50),
    STREET                NVARCHAR2(30)                  not null,
    STREET2               NVARCHAR2(30),
    STREET3               NVARCHAR2(30),
    STREET4               NVARCHAR2(30),
    CITY                  NVARCHAR2(25)                  not null,
    STATE                 NVARCHAR2(3)                   not null,
    POSTAL_CODE           NVARCHAR2(9)                   not null,
    COUNTRY_ISO           NVARCHAR2(2) default N'US'
        constraint FK_DEMOGRAPHIC_COUNTRY_COUNTRY_ISO
            references COUNTRY,
    DATE_OF_BIRTH         DATE                           not null,
    FULL_TIME_DATE        DATE,
    HIRE_DATE             DATE                           not null,
    REHIRE_DATE           DATE,
    TERMINATION_DATE      DATE,
    DEPARTMENT            NUMBER(1)                      not null
        constraint FK_DEMOGRAPHIC_DEPARTMENT_DEPARTMENTID
            references DEPARTMENT,
    EMPLOYMENT_TYPE_ID    NVARCHAR2(2)                   not null
        constraint FK_DEMOGRAPHIC_EMPLOYMENTTYPE_EMPLOYMENTTYPEID
            references EMPLOYMENT_TYPE,
    GENDER_ID             NVARCHAR2(1)                   not null
        constraint FK_DEMOGRAPHIC_GENDER_GENDERID
            references GENDER,
    PAY_FREQUENCY_ID      NUMBER(3)                      not null
        constraint FK_DEMOGRAPHIC_PAYFREQUENCY_PAYFREQUENCYID
            references PAY_FREQUENCY,
    TERMINATION_CODE_ID   NVARCHAR2(1)
        constraint FK_DEMOGRAPHIC_TERMINATIONCODE_TERMINATIONCODEID
            references TERMINATION_CODE,
    EMPLOYMENT_STATUS_ID  NVARCHAR2(1)                   not null
        constraint FK_DEMOGRAPHIC_EMPLOYMENTSTATUS_EMPLOYMENTSTATUSID
            references EMPLOYMENT_STATUS
)
/

comment on column DEMOGRAPHIC.FULL_NAME is ' F u l l N a m e'
/

comment on column DEMOGRAPHIC.LAST_NAME is ' L a s t N a m e'
/

comment on column DEMOGRAPHIC.FIRST_NAME is ' F i r s t N a m e'
/

comment on column DEMOGRAPHIC.MIDDLE_NAME is ' M i d d l e N a m e'
/

comment on column DEMOGRAPHIC.STORE_NUMBER is ' S t o r e N u m b e r'
/

comment on column DEMOGRAPHIC.PAY_CLASSIFICATION_ID is ' P a y C l a s s i f i c a t i o n'
/

comment on column DEMOGRAPHIC.STREET is ' S t r e e t'
/

comment on column DEMOGRAPHIC.STREET2 is ' S t r e e t 2'
/

comment on column DEMOGRAPHIC.STREET3 is ' S t r e e t 3'
/

comment on column DEMOGRAPHIC.STREET4 is ' S t r e e t 4'
/

comment on column DEMOGRAPHIC.CITY is ' C i t y'
/

comment on column DEMOGRAPHIC.STATE is ' S t a t e'
/

comment on column DEMOGRAPHIC.POSTAL_CODE is ' P o s t a l   C o d e'
/

comment on column DEMOGRAPHIC.DATE_OF_BIRTH is ' D a t e O f B i r t h'
/

comment on column DEMOGRAPHIC.FULL_TIME_DATE is ' F u l l T i m e D a t e'
/

comment on column DEMOGRAPHIC.HIRE_DATE is ' H i r e D a t e'
/

comment on column DEMOGRAPHIC.REHIRE_DATE is ' R e H i r e D a t e'
/

comment on column DEMOGRAPHIC.TERMINATION_DATE is ' T e r m i n a t i o n D a t e'
/

comment on column DEMOGRAPHIC.DEPARTMENT is ' D e p a r t m e n t'
/

comment on column DEMOGRAPHIC.EMPLOYMENT_TYPE_ID is ' E m p l o y m e n t T y p e'
/

comment on column DEMOGRAPHIC.GENDER_ID is ' G e n d e r'
/

comment on column DEMOGRAPHIC.PAY_FREQUENCY_ID is ' P a y F r e q u e n c y'
/

comment on column DEMOGRAPHIC.TERMINATION_CODE_ID is ' T e r m i n a t i o n C o d e'
/

create index IX_DEMOGRAPHIC_BADGENUMBER
    on DEMOGRAPHIC (BADGE_NUMBER)
/

create index IX_DEMOGRAPHIC_COUNTRY_ISO
    on DEMOGRAPHIC (COUNTRY_ISO)
/

create index IX_DEMOGRAPHIC_DEPARTMENTID
    on DEMOGRAPHIC (DEPARTMENT)
/

create index IX_DEMOGRAPHIC_EMPLOYMENTSTATUSID
    on DEMOGRAPHIC (EMPLOYMENT_STATUS_ID)
/

create index IX_DEMOGRAPHIC_EMPLOYMENTTYPEID
    on DEMOGRAPHIC (EMPLOYMENT_TYPE_ID)
/

create index IX_DEMOGRAPHIC_GENDERID
    on DEMOGRAPHIC (GENDER_ID)
/

create index IX_DEMOGRAPHIC_PAYCLASSIFICATIONID
    on DEMOGRAPHIC (PAY_CLASSIFICATION_ID)
/

create index IX_DEMOGRAPHIC_PAYFREQUENCYID
    on DEMOGRAPHIC (PAY_FREQUENCY_ID)
/

create index IX_DEMOGRAPHIC_SSN
    on DEMOGRAPHIC (SSN)
/

create index IX_DEMOGRAPHIC_SSN_ORACLEHCMID
    on DEMOGRAPHIC (SSN, ORACLE_HCM_ID)
/

create index IX_DEMOGRAPHIC_TERMINATIONCODEID
    on DEMOGRAPHIC (TERMINATION_CODE_ID)
/

create table PROFIT_DETAIL
(
    ID                          NUMBER(10) default "C##PROFIT"."ISEQ$$_135505".nextval generated by default on null as identity
		constraint PK_PROFIT_DETAIL
			primary key,
    SSN                         NUMBER(9)            not null,
    PROFIT_YEAR                 NUMBER(5)            not null,
    PROFIT_YEAR_ITERATION       NUMBER(3)            not null,
    DISTRIBUTION_SEQUENCE       NUMBER(10)           not null,
    PROFIT_CODE_ID              NUMBER(3)            not null
        constraint FK_PROFIT_DETAIL_PROFIT_CODE_PROFITCODEID
            references PROFIT_CODE,
    CONTRIBUTION                NUMBER(9, 2)         not null,
    EARNINGS                    NUMBER(9, 2)         not null,
    FORFEITURE                  NUMBER(9, 2)         not null,
    MONTH_TO_DATE               NUMBER(2)            not null,
    YEAR_TO_DATE                NUMBER(4)            not null,
    REMARK                      NVARCHAR2(32),
    ZERO_CONTRIBUTION_REASON_ID NUMBER(3)
        constraint FK_PROFIT_DETAIL_ZEROCONTRIBUTIONREASON_ZEROCONTRIBUTIONREASONID
            references ZERO_CONTRIBUTION_REASON,
    FEDERAL_TAXES               NUMBER(9, 2)         not null,
    STATE_TAXES                 NUMBER(9, 2)         not null,
    TAX_CODE_ID                 NVARCHAR2(1)
        constraint FK_PROFIT_DETAIL_TAXCODES_TAX_CODE_ID
            references TAX_CODE,
    IS_TRANSFER_OUT             BOOLEAN    default 0 not null,
    IS_TRANSFER_IN              BOOLEAN    default 0 not null,
    TRANSFER_PSN                NUMBER(19)
)
/

create index IX_PROFIT_DETAIL_PROFITCODEID
    on PROFIT_DETAIL (PROFIT_CODE_ID)
/

create index IX_PROFIT_DETAIL_SSN_DISTRIBUTIONSEQUENCE_PROFITYEAR
    on PROFIT_DETAIL (SSN, DISTRIBUTION_SEQUENCE, PROFIT_YEAR)
/

create index IX_PROFIT_DETAIL_TAXCODEID
    on PROFIT_DETAIL (TAX_CODE_ID)
/

create index IX_PROFIT_DETAIL_ZEROCONTRIBUTIONREASONID
    on PROFIT_DETAIL (ZERO_CONTRIBUTION_REASON_ID)
/

create table DISTRIBUTION
(
    ID                           NUMBER(19) generated by default on null as identity
        constraint PK_DISTRIBUTION
            primary key,
    SSN                          NUMBER(9)     not null,
    PAYMENT_SEQUENCE             NUMBER(3)     not null,
    EMPLOYEE_NAME                NVARCHAR2(84) not null,
    FREQUENCY_ID                 NVARCHAR2(1)  not null
        constraint FK_DISTRIBUTION_DISTRIBUTION_FREQUENCY_FREQUENCYID
            references DISTRIBUTION_FREQUENCY,
    STATUS_ID                    NVARCHAR2(1)  not null
        constraint FK_DISTRIBUTION_DISTRIBUTIONSTATUSES_STATUSID
            references DISTRIBUTION_STATUS,
    PAYEE_ID                     NUMBER(10)
        constraint FK_DISTRIBUTION_DISTRIBUTIONPAYEE_PAYEEID
            references DISTRIBUTION_PAYEE,
    THIRD_PARTY_PAYEE_ID         NUMBER(10)
        constraint FK_DISTRIBUTION_DISTRIBUTIONTHIRDPARTYPAYEE_THIRDPARTYPAYEEID
            references DISTRIBUTION_THIRDPARTY_PAYEE,
    FORTHEBENEFITOF_PAYEE        NVARCHAR2(30),
    FORTHEBENEFITOF_ACCOUNT_TYPE NVARCHAR2(30),
    TAX1099_FOR_EMPLOYEE         NUMBER(1)     not null,
    TAX1099_FOR_BENEFICIARY      NUMBER(1)     not null,
    FEDERAL_TAX_PERCENTAGE       NUMBER(9, 2)  not null,
    STATE_TAX_PERCENTAGE         NUMBER(9, 2)  not null,
    GROSS_AMOUNT                 NUMBER(9, 2)  not null,
    FEDERAL_TAX_AMOUNT           NUMBER(9, 2)  not null,
    STATE_TAX_AMOUNT             NUMBER(9, 2)  not null,
    CHECK_AMOUNT                 NUMBER(9, 2)  not null,
    TAX_CODE_ID                  NVARCHAR2(1)  not null
        constraint FK_DISTRIBUTION_TAXCODES_TAX_CODE_ID
            references TAX_CODE,
    DECEASED                     NUMBER(1)     not null,
    GENDER_ID                    NVARCHAR2(1)
        constraint FK_DISTRIBUTION_GENDER_GENDERID
            references GENDER,
    QDRO                         NUMBER(1)     not null,
    MEMO                         NVARCHAR2(128),
    ROTH_IRA                     NUMBER(1)     not null
)
/

comment on column DISTRIBUTION.QDRO is ' Q u a l i f i e d   D o m e s t i c   R e l a t i o n s   O r d e r'
/

create index IX_DISTRIBUTION_FREQUENCYID
    on DISTRIBUTION (FREQUENCY_ID)
/

create index IX_DISTRIBUTION_GENDERID
    on DISTRIBUTION (GENDER_ID)
/

create index IX_DISTRIBUTION_PAYEEID
    on DISTRIBUTION (PAYEE_ID)
/

create unique index IX_DISTRIBUTION_SSN_PAYMENTSEQUENCE
    on DISTRIBUTION (SSN, PAYMENT_SEQUENCE)
/

create index IX_DISTRIBUTION_STATUSID
    on DISTRIBUTION (STATUS_ID)
/

create index IX_DISTRIBUTION_TAX_CODE_ID
    on DISTRIBUTION (TAX_CODE_ID)
/

create index IX_DISTRIBUTION_THIRDPARTYPAYEEID
    on DISTRIBUTION (THIRD_PARTY_PAYEE_ID)
/

create table BENEFICIARY
(
    ID                     NUMBER(10) generated by default on null as identity
        constraint PK_BENEFICIARY
            primary key,
    PSN_SUFFIX             NUMBER(5)    not null,
    BADGE_NUMBER           NUMBER(7)    not null,
    ORACLE_HCM_ID          NUMBER(15)   not null
        constraint FK_BENEFICIARY_DEMOGRAPHIC_ORACLE_HCM_ID
            references DEMOGRAPHIC,
    BENEFICIARY_CONTACT_ID NUMBER(10)   not null
        constraint FK_BENEFICIARY_BENEFICIARY_CONTACT_BENEFICIARYCONTACTID
            references BENEFICIARY_CONTACT,
    RELATIONSHIP           NVARCHAR2(10),
    DISTRIBUTION           NUMBER(9, 2) not null,
    AMOUNT                 NUMBER(9, 2) not null,
    EARNINGS               NUMBER(9, 2) not null,
    SECONDARY_EARNINGS     NUMBER(9, 2) not null,
    PERCENT                NUMBER(3)    not null
)
/

create index IX_BENEFICIARY_BADGENUMBER
    on BENEFICIARY (BADGE_NUMBER)
/

create index IX_BENEFICIARY_BENEFICIARYCONTACTID
    on BENEFICIARY (BENEFICIARY_CONTACT_ID)
/

create index IX_BENEFICIARY_ORACLE_HCM_ID
    on BENEFICIARY (ORACLE_HCM_ID)
/

create index IX_BENEFICIARY_PSNSUFFIX
    on BENEFICIARY (PSN_SUFFIX)
/

create table PAY_PROFIT
(
    ORACLE_HCM_ID               NUMBER(15)   not null
        constraint FK_PAY_PROFIT_DEMOGRAPHIC_ORACLEHCMID
            references DEMOGRAPHIC,
    PROFIT_YEAR                 NUMBER(4)    not null,
    CURRENT_HOURS_YEAR          NUMBER(6, 2) not null,
    CURRENT_INCOME_YEAR         NUMBER(9, 2) not null,
    EARNINGS_ETVA_VALUE         NUMBER(9, 2) not null,
    SECONDARY_EARNINGS          NUMBER(9, 2),
    SECONDARY_ETVA_EARNINGS     NUMBER(9, 2),
    WEEKS_WORKED_YEAR           NUMBER(2)    not null,
    PS_CERTIFICATE_ISSUED_DATE  DATE,
    ENROLLMENT_ID               NUMBER(3)    not null
        constraint FK_PAY_PROFIT_ENROLLMENT_ENROLLMENTID
            references ENROLLMENT,
    BENEFICIARY_TYPE_ID         NUMBER(3)    not null
        constraint FK_PAY_PROFIT_BENEFICIARY_TYPE_BENEFICIARYTYPEID
            references BENEFICIARY_TYPE,
    EMPLOYEE_TYPE_ID            NUMBER(3)    not null
        constraint FK_PAY_PROFIT_EMPLOYEE_TYPE_EMPLOYEETYPEID
            references EMPLOYEE_TYPE,
    ZERO_CONTRIBUTION_REASON_ID NUMBER(3)
        constraint FK_PAY_PROFIT_ZEROCONTRIBUTIONREASON_ZEROCONTRIBUTIONREASONID
            references ZERO_CONTRIBUTION_REASON,
    HOURS_EXECUTIVE             NUMBER(6, 2) not null,
    INCOME_EXECUTIVE            NUMBER(9, 2) not null,
    constraint PK_PAY_PROFIT
        primary key (ORACLE_HCM_ID, PROFIT_YEAR)
)
/

create index IX_PAY_PROFIT_BENEFICIARYTYPEID
    on PAY_PROFIT (BENEFICIARY_TYPE_ID)
/

create index IX_PAY_PROFIT_EMPLOYEETYPEID
    on PAY_PROFIT (EMPLOYEE_TYPE_ID)
/

create index IX_PAY_PROFIT_ENROLLMENTID
    on PAY_PROFIT (ENROLLMENT_ID)
/

create index IX_PAY_PROFIT_ZEROCONTRIBUTIONREASONID
    on PAY_PROFIT (ZERO_CONTRIBUTION_REASON_ID)
/

