-- PS-1829: Add computed FULL_NAME columns to avoid manual concatenation in services
-- Oracle is forcing Unicode literals - accept it and use NVARCHAR2 to match
-- This ensures character set compatibility

-- Drop and recreate DEMOGRAPHIC.FULL_NAME as computed column
ALTER TABLE DEMOGRAPHIC DROP COLUMN FULL_NAME;

ALTER TABLE DEMOGRAPHIC ADD (
    FULL_NAME NVARCHAR2(128) 
    AS (LAST_NAME || ', ' || FIRST_NAME || CASE WHEN MIDDLE_NAME IS NOT NULL THEN ' ' || SUBSTR(MIDDLE_NAME,1,1) ELSE NULL END)
);

-- Drop and recreate BENEFICIARY_CONTACT_ARCHIVE.FULL_NAME as computed column
ALTER TABLE BENEFICIARY_CONTACT_ARCHIVE DROP COLUMN FULL_NAME;

ALTER TABLE BENEFICIARY_CONTACT_ARCHIVE ADD (
    FULL_NAME NVARCHAR2(128) 
    AS (LAST_NAME || ', ' || FIRST_NAME || CASE WHEN MIDDLE_NAME IS NOT NULL THEN ' ' || SUBSTR(MIDDLE_NAME,1,1) ELSE NULL END)
);

-- Drop and recreate BENEFICIARY_CONTACT.FULL_NAME as computed column  
ALTER TABLE BENEFICIARY_CONTACT DROP COLUMN FULL_NAME;

ALTER TABLE BENEFICIARY_CONTACT ADD (
    FULL_NAME NVARCHAR2(128) 
    AS (LAST_NAME || ', ' || FIRST_NAME || CASE WHEN MIDDLE_NAME IS NOT NULL THEN ' ' || SUBSTR(MIDDLE_NAME,1,1) ELSE NULL END)
);

-- Verify the columns were created correctly (should show no U prefix)
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_DEFAULT
FROM USER_TAB_COLUMNS
WHERE COLUMN_NAME = 'FULL_NAME'
  AND TABLE_NAME IN ('DEMOGRAPHIC', 'BENEFICIARY_CONTACT_ARCHIVE', 'BENEFICIARY_CONTACT')
ORDER BY TABLE_NAME;
