BEGIN
DELETE FROM NAVIGATION_ASSIGNED_ROLES;
DELETE FROM NAVIGATION_TRACKING;
DELETE FROM NAVIGATION;
--Main menu
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(49,null, 'INQUIRIES', '','', 1, 10, '');
--Sub values for INQUIRIES
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(50,49, 'MASTER INQUIRY', '','master-inquiry', 1, 1, '');
--Main menu
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(51,null, 'BENEFICIARIES', '','', 1, 2, '');
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(52,null, 'DISTRIBUTIONS', '','', 1, 3, '');
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(53,null, 'RECONCILIATION', '','', 1, 4, '');
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(54,null, 'YEAR END', '','', 1, 5, '');
--December Activities
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(1,54, 'December Activities', '','December Activities', 1, 1, '');
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(2,1, 'Clean up Reports', '','', 1, 1, '');
--sub values for Clean up Reports
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(3,2, 'Demographic Badges Not In PayProfit', '','demographic-badges-not-in-payprofit', 1, 1, '');
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(4,2, 'Duplicate SSNs in Demographics', '','duplicate-ssns-demographics', 1, 2, '');
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(5,2, 'Negative ETVA', '','negative-etva-for-ssns-on-payprofit', 1, 3, '');
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(6,2, 'Duplicate Names and Birthdays', '','duplicate-names-and-birthdays', 1, 4, '');
--sub values for December Activities
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(7,1, 'Military Contributions', 'TPR008-13','military-entry-and-modification', 1, 2, '');
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(8,1, 'Rehire Forfeitures', 'QPREV-PROF','rehire-forfeitures', 1, 3, '');
--INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
--VALUES(9,1, 'Rehire Forfeitures', 'QPREV-PROF','rehire-forfeitures', 1, 4, '');
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(10,1, 'Distributions and Forfeitures', 'QPAY129','distributions-and-forfeitures', 1, 6, '');
--INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
--VALUES(11,1, 'Distributions and Forfeitures', 'QPAY129','distributions-and-forfeitures', 1, 7, '');
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(12,1, 'Terminations', 'QPAY066','prof-term', 1, 8, '');
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(13,1, 'Profit Share Report', 'PAY426','profit-share-report', 1, 9, '');
--Fiscal Close
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(14,54, 'Fiscal Close', '','Fiscal Close', 1, 2, '');
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(15,14, 'Manage Executive Hours and Dollars', 'TPR008-09','manage-executive-hours-and-dollars', 1, 1, '');
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(16,14, 'YTD Wages Extract', 'PROF-DOLLAR-EXTRACT','ytd-wages-extract', 1, 2, '');
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(17,14, 'Profit Share Report', 'PAY426','profit-share-report', 1, 3, '');
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(18,14, 'Profit Share Report Edit Run', 'PAY426N','', 1, 4, '');
--sub values for Profit Share Report Edit Run
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(19,18, 'Active/inactive employees age 18 - 20 with 1000 hours or more', '','pay426-1', 1, 1, '');
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(21,18, 'Active/inactive employees age 21 & with 1000 hours or more', '','pay426-2', 1, 2, '');
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(22,18, 'Active/inactive employees under 18', '','pay426-3', 1, 3, '');
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(23,18, 'Active/inactive employees 18 and older with prior profit sharing amounts and <1000 hours', '','pay426-4', 1, 4, '');
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(24,18, 'Active/inactive employees 18 and older with no prior profit sharing amounts and <1000 hours', '','pay426-5', 1, 5, '');
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(25,18, 'Terminated employees 18 and older with 1000 hours or more', '','pay426-6', 1, 6, '');
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(26,18, 'Terminated employees 18 and older with no prior profit sharing amounts and < 1000 hours', '','pay426-7', 1, 7, '');
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON)
VALUES(27,18, 'Terminated employees 18 and older with prior profit sharing amounts and < 1000 hours', '','pay426-8', 1, 8, '');
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(28,18, 'Profit sharing summary page', '','pay426-9', 1, 9, '');
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(29,18, 'All non-employee beneficiaries', '','pay426-10', 1, 10, '');
--sub values for Fiscal Close
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(30,14, 'Get Eligible Employees', 'GET-ELIGIBLE-EMPS','eligible-employees', 1, 5, '');
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(31,14, 'Forfeit', 'PAY443','forfeit', 1, 6, '');
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(32,14, 'Profit Share Updates', 'PAY444|PAY447','profit-share-update', 1, 7, '');
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(33,14, 'Reports by Age', '','', 1, 8, '');
--sub values for Report by Age
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(34,33, 'Get Contributions by Age', 'PROF130','contributions-by-age', 1, 1, '');
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(35,33, 'Get Distributions by Age', 'PROF130','distributions-by-age', 1, 2, '');
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(36,33, 'Get Forfeiture by Age', 'PROF130','forfeitures-by-age', 1, 3, '');
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(37,33, 'Get Balance by Age', 'PROF130B','balance-by-age', 1, 4, '');
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(38,33, 'Get Vested Amounts by Age', 'PROF130V','vested-amounts-by-age', 1, 5, '');
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(39,33, 'Get Balance by Years', 'PROF130Y','balance-by-years', 1, 6, '');
--sub values for Fiscal Close
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(40,14, 'Profit Share Gross Report', 'QPAY501','profit-share-gross-report', 1, 9, '');
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(41,14, 'Profit Share by Store', 'QPAY066TA','', 1, 9, '');
--sub values of Profit Share by Store
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(42,41, 'QPAY066-UNDR21', '','qpay066-under21', 1, 1, '');
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(43,41, 'QPAY066TA-UNDR21', '','qpay066ta-under21', 1, 2, '');
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(44,41, 'QPAY066TA', '','qpay066ta', 1, 3, '');
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(45,41, 'PROFALL Report', '','profall', 1, 4, '');
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(46,41, 'New Labels', 'QNEWPROFLBL','new-ps-labels', 1, 5, '');
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(47,41, 'PROFNEW', '','', 1, 6, '');
--sub value for Fiscal Close
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON) 
VALUES(48,14, 'Print Profit Certs', 'PAYCERT','', 1, 10, '');

END;
COMMIT;

