BEGIN
DELETE FROM NAVIGATION_ASSIGNED_ROLES;
DELETE FROM NAVIGATION_TRACKING;
DELETE FROM NAVIGATION;

-- UAT Navigation Data - Limited to December Activities, Unforfeit, Terminations, and Master Inquiry
-- This script includes only the initial UAT routes and can be extended over time

--Main menu - INQUIRIES (required for Master Inquiry)
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON, DISABLED) 
VALUES(50,null, 'INQUIRIES', '','', 1, 1, '', 0);

--Sub values for INQUIRIES
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON, DISABLED) 
VALUES(51,50, 'MASTER INQUIRY', '','master-inquiry', 1, 1, '', 0);

--Main menu - IT OPERATIONS
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON, DISABLED) 
VALUES(56,null, 'IT OPERATIONS', '','', 1, 6, '', 0);

--IT Operations sub-items
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON, DISABLED) 
VALUES(57,56, 'Demographic Freeze', '','demographic-freeze', 1, 1, '', 0);

--Main menu - YEAR END (required parent for December Activities)
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON, DISABLED) 
VALUES(55,null, 'YEAR END', '','', 1, 5, '', 0);

--December Activities (main container)
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON, DISABLED) 
VALUES(1,55, 'December Activities', '','december-process-accordion', 1, 1, '', 0);

--December Activities sub-items (UAT Phase 1)
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON, DISABLED) 
VALUES(8,1, 'UnForfeit', 'QPREV-PROF','unforfeitures', 1, 2, '', 0);

INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON, DISABLED) 
VALUES(9,1, 'Terminations', 'QPAY066','prof-term', 1, 4, '', 0);

--Clean up Reports (main container)
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON, DISABLED) 
VALUES(2,1, 'Clean up Reports', '','', 1, 1, '', 0);

--sub values for Clean up Reports
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON, DISABLED) 
VALUES(3,2, 'Demographic Badges Not In PayProfit', '','demographic-badges-not-in-payprofit', 1, 1, '', 0);

INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON, DISABLED) 
VALUES(4,2, 'Duplicate SSNs in Demographics', '','duplicate-ssns-demographics', 1, 2, '', 0);

INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON, DISABLED) 
VALUES(5,2, 'Negative ETVA', '','negative-etva-for-ssns-on-payprofit', 1, 3, '', 0);

INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON, DISABLED) 
VALUES(6,2, 'Duplicate Names and Birthdays', '','duplicate-names-and-birthdays', 1, 4, '', 0);

--Additional December Activities sub-items
INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON, DISABLED) 
VALUES(7,1, 'Military Contributions', '008-13','military-entry-and-modification', 1, 3, '', 0);

INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON, DISABLED) 
VALUES(10,1, 'Forfeitures', '008-12','forfeitures-adjustment', 1, 5, '', 0);

INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON, DISABLED) 
VALUES(11,1, 'Distributions and Forfeitures', 'QPAY129','distributions-and-forfeitures', 1, 6, '', 0);

INSERT INTO NAVIGATION(ID,PARENT_ID, TITLE, SUB_TITLE, URL, STATUS_ID, ORDER_NUMBER, ICON, DISABLED) 
VALUES(13,1, 'Profit Share Report', 'PAY426','profit-share-report', 1, 9, '', 0);

--Inserting value for IT Operation for role management
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (56,6 );

-- Assign roles for INQUIRIES (Master Inquiry -> CanRunMasterInquiry)
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (50,1 ); -- System-Administrator
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (50,2 ); -- Finance-Manager
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (50,3 ); -- Distributions-Clerk
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (50,4 ); -- Hardship-Administrator
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (50,6 ); -- IT-Operations

-- Assign roles for YEAR END (YearEndGroup -> CanViewYearEndReports)
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (55,1 ); -- System-Administrator
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (55,2 ); -- Finance-Manager
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (55,4 ); -- Hardship-Administrator
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (55,6 ); -- IT-Operations

-- Per-endpoint role assignments (UAT scope)
-- Master Inquiry
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (51,1 ); -- System-Administrator
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (51,2 ); -- Finance-Manager
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (51,3 ); -- Distributions-Clerk
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (51,4 ); -- Hardship-Administrator
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (51,6 ); -- IT-DevOps

-- IT Operations -> Demographic Freeze
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (57,6 ); -- IT-DevOps

-- December Activities container and children
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (1,1 );
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (1,2 );
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (1,4 );
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (1,6 );
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (2,1 );
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (2,2 );
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (2,4 );
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (2,6 );
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (3,1 );
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (3,2 );
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (3,4 );
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (3,6 );
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (4,1 );
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (4,2 );
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (4,4 );
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (4,6 );
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (5,1 );
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (5,2 );
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (5,4 );
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (5,6 );
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (6,1 );
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (6,2 );
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (6,4 );
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (6,6 );

-- December Activities items in UAT phase 1
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (7,1 );
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (7,2 );
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (7,4 );
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (7,6 );
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (8,1 );
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (8,2 );
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (8,4 );
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (8,6 );
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (9,1 );
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (9,2 );
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (9,4 );
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (9,6 );
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (10,1 );
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (10,2 );
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (10,4 );
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (10,6 );
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (11,1 );
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (11,2 );
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (11,4 );
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (11,6 );
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (13,1 );
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (13,2 );
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (13,4 );
INSERT INTO NAVIGATION_ASSIGNED_ROLES(NAVIGATIONID, REQUIREDROLESID) VALUES (13,6 );

END;
COMMIT ;
