using System.Security.Cryptography.X509Certificates;

namespace Demoulas.ProfitSharing.OracleHcm.Services.Interfaces;

/// <summary>
/// Service for generating JWT (JSON Web Token) tokens signed with an X509 certificate private key.
/// Used for Oracle HCM REST API authentication.
/// </summary>
/// <remarks>
/// JWT tokens are required for Oracle HCM API authentication in addition to mutual TLS (mTLS).
/// The token is signed with RS256 (RSA SHA-256) using the certificate's private key.
///
/// Token structure:
/// - Header: Contains algorithm (RS256), token type (JWT), and certificate thumbprint (x5t)
/// - Payload: Contains issuer, principal, issued-at time, and expiration time
/// - Signature: Generated by signing the header and payload with the certificate's private key
///
/// Reference: https://www.oracle.com/webfolder/technetwork/tutorials/obe/fusionapps/HCM/JWT_API_Authentication_OBE/html/index.html
/// </remarks>
public interface IJwtTokenService
{
    /// <summary>
    /// Generates a JWT token signed with the certificate's private key.
    /// </summary>
    /// <param name="certificate">The X509 certificate containing the private key for signing.</param>
    /// <param name="issuer">The issuer claim (e.g., "www.mycompany.com"). Required by Oracle HCM.</param>
    /// <param name="principal">The principal/username claim (e.g., "fusion"). Required by Oracle HCM.</param>
    /// <param name="expirationMinutes">Token expiration time in minutes from now. Default: 10 minutes.</param>
    /// <returns>A signed JWT token string ready for use in the Authorization header.</returns>
    /// <remarks>
    /// The generated token includes:
    /// - Header: RS256 algorithm, JWT type, x5t (SHA-1 thumbprint of certificate)
    /// - Payload: iss (issuer), prn (principal), iat (issued at), exp (expiration)
    /// - Signature: Signed with the certificate's private RSA key
    /// </remarks>
    string GenerateToken(X509Certificate2 certificate, string issuer, string principal, int expirationMinutes = 10);

    /// <summary>
    /// Generates a JWT token with the certificate issuer as the claim issuer.
    /// </summary>
    /// <param name="certificate">The X509 certificate containing the private key for signing.</param>
    /// <param name="expirationMinutes">Token expiration time in minutes from now. Default: 10 minutes.</param>
    /// <returns>A signed JWT token string ready for use in the Authorization header.</returns>
    /// <remarks>
    /// Uses the certificate subject's CN (Common Name) or L (Locality) as the issuer claim.
    /// Default Oracle HCM principal: "fusion"
    /// Example: For certificate with "CN = Demoulas Cloud Issuing CA 2",
    /// the token issuer claim will be "Demoulas Cloud Issuing CA 2"
    /// </remarks>
    string GenerateTokenWithDefaults(X509Certificate2 certificate, int expirationMinutes = 10);
}
