/*
    This script loads the distinct keys (SSN, PSN) from several tables into new temporary tables that have indexes to allow 
    much faster searching than if we tried to hit the original
    tables to figure out what keys are there.
*/

insert into DEMOGRAPHICS_SSN (ssn) 
select DISTINCT DEM_SSN from DEMOGRAPHICS WHERE DEM_SSN IS NOT NULL;

insert into PROFDIST_SSN (SSN)
select DISTINCT PROFDIST_SSN from PROFDIST WHERE PROFDIST_SSN IS NOT NULL;

insert into PROFDIST_PAYSSN (SSN)
select DISTINCT PROFDIST_PAYSSN from PROFDIST WHERE PROFDIST_PAYSSN IS NOT NULL;

insert into PS_CHECKS_SSN (SSN)
select DISTINCT SSN_NUMBER from PROFIT_SHARE_CHECKS WHERE SSN_NUMBER IS NOT NULL;

insert into PS_CHECKS_EMP_SSN (SSN)
select DISTINCT EMPLOYEE_SSN from PROFIT_SHARE_CHECKS WHERE EMPLOYEE_SSN IS NOT NULL;

insert into PROFIT_DETAIL_SSN (SSN)
select DISTINCT PR_DET_S_SEC_NUMBER from PROFIT_DETAIL WHERE PR_DET_S_SEC_NUMBER IS NOT NULL;

insert into PROFIT_SS_DETAIL_SSN (SSN)
select DISTINCT PR_SS_D_S_SEC_NUMBER from PROFIT_SS_DETAIL WHERE PR_SS_D_S_SEC_NUMBER IS NOT NULL;

insert into PYBEN_PAYSSN (SSN)
select DISTINCT PYBEN_PAYSSN from PAYBEN WHERE PYBEN_PAYSSN IS NOT NULL;

insert into PAYPROFIT_SSN (SSN)
select DISTINCT PAYPROF_SSN from PAYPROFIT WHERE PAYPROF_SSN IS NOT NULL;

insert into SOC_SEC_SSN (SSN)
select DISTINCT SOC_SEC_NUMBER from SOC_SEC_REC WHERE SOC_SEC_NUMBER IS NOT NULL;

insert into PYREL_PAYSSN (SSN)
select DISTINCT PYREL_PAYSSN from PAYREL WHERE PYREL_PAYSSN IS NOT NULL;

insert into DEMOGRAPHICS_PSN (PSN)
select DISTINCT DEM_BADGE from DEMOGRAPHICS WHERE DEM_BADGE IS NOT NULL;

insert into PAYBEN_PSN (PSN)
select DISTINCT PYBEN_PSN from PAYBEN WHERE PYBEN_PSN IS NOT NULL;

--insert into PS_CHECKS_EMP_NUM (PSN)
--select DISTINCT EMPLOYEE_NUMBER from PROFIT_SHARE_CHECKS;

insert into PROF_DIST_REQ_EMP (PSN)
select DISTINCT PROFIT_DIST_REQ_EMP from PROFIT_DIST_REQ WHERE PROFIT_DIST_REQ_EMP IS NOT NULL;

insert into PROF_DIST_REQ_PSN (PSN)
select DISTINCT PROFIT_DIST_REQ_PSN from PROFIT_DIST_REQ WHERE PROFIT_DIST_REQ_PSN IS NOT NULL;

insert into PYREL_PSN (PSN)
select DISTINCT PYREL_PSN from PAYREL WHERE PYREL_PSN IS NOT NULL;

insert into PAYPROFIT_PSN (PSN)
select DISTINCT PAYPROF_BADGE from PAYPROFIT WHERE PAYPROF_BADGE IS NOT NULL;

COMMIT;
