/*
    These tables and indexes are to store the unique SSN and 
    PSN values that occur in several tables in a way that they 
    can be accessed efficiently.

    Each table has just one row, either for SSNs or PSNs.
    
    There are also two tables to help randomize store numbers 
    for stores that have very few employees.
*/

CREATE TABLE DEMOGRAPHICS_SSN (SSN NUMBER(9));
CREATE TABLE PROFDIST_SSN (SSN NUMBER(9));
CREATE TABLE PROFDIST_PAYSSN (SSN NUMBER(9));
CREATE TABLE PS_CHECKS_SSN (SSN NUMBER(9));
CREATE TABLE PS_CHECKS_EMP_SSN (SSN NUMBER(9));
CREATE TABLE PROFIT_DETAIL_SSN (SSN NUMBER(9));
CREATE TABLE PROFIT_SS_DETAIL_SSN (SSN NUMBER(9));
CREATE TABLE PYBEN_PAYSSN (SSN NUMBER(9));
CREATE TABLE PYREL_PAYSSN (SSN NUMBER(9));
CREATE TABLE PAYPROFIT_SSN (SSN NUMBER(9));
CREATE TABLE SOC_SEC_SSN (SSN NUMBER(9));

CREATE TABLE DEMOGRAPHICS_PSN (PSN NUMBER(7));
CREATE TABLE PAYBEN_PSN (PSN NUMBER(11));
--CREATE TABLE PS_CHECKS_EMP_NUM (PSN NUMBER(7));
CREATE TABLE PROF_DIST_REQ_EMP (PSN NUMBER(7));
CREATE TABLE PROF_DIST_REQ_PSN (PSN NUMBER(11));
CREATE TABLE PYREL_PSN (PSN NUMBER(11));
CREATE TABLE PAYPROFIT_PSN (PSN NUMBER(7));

-- These tables are going to assist at finding 
-- orphan PSNs that are not tied to employees.
-- We need them for PAYBEN, PROF_DIST_REQ_PSN,
-- PYREL_PSN. We can use existing PAYPROFIT_PSN 
-- and PROF_DIST_REQ_EMP for this purpose)

CREATE TABLE PAYBEN_PSN_BASES (
    PSN NUMBER(11),
    PSN_BASE NUMBER(7)
);
CREATE INDEX PAYBEN_PSN_BASES_I ON PAYBEN_PSN_BASES ( PSN_BASE );

CREATE TABLE PROF_DIST_PSN_BASES (
    PSN NUMBER(11),
    PSN_BASE NUMBER(7)
);
CREATE INDEX PROF_DIST_PSN_BASES_I ON PROF_DIST_PSN_BASES ( PSN_BASE );

CREATE TABLE PYREL_PSN_BASES (
    PSN NUMBER(11),
    PSN_BASE NUMBER(7)
);
CREATE INDEX PYREL_PSN_BASES_I ON PYREL_PSN_BASES ( PSN_BASE );

CREATE TABLE PROFIT_DETAIL_PSN_BASES (
    PSN NUMBER(11),
    PSN_BASE NUMBER(7)
);
CREATE INDEX PROFIT_DETAIL_PSN_BASES_I ON PROFIT_DETAIL_PSN_BASES ( PSN_BASE );

CREATE TABLE PROFIT_SS_DETAIL_PSN_BASES (
    PSN NUMBER(11),
    PSN_BASE NUMBER(7)
);
CREATE INDEX PROFIT_SS_DETAIL_PSN_BASES_I ON PROFIT_SS_DETAIL_PSN_BASES ( PSN_BASE );


CREATE TABLE TINY_STORES (STORE_NUMBER NUMBER(3));
CREATE TABLE HUGE_STORES (STORE_NUMBER NUMBER(3));

-- This is a special table for storing content of
-- the PROFIT_CMNT field of PROFIT_DETAIL for 
-- obscuring and replacing PSN values in account
-- transfers.
CREATE TABLE PROFIT_CMNT_PSN (
    PROFIT_DET_RECNO NUMBER(9,0),
    PROFIT_CMNT_PREFIX VARCHAR(16),
    PROFIT_PSN NUMBER(11),
    DONE NUMBER(1) DEFAULT 0
);

COMMIT;

CREATE INDEX PROFIT_CMNT_PSN_I ON PROFIT_CMNT_PSN ( PROFIT_PSN );

-- We need the same for PROFIT_SS_DETAIL

CREATE TABLE PROFIT_SS_CMNT_PSN (
    PROFIT_SS_DET_RECNO NUMBER(9,0),
    PROFIT_SS_CMNT_PREFIX VARCHAR(16),
    PROFIT_SS_PSN NUMBER(11),
    DONE NUMBER(1) DEFAULT 0
);

COMMIT;

CREATE INDEX PROFIT_SS_CMNT_PSN_I ON PROFIT_SS_CMNT_PSN ( PROFIT_SS_PSN );

CREATE INDEX DEMOGRAPHICS_SSN_I ON DEMOGRAPHICS_SSN ( SSN );
CREATE INDEX PROFDIST_SSN_I  ON PROFDIST_SSN (SSN);
CREATE INDEX PROFDIST_PAYSSN_I ON PROFDIST_PAYSSN ( SSN );
CREATE INDEX PS_CHECKS_SSN_I ON PS_CHECKS_SSN ( SSN );
CREATE INDEX PS_CHECKS_EMP_SSN_I ON PS_CHECKS_EMP_SSN ( SSN );
CREATE INDEX PROFIT_DETAIL_SSN_I ON PROFIT_DETAIL_SSN ( SSN );
CREATE INDEX PROFIT_SS_DETAIL_SSN_I ON PROFIT_SS_DETAIL_SSN ( SSN );
CREATE INDEX PYBEN_PAYSSN_SSN_I ON PYBEN_PAYSSN ( SSN );
CREATE INDEX PYREL_PAYSSN_I ON PYREL_PAYSSN ( SSN );
CREATE INDEX PAYPROFIT_SSN_I ON PAYPROFIT_SSN ( SSN );
CREATE INDEX SOC_SEC_SSN_I ON SOC_SEC_SSN ( SSN );

CREATE INDEX DEMOGRAPHICS_PSN_I ON DEMOGRAPHICS_PSN ( PSN );
CREATE INDEX PAYBEN_PSN_I ON PAYBEN_PSN ( PSN );
--CREATE INDEX PS_CHECKS_EMP_NUM_I ON PS_CHECKS_EMP_NUM ( PSN );
CREATE INDEX PROF_DIST_REQ_EMP_I ON PROF_DIST_REQ_EMP ( PSN );
CREATE INDEX PROF_DIST_REQ_PSN_I ON PROF_DIST_REQ_PSN ( PSN );
CREATE INDEX PYREL_PSN_I ON PYREL_PSN ( PSN );
CREATE INDEX PAYPROFIT_PSN_I ON PAYPROFIT_PSN ( PSN );

CREATE INDEX TINY_STORES_I on TINY_STORES(STORE_NUMBER);
CREATE INDEX HUGE_STORES_I on HUGE_STORES(STORE_NUMBER);

COMMIT;


/*
DROP TABLE DEMOGRAPHICS_SSN;
DROP TABLE PROFDIST_SSN;
DROP TABLE PROFDIST_PAYSSN;
DROP TABLE PS_CHECKS_SSN;
DROP TABLE PS_CHECKS_EMP_SSN;
DROP TABLE PROFIT_DETAIL_SSN;
DROP TABLE PROFIT_SS_DETAIL_SSN;
DROP TABLE PYBEN_PAYSSN;
DROP TABLE PYREL_PAYSSN;
DROP TABLE PAYPROFIT_SSN;
DROP TABLE SOC_SEC_SSN;

DROP TABLE DEMOGRAPHICS_PSN;
DROP TABLE PAYBEN_PSN;
DROP TABLE PS_CHECKS_EMP_NUM;
DROP TABLE PROF_DIST_REQ_EMP;
DROP TABLE PROF_DIST_REQ_PSN;
DROP TABLE PYREL_PSN;
DROP TABLE PAYPROFIT_PSN;
DROP TABLE PROFIT_CMNT_PSN;
DROP TABLE PROFIT_SS_CMNT_PSN;

DROP TABLE PAYBEN_PSN_BASES;
DROP TABLE PROF_DIST_PSN_BASES;
DROP TABLE PYREL_PSN_BASES;
DROP TABLE PAYPROFIT_PSN_BASES;
DROP TABLE PROFIT_DETAIL_PSN_BASES;
DROP TABLE PROFIT_SS_DETAIL_PSN_BASES;

DROP TABLE TINY_STORES;
DROP TABLE HUGE_STORES;

*/