/*
    This script creates indexes on certain existing tables for performance reasons
*/

-- PROFIT_SHARE_CHECKS
DROP INDEX PROFIT_SHARE_CHECKS_SSN_I;
DROP INDEX PROFIT_SHARE_CHECKS_ESSN_I;
DROP INDEX PROFIT_SHARE_CHECKS_ENUM_I;
CREATE INDEX PROFIT_SHARE_CHECKS_SSN_I on PROFIT_SHARE_CHECKS(SSN_NUMBER);
CREATE INDEX PROFIT_SHARE_CHECKS_ESSN_I on PROFIT_SHARE_CHECKS(EMPLOYEE_SSN);
CREATE INDEX PROFIT_SHARE_CHECKS_ENUM_I on PROFIT_SHARE_CHECKS(EMPLOYEE_NUMBER);

-- DEMOGRAPHICS
-- Note: DEMOGRAPHICS columns BADGE AND SSN are already indexed

-- PAYBEN
-- Note that PYBEN_PAYSSN and PYBEN_PSN are already indexed

-- PAYREL
DROP INDEX PYREL_I;
CREATE INDEX PYREL_I on PYREL(PYREL_PSN);

-- PAYPROFIT
DROP INDEX PAYPROFIT_PROF_SSN_I;
DROP INDEX PAYPROFIT_PROF_BADGE_I;
CREATE INDEX PAYPROFIT_PROF_SSN_I on PAYPROFIT(PAYPROF_SSN); 
CREATE INDEX PAYPROFIT_PROF_BADGE_I on PAYPROFIT(PAYPROF_BADGE);

-- PROFIT_DETAIL
DROP INDEX PROFIT_DETAIL_SSEC_I;
DROP INDEX PROFIT_DETAIL_CMNT_I;
CREATE INDEX PROFIT_DETAIL_SSEC_I on PROFIT_DETAIL(PR_DET_S_SEC_NUMBER);
-- We need this next one for obscuring this overloaded field
CREATE INDEX PROFIT_DETAIL_CMNT_I on PROFIT_DETAIL(PROFIT_CMNT);

-- PROFIT_SS_DETAIL
DROP INDEX PROFIT_SS_DETAIL_SSEC_I;
CREATE INDEX PROFIT_SS_DETAIL_SSEC_I on PROFIT_SS_DETAIL(PR_SS_D_S_SEC_NUMBER);

-- SOC_SEC_REC
DROP INDEX SOC_SEC_REC_I;
CREATE INDEX SOC_SEC_REC_I on SOC_SEC_REC(SOC_SEC_NUMBER);

-- PROFDIST
DROP INDEX PROFDIST_SEX_I;
DROP INDEX PROFDIST_PD_SSN_I;
DROP INDEX PROFDIST_PAY_SSN_I;
CREATE INDEX PROFDIST_PD_SSN_I on PROFDIST(PROFDIST_SSN);
CREATE INDEX PROFDIST_PAY_SSN_I on PROFDIST(PROFDIST_PAYSSN);
-- Bitmap indexes are better when there are few possible values
CREATE BITMAP INDEX PROFDIST_SEX_I on PROFDIST(PROFDIST_SEX);

-- PROFIT_DIST_REQ
DROP INDEX PROFIT_DIST_REQ_PSN_I;
DROP INDEX PROFIT_DIST_REQ_EMP_I;
CREATE INDEX PROFIT_DIST_REQ_PSN_I on PROFIT_DIST_REQ(PROFIT_DIST_REQ_PSN);
CREATE INDEX PROFIT_DIST_REQ_EMP_I on PROFIT_DIST_REQ(PROFIT_DIST_REQ_EMP);