/* 
    This script deletes the data that was used to aid the obfuscation process, not data in the PAY9 tables, such as DEMOGRAPHICS.
*/


/* These are the tables for reducing the target data set */

DELETE FROM TARGET_EMP_PSN;
DELETE FROM TARGET_ALL_SSN;
DELETE FROM TARGET_BEN_SSN;
DELETE FROM TARGET_BEN_PSN;
DELETE FROM TARGET_ALL_PSN;

/* Normal framework temporary tables */

DELETE FROM EMP_AS_BEN_PSN;
DELETE FROM EMP_AS_BEN_SSN;

DELETE FROM PROFIT_CMNT_PSN;
DELETE FROM PROFIT_SS_CMNT_PSN;

DELETE FROM PAYBEN_PSN_BASES;
DELETE FROM PROF_DIST_PSN_BASES;
DELETE FROM PYREL_PSN_BASES;
DELETE FROM PROFIT_DETAIL_PSN_BASES;
DELETE FROM PROFIT_SS_DETAIL_PSN_BASES;

DELETE FROM EMPLOYEES_OBFUSCATED;
DELETE FROM DEMOGRAPHICS_SSN;
DELETE FROM PROFDIST_SSN;
DELETE FROM PROFDIST_PAYSSN;
DELETE FROM PS_CHECKS_SSN;
DELETE FROM PS_CHECKS_EMP_SSN;
DELETE FROM PROFIT_DETAIL_SSN;
DELETE FROM PROFIT_SS_DETAIL_SSN;
DELETE FROM PYBEN_PAYSSN;
DELETE FROM PYREL_PAYSSN;
DELETE FROM PAYPROFIT_SSN;
DELETE FROM SOC_SEC_SSN;

DELETE FROM DEMOGRAPHICS_PSN;
DELETE FROM PAYBEN_PSN;
--DELETE FROM PS_CHECKS_EMP_NUM;
DELETE FROM PROF_DIST_REQ_EMP;
DELETE FROM PROF_DIST_REQ_PSN;
DELETE FROM PYREL_PSN;
DELETE FROM PAYPROFIT_PSN;

DELETE FROM SSN_TASKS;
DELETE FROM PSN_TASKS;

DELETE FROM TINY_STORES;
DELETE FROM HUGE_STORES;

DELETE FROM LOG_MESSAGES;

COMMIT;