/*

This script assumes there ALREADY is a table called TARGET_EMP_SSN 
that is a one-column table that contains the employee SSNs that are 
in-scope for the obfuscation.

It will do the following:

- It will create an index on this table
- It will create three new tables, TARGET_EMP_PSN, TARGET_BEN_SSN, TARGET_BEN_PSN
- Indexes will be created on each of these

*/

CREATE TABLE TARGET_EMP_PSN (PSN NUMBER(7));
CREATE TABLE TARGET_BEN_SSN (SSN NUMBER(9));
CREATE TABLE TARGET_BEN_PSN (PSN NUMBER(11));
CREATE TABLE TARGET_ALL_SSN (SSN NUMBER(9));
CREATE TABLE TARGET_ALL_PSN (PSN NUMBER(11));

-- We need these two tables for reporting
CREATE TABLE EMP_AS_BEN_PSN (PSN NUMBER(11));
CREATE TABLE EMP_AS_BEN_SSN (SSN NUMBER(9));

DROP INDEX TARGET_EMP_SSN_I;
DROP INDEX TARGET_ALL_SSN_I;
DROP INDEX TARGET_EMP_PSN_I;
DROP INDEX TARGET_BEN_SSN_I;
DROP INDEX TARGET_BEN_PSN_I;
DROP INDEX TARGET_ALL_PSN_I;
DROP INDEX EMP_AS_BEN_PSN_I;
DROP INDEX EMP_AS_BEN_SSN_I;

CREATE INDEX TARGET_EMP_SSN_I on TARGET_EMP_SSN(SSN);
CREATE INDEX TARGET_EMP_PSN_I on TARGET_EMP_PSN(PSN);
CREATE INDEX TARGET_BEN_SSN_I on TARGET_BEN_SSN(SSN);
CREATE INDEX TARGET_BEN_PSN_I on TARGET_BEN_PSN(PSN);
CREATE INDEX TARGET_ALL_SSN_I on TARGET_ALL_SSN(SSN);
CREATE INDEX TARGET_ALL_PSN_I on TARGET_ALL_PSN(PSN);

CREATE INDEX EMP_AS_BEN_SSN_I on EMP_AS_BEN_SSN(SSN);
CREATE INDEX EMP_AS_BEN_PSN_I on EMP_AS_BEN_PSN(PSN);