/*

This script inserts orphan records into tables that are not
traced to DEMOGRAPHICS or PAYBEN, as they are supposed to be.

This condition can happen when an SSN changes. 

These test records can be used to test the script 
delete_orphan_ids.sql

The records have just enough fields to be valid and noticed.
*/

-- PROFIT DETAIL EMPLOYEE SSN
INSERT INTO PROFIT_DETAIL (PR_DET_S_SEC_NUMBER, PROFIT_DET_RECNO) VALUES ( -999999985, -99999999);

-- PROFIT SS DETAIL EMPLOYEE SSN
INSERT INTO PROFIT_SS_DETAIL (PR_SS_D_S_SEC_NUMBER, PROFIT_SS_SSNO, PROFIT_SS_DET_RECNO) VALUES ( -999999985, -999999986, -99999999);

-- PROFDIST EMPLOYEE SSN
INSERT INTO PROFDIST (PROFDIST_SSN, PROFDIST_PAYSEQ) VALUES ( -99999994, 1);

-- PAYREL BENEFICIARY SSN/PSN
INSERT INTO PAYREL (PYREL_PSN, PYREL_PAYSSN) VALUES ( -99999994, -9999999);

-- PROFDIST EMPLOYEE SSN
INSERT INTO PROFDIST (PROFDIST_SSN, PROFDIST_PAYSEQ) VALUES ( -99999994, 1);

-- PROFDIST BENEFICIARY SSN
INSERT INTO PROFDIST (PROFDIST_PAYSSN, PROFDIST_SSN, PROFDIST_PAYSEQ) VALUES ( -999999983, -99999984, 8);

-- PROFIT_SHARE_CHECKS EMPLOYEE SSN
INSERT INTO PROFIT_SHARE_CHECKS (EMPLOYEE_SSN) VALUES ( -999999982);

-- PROFIT_SHARE_CHECKS BENEFICIARY SSN
INSERT INTO PROFIT_SHARE_CHECKS (SSN_NUMBER) VALUES ( -999999981);

-- SOC_SEC_REC
INSERT INTO SOC_SEC_REC (SOC_SEC_NUMBER, SOC_SEC_RECNO) VALUES ( -999999981, 9999999);

-- PROFIT_SHARE_CHECKS EMPLOYEE PSN
--INSERT INTO PROFIT_SHARE_CHECKS (EMPLOYEE_NUMBER) VALUES ( -99983);

-- PROFIT_DIST_REQ EMPLOYEE PSN
INSERT INTO PROFIT_DIST_REQ (PROFIT_DIST_REQ_EMP, PROFIT_DIST_REQ_SEQ_NUM) VALUES ( -9999982, -9999995);

-- PROFIT_DIST_REQ EMPLOYEE NUMBER
INSERT INTO PROFIT_DIST_REQ (PROFIT_DIST_REQ_PSN, PROFIT_DIST_REQ_SEQ_NUM) VALUES ( -9999981, -9999994);

-- PAYPROFIT EMPLOYEE PSN
INSERT INTO PAYPROFIT (PAYPROF_BADGE) VALUES ( -9999980);
INSERT INTO PAYPROFIT (PAYPROF_BADGE) VALUES ( -9999981);
INSERT INTO PAYPROFIT (PAYPROF_BADGE) VALUES ( -9999982);
INSERT INTO PAYPROFIT (PAYPROF_BADGE) VALUES ( -9999983);
INSERT INTO PAYPROFIT (PAYPROF_BADGE) VALUES ( -9999984);
INSERT INTO PAYPROFIT (PAYPROF_BADGE) VALUES ( -9999985);
INSERT INTO PAYPROFIT (PAYPROF_BADGE) VALUES ( -9999986);
INSERT INTO PAYPROFIT (PAYPROF_BADGE) VALUES ( -9999987);
INSERT INTO PAYPROFIT (PAYPROF_BADGE) VALUES ( -9999988);
INSERT INTO PAYPROFIT (PAYPROF_BADGE) VALUES ( -9999989);
INSERT INTO PAYPROFIT (PAYPROF_BADGE) VALUES ( -9999990);
INSERT INTO PAYPROFIT (PAYPROF_BADGE) VALUES ( -9999991);
INSERT INTO PAYPROFIT (PAYPROF_BADGE) VALUES ( -9999992);

-- PAYPROFIT EMPLOYEE SSN
INSERT INTO PAYPROFIT (PAYPROF_SSN) VALUES ( -999999980);

COMMIT;
