import { CAPTIONS } from "../constants";

const pathToReadableName: Record<string, string> = {
  "": "",
  "add-distribution": CAPTIONS.ADD_DISTRIBUTION_SHORT,
  "adhoc-beneficiaries-report": CAPTIONS.PAY_BE_NEXT_SHORT,
  adjustments: CAPTIONS.ADJUSTMENTS_SHORT,
  "balance-by-age": CAPTIONS.BALANCE_BY_AGE_SHORT,
  "balance-by-years": CAPTIONS.BALANCE_BY_YEARS_SHORT,
  beneficiary: CAPTIONS.BENEFICIARY_INQUIRY_SHORT,
  "clean-up-summary": CAPTIONS.CLEAN_UP_SUMMARY_SHORT,
  "contributions-by-age": CAPTIONS.CONTRIBUTIONS_BY_AGE_SHORT,
  "december-process": CAPTIONS.DECEMBER_SHORT,
  "december-process-local": CAPTIONS.DECEMBER_PROCESS_LOCAL_SHORT,
  demographic: CAPTIONS.DEMOGRAPHIC_FREEZE_SHORT,
  "demographic-badges-not-in-payprofit": CAPTIONS.DEMOGRAPHIC_BADGES_SHORT,
  "demographic-freeze": CAPTIONS.DEMOGRAPHIC_FREEZE_SHORT,
  "dev-debug": CAPTIONS.DEV_DEBUG_SHORT,
  "distributions-and-forfeitures": CAPTIONS.DISTRIBUTIONS_AND_FORFEITURES_SHORT,
  "distributions-by-age": CAPTIONS.DISTRIBUTIONS_BY_AGE_SHORT,
  "distributions-inquiry": CAPTIONS.DISTRIBUTIONS_INQUIRY_SHORT,
  documentation: CAPTIONS.DOCUMENTATION_SHORT,
  "duplicate-names-and-birthdays": CAPTIONS.DUPLICATE_NAMES_SHORT,
  "duplicate-ssns-demographics": CAPTIONS.DUPLICATE_SSNS_SHORT,
  "edit-distribution": CAPTIONS.EDIT_DISTRIBUTION_SHORT,
  "eligible-employees": CAPTIONS.ELIGIBLE_EMPLOYEES_SHORT,
  "fiscal-close": CAPTIONS.FISCAL_CLOSE_SHORT,
  "forfeitures-adjustment": CAPTIONS.FORFEITURES_ADJUSTMENT_SHORT,
  "forfeitures-by-age": CAPTIONS.FORFEITURES_BY_AGE_SHORT,
  "frozen-summary": CAPTIONS.FROZEN_SUMMARY_SHORT,
  "it devops": CAPTIONS.IT_DEVOPS_SHORT,
  "manage-executive-hours-and-dollars": CAPTIONS.MANAGE_EXECUTIVE_HOURS_SHORT,
  "master-inquiry": CAPTIONS.MASTER_INQUIRY_SHORT,
  "military-and-rehire": CAPTIONS.MILITARY_AND_REHIRE_SHORT,
  "military-entry-and-modification": CAPTIONS.MILITARY_CONTRIBUTIONS_SHORT,
  "missing-comma-in-py-name": CAPTIONS.MISSING_COMMA_IN_PY_NAME_SHORT,
  "negative-etva-for-ssns-on-payprofit": CAPTIONS.NEGATIVE_ETVA_SHORT,
  "new-ps-labels": CAPTIONS.NEW_PS_LABELS_SHORT,
  "new-ps-labels-report": CAPTIONS.NEW_PS_LABELS_REPORT_SHORT,
  "pay426-9": CAPTIONS.PAY426_SUMMARY_SHORT,
  "pay426-final-run": CAPTIONS.PROFIT_SHARE_REPORT_FINAL_RUN_SHORT,
  pay426n: CAPTIONS.PAY426N_SHORT,
  "pay450-summary": CAPTIONS.PAY450_SUMMARY_SHORT,
  "payben-report": CAPTIONS.PAYBEN_REPORT_SHORT,
  "print-profit-certs": CAPTIONS.PRINT_PROFIT_CERTS_SHORT,
  "prof-control-sheet": CAPTIONS.PROFIT_SHARING_CONTROL_SHEET_SHORT,
  "prof-term": CAPTIONS.TERMINATIONS_SHORT,
  profall: CAPTIONS.PROFALL_SHORT,
  "profit-share-by-store": CAPTIONS.PROFIT_SHARE_BY_STORE_SHORT,
  "profit-share-gross-report": CAPTIONS.PROFIT_SHARE_GROSS_REPORT_SHORT,
  "profit-share-report": CAPTIONS.PROFIT_SHARE_REPORT_SHORT,
  "profit-share-report-edit-run": CAPTIONS.PROFIT_SHARE_REPORT_EDIT_RUN_SHORT,
  "profit-share-update": CAPTIONS.PROFIT_SHARE_UPDATE_SHORT,
  qpay066: CAPTIONS.QPAY066_UNDER21_SHORT,
  "qpay066-adhoc": CAPTIONS.QPAY066_ADHOC_SHORT,
  "qpay066-under21": CAPTIONS.QPAY066_UNDER21_SHORT,
  qpay066b: CAPTIONS.QPAY066B_SHORT,
  qpay066ta: CAPTIONS.QPAY066TA_SHORT,
  "qpay066ta-under21": CAPTIONS.QPAY066TA_UNDER21_SHORT,
  qpay600: CAPTIONS.QPAY600_SHORT,
  "recently-terminated": CAPTIONS.RECENTLY_TERMINATED_SHORT,
  "terminated-letters": CAPTIONS.TERMINATED_LETTERS_SHORT,
  "under-21-report": CAPTIONS.QPAY066_UNDER21_SHORT,
  "under-21-term-active": CAPTIONS.QPAY066TA_UNDER21_SHORT,
  unforfeitures: CAPTIONS.REHIRE_FORFEITURES_SHORT,
  "vested-amounts-by-age": CAPTIONS.VESTED_AMOUNTS_BY_AGE_SHORT,
  "view-distribution": CAPTIONS.VIEW_DISTRIBUTION_SHORT,
  "ytd-wages-extract": CAPTIONS.YTD_WAGES_EXTRACT_SHORT,
  "ytd-wages-extract-live": CAPTIONS.YTD_WAGES_EXTRACT_LIVE_SHORT
};

export const getReadablePathName = (path: string): string => {
  const basePath = path.replace(/^\/+|\/+$/g, "").split("/")[0];
  return pathToReadableName[basePath] || basePath;
};
