
const pathToReadableName: Record<string, string> = {
  "": "",
  "demographic-badges-not-in-payprofit": "Demographic Badges Not In Payprofit",
  "duplicate-ssns-demographics": "Duplicate SSNs on Demographics",
  "negative-etva-for-ssns-on-payprofit": "Negative ETVA for SSNs on Payprofit",
  "duplicate-names-and-birthdays": "Duplicate Names and Birthdays",
  "missing-comma-in-py-name": "Missing Comma in PY Name",
  "military-and-rehire": "Military and Rehire",
  unforfeitures: "UnForfeit (PREVPROF)",
  "distributions-and-forfeitures": "Distributions and Forfeitures",
  "manage-executive-hours-and-dollars": "Manage Executive Hours and Dollars",
  "eligible-employees": "Eligible Employees",
  "master-inquiry": "Master Inquiry",
  adjustments: "Adjustments",
  "distributions-by-age": "Distributions by Age",
  "contributions-by-age": "Contributions by Age",
  "forfeitures-by-age": "Forfeitures by Age",
  "balance-by-age": "Balance by Age",
  "clean-up-summary": "Clean Up Summary",
  "frozen-summary": "Frozen Summary",
  "balance-by-years": "Balance by Years",
  "vested-amounts-by-age": "Vested Amounts by Age",
  "december-process": "December Process",
  "december-process-local": "December Process Local",
  "december-process-accordion": "December Activities Summary",
  "prof-term": "Termination",
  "military-entry-and-modification": "Military Contributions",
  "profit-share-report": "Profit Share Report",
  forfeit: "Forfeit",
  "forfeitures-adjustment": "Forfeiture Adjustments",
  "fiscal-close": "Year End Flow",
  "profit-share-update": "Profit Share Update (PAY444 PAY447)",
  "profit-share-report-edit-run": "Profit Share Report Edit Run",
  "profit-share-by-store": "Profit Share by Store",
  "profit-share-gross-report": "Profit Share Gross Report",
  "pay426-1": "Pay 426 Active 18-20",
  "pay426-2": "Pay 426 Active 21 Plus",
  "pay426-3": "Pay 426 Active Under 18",
  "pay426-4": "Pay 426 Active Prior Sharing",
  "pay426-5": "Pay 426 Active No Prior",
  "pay426-6": "Pay 426 Terminated 1000 Plus",
  "pay426-7": "Pay 426 Terminated No Prior",
  "pay426-8": "Pay 426 Terminated Prior",
  "pay426-9": "Pay 426 Summary",
  "pay426-10": "Pay 426 Non Employee",
  pay426n: "PAY426N",
  "pay450-summary": "Pay 450 Summary",
  "prof-control-sheet": "Control Sheet",
  "under-21-report": "Under 21 Age Report",
  "under-21-term-active": "Under 21 Term Active Report",
  "new-ps-labels": "New PS Labels",
  qpay066: "QPAY066 - Under 21 Age Report",
  qpay066ta: "QPAY066TA - Under 21 Term Active",
  "qpay066-under21": "QPAY066 Under 21",
  "qpay066ta-under21": "QPAY066TA Under 21",
  "new-ps-labels-report": "New PS Labels Report",
  demographic: "Demographic Freeze",
  "demographic-freeze": "Demographic Freeze",
  "ytd-wages-extract": "YTD Wages Extract",
  "ytd-wages-extract-live": "YTD Wages Extract",
  profall: "Profall",
  "pay426-final-run": "Pay 426 Final Run",
  "dev-debug": "Dev Debug",
  documentation: "Documentation",
  beneficiary: "Beneficiary Inquiry",
  "adhoc-beneficiaries-report": "Pay Be Next",
  "payben-report": "Pay Beneficiary Report",
  "qpay066-adhoc": "QPAY066* Reports",
  qpay066b: "QPAY066B",
  qpay600: "QPAY600",
  "reprint-certificates": "Reprint Certificates",
  "print-profit-certs": "Print Profit Certificates",
  "recently-terminated": "Recently Terminated",
  "terminated-letters": "Terminated Letters",
  "it devops": "IT DevOps",
  "add-distribution": "Add Distribution",
  "edit-distribution": "Edit Distribution",
  "view-distribution": "View Distribution",
  "distributions-inquiry": "Distribution Inquiry"
};

export const getReadablePathName = (path: string): string => {
  const basePath = path.replace(/^\/+|\/+$/g, "").split("/")[0];
  return pathToReadableName[basePath] || basePath;
};
