import { CAPTIONS, ROUTES } from "../constants";

const pathToReadableName: Record<string, string> = {
  "": "",
  [ROUTES.ADD_DISTRIBUTION]: CAPTIONS.ADD_DISTRIBUTION_SHORT,
  [ROUTES.PAY_BE_NEXT]: CAPTIONS.PAY_BE_NEXT_SHORT,
  [ROUTES.ADJUSTMENTS]: CAPTIONS.ADJUSTMENTS_SHORT,
  [ROUTES.BALANCE_BY_AGE]: CAPTIONS.BALANCE_BY_AGE_SHORT,
  [ROUTES.BALANCE_BY_YEARS]: CAPTIONS.BALANCE_BY_YEARS_SHORT,
  [ROUTES.BENEFICIARY_INQUIRY]: CAPTIONS.BENEFICIARY_INQUIRY_SHORT,
  [ROUTES.CONTRIBUTIONS_BY_AGE]: CAPTIONS.CONTRIBUTIONS_BY_AGE_SHORT,
  "december-process": CAPTIONS.DECEMBER_SHORT, // No matching ROUTE
  demographic: CAPTIONS.DEMOGRAPHIC_FREEZE_SHORT, // No matching ROUTE
  [ROUTES.DEMOGRAPHIC_BADGES]: CAPTIONS.DEMOGRAPHIC_BADGES_SHORT,
  [ROUTES.DEMO_FREEZE]: CAPTIONS.DEMOGRAPHIC_FREEZE_SHORT,
  [ROUTES.MANAGE_STATE_TAXES]: CAPTIONS.MANAGE_STATE_TAX_RATES_SHORT,
  [ROUTES.MANAGE_ANNUITY_RATES]: CAPTIONS.MANAGE_ANNUITY_RATES_SHORT,
  [ROUTES.DEV_DEBUG]: CAPTIONS.DEV_DEBUG_SHORT,
  [ROUTES.DISTRIBUTIONS_AND_FORFEITURES]: CAPTIONS.DISTRIBUTIONS_AND_FORFEITURES_SHORT,
  [ROUTES.DISTRIBUTIONS_BY_AGE]: CAPTIONS.DISTRIBUTIONS_BY_AGE_SHORT,
  [ROUTES.DISTRIBUTIONS_INQUIRY]: CAPTIONS.DISTRIBUTIONS_INQUIRY_SHORT,
  [ROUTES.DOCUMENTATION]: CAPTIONS.DOCUMENTATION_SHORT,
  [ROUTES.DUPLICATE_NAMES]: CAPTIONS.DUPLICATE_NAMES_SHORT,
  [ROUTES.DUPLICATE_SSNS]: CAPTIONS.DUPLICATE_SSNS_SHORT,
  [ROUTES.EDIT_DISTRIBUTION]: CAPTIONS.EDIT_DISTRIBUTION_SHORT,
  [ROUTES.ELIGIBLE_EMPLOYEES]: CAPTIONS.ELIGIBLE_EMPLOYEES_SHORT,
  [ROUTES.FISCAL_CLOSE]: CAPTIONS.FISCAL_CLOSE_SHORT,
  [ROUTES.FORFEITURES_ADJUSTMENT]: CAPTIONS.FORFEITURES_ADJUSTMENT_SHORT,
  [ROUTES.FORFEITURES_BY_AGE]: CAPTIONS.FORFEITURES_BY_AGE_SHORT,
  [ROUTES.FROZEN_SUMMARY]: CAPTIONS.FROZEN_SUMMARY_SHORT,
  "it devops": CAPTIONS.IT_DEVOPS_SHORT, // No matching ROUTE
  [ROUTES.MANAGE_EXECUTIVE_HOURS]: CAPTIONS.MANAGE_EXECUTIVE_HOURS_SHORT,
  [ROUTES.MASTER_INQUIRY]: CAPTIONS.MASTER_INQUIRY_SHORT,
  [ROUTES.MILITARY_CONTRIBUTION]: CAPTIONS.MILITARY_CONTRIBUTIONS_SHORT, // No matching ROUTE (MILITARY_CONTRIBUTION is different)
  [ROUTES.NEGATIVE_ETVA]: CAPTIONS.NEGATIVE_ETVA_SHORT,
  [ROUTES.NEW_PS_LABELS]: CAPTIONS.NEW_PS_LABELS_SHORT,
  [ROUTES.PAY426_SUMMARY]: CAPTIONS.PAY426_SUMMARY_SHORT,
  [ROUTES.PAY426N_LIVE]: CAPTIONS.PAY426N_SHORT,
  [ROUTES.PAY450_SUMMARY]: CAPTIONS.PAY450_SUMMARY_SHORT,
  [ROUTES.PAY_BEN_REPORT]: CAPTIONS.PAYBEN_REPORT_SHORT,
  [ROUTES.PRINT_PROFIT_CERTS]: CAPTIONS.PRINT_PROFIT_CERTS_SHORT,
  [ROUTES.PROF_CTRLSHEET]: CAPTIONS.PROFIT_SHARING_CONTROL_SHEET_SHORT,
  [ROUTES.PROF_TERM]: CAPTIONS.TERMINATIONS_SHORT,
  [ROUTES.PROFALL]: CAPTIONS.PROFALL_SHORT,
  [ROUTES.PROFIT_SHARE_BY_STORE]: CAPTIONS.PROFIT_SHARE_BY_STORE_SHORT,
  [ROUTES.PROFIT_SHARE_GROSS_REPORT]: CAPTIONS.PROFIT_SHARE_GROSS_REPORT_SHORT,
  [ROUTES.PROFIT_SHARE_REPORT]: CAPTIONS.PROFIT_SHARE_REPORT_SHORT,
  "profit-share-report-edit-run": CAPTIONS.PROFIT_SHARE_REPORT_EDIT_RUN_SHORT, // No matching ROUTE
  [ROUTES.PROFIT_SHARE_UPDATE]: CAPTIONS.PROFIT_SHARE_UPDATE_SHORT,
  [ROUTES.QPAY066_ADHOC]: CAPTIONS.QPAY066_ADHOC_SHORT,
  [ROUTES.QPAY066_UNDER21]: CAPTIONS.QPAY066_UNDER21_SHORT,
  [ROUTES.QPAY066B]: CAPTIONS.QPAY066B_SHORT,
  [ROUTES.QPAY066TA]: CAPTIONS.QPAY066TA_SHORT,
  [ROUTES.QPAY066TA_UNDER21]: CAPTIONS.QPAY066TA_UNDER21_SHORT,
  [ROUTES.QPAY600]: CAPTIONS.QPAY600_SHORT,
  [ROUTES.RECENTLY_TERMINATED]: CAPTIONS.RECENTLY_TERMINATED_SHORT,
  [ROUTES.TERMINATED_LETTERS]: CAPTIONS.TERMINATED_LETTERS_SHORT,
  [ROUTES.UNDER_21_REPORT]: CAPTIONS.QPAY066_UNDER21_SHORT,
  [ROUTES.REHIRE_FORFEITURES]: CAPTIONS.REHIRE_FORFEITURES_SHORT,
  [ROUTES.VESTED_AMOUNTS_BY_AGE]: CAPTIONS.VESTED_AMOUNTS_BY_AGE_SHORT,
  [ROUTES.VIEW_DISTRIBUTION]: CAPTIONS.VIEW_DISTRIBUTION_SHORT,
  [ROUTES.YTD_WAGES_EXTRACT]: CAPTIONS.YTD_WAGES_EXTRACT_SHORT,
  [ROUTES.YTD_WAGES_EXTRACT_LIVE]: CAPTIONS.YTD_WAGES_EXTRACT_LIVE_SHORT,
  [ROUTES.ADHOC_PROF_LETTER73]: CAPTIONS.ADHOC_PROF_LETTER73,
};

export const getReadablePathName = (path: string): string => {
  const basePath = path.replace(/^\/+|\/+$/g, "").split("/")[0];
  return pathToReadableName[basePath] || basePath;
};
